msys2/MSYS2-packages

- repman/PKGBUILD
Repman should now be included in the MSYS2 installer.
> repman: Add to base group

- pacman/PKGBUILD
- pacman/makepkg-mingw
- Set correct `MSYSTEM`: previously, it was being set to `MINGW32` for both architectures
- Allow user to set `MINGW_INSTALLATIONS`: user can use this envvar to choose which architecture to build for
- Don't print help output twice: if `makepkg-mingw` is passed `-h` or `-V`
> pacman: makepkg-mingw improvements

- pacman/makepkg.conf
- pacman/makepkg_mingw32.conf
- pacman/makepkg_mingw64.conf
MAN_DIRS was missing a brace, which prevented man pages for mingw packages from being compressed. I added the missing brace and also moved around some slashes to prevent doubled and missing slashes in the paths.
> Fix MAN_DIRS expansion in makepkg.conf

- cyrus-sasl/PKGBUILD
- filesystem/PKGBUILD
- filesystem/profile
- gdb/PKGBUILD
- heimdal/PKGBUILD
- tar/PKGBUILD
- tzcode/PKGBUILD
- tzcode/tzcode-makefile.patch
- util-linux/PKGBUILD
Affected recipes: cyrus-sasl, filesystem, gdb, heimdal, tar, tzcode, util-linux
Also:
- add missing dependencies to gdb
- re-format filesystem PKGBUILD slightly
I can split the commit into multiple ones, if needed.
> Clean up /usr/sbin and /usr/etc

- xdelta3/0001-regtest_size_t.patch
- xdelta3/0002-disable-permission-test.patch
- xdelta3/PKGBUILD
This package is used for diffing the contents of pacman packages (see `UseDelta` option in `pacman.conf`, or `-d` option of `repo-add`, or `pkgdelta` command). It's not in `optdepends` of pacman, but that may change shortly (see https://bugs.archlinux.org/task/43723).
> new: xdelta3 for delta package functionality of pacman

- python2/0260-wrong-parameters.patch
- python2/PKGBUILD
- python3/3.3-wrong-parameters.patch
- python3/PKGBUILD
Diagnosed the source of useretail's crash. The `wrong-parameters` patch fixed one place where formatting string had one too many `%s`, but did not fix the other one.
I have the feeling that this should go upstream.
> python2, python3: Extended existing patch to fix another crash

- bc/PKGBUILD
[`bc`](https://www.gnu.org/software/bc) is an arbitrary precision numeric processing calculator language; a utility included in the POSIX P1003.2/D11 draft standard.
This package is GNU's implementation of `bc`.
> Add bc package

- whois/PKGBUILD
- whois/whois-libiconv.patch
Created a new Package for whois
The PKGBUILD is mostly the same as the one from Archlinux
The only difference is the Patch.
The Patch changes the makefile so that it also links against libiconv when building with the HAVE_ICONV switch
> whois: New Package

- vimpager-git/PKGBUILD
Syntax highlighting for man pages and the cat command.
> New package vimpager

- git/PKGBUILD
- git/git-2.3.5-mingw-pwd.patch
I have not tested this change much, but I have confirmed it fixes `git stash` in a mingw shell.
Even if the change turns out to be problematic, it definitely shouldn't affect msys2 shell or cmd, as neither of them presents as a mingw shell.
Fixes #30. Fixes #189. Ref #141 (not sure if this fixes it).
> Fix git stash in mingw shells

- filesystem/PKGBUILD
- filesystem/mingw32_shell.bat
- filesystem/mingw64_shell.bat
- filesystem/msys2_shell.bat
I have not actually tested if the bits make it into the msys2 distribution archive.
I don't see any downside to adding the empty label (`:`) to the batch files, but I could be wrong.
> filesystem: Fix execute permissions on files (should fix #222)

- filesystem/profile
```
$ MINGW_MOUNT_POINT=; [ -n $MINGW_MOUNT_POINT ]; echo $?
0
```
```
$ MINGW_MOUNT_POINT=; [ -n "$MINGW_MOUNT_POINT" ]; echo $?
1
```
> Fix empty MINGW_MOUNT_POINT handling

- lftp/PKGBUILD
I notice that lftp's GNU license dosen't include OpenSSL exception.
> lftp: Rebuild with gnutls.

- scons/PKGBUILD
- scons/scons-2.3.4-msys2-plat-mingw-env.patch
> scons: Pass few envvars to the build env to fix mingw-gcc

- pass/PKGBUILD
- pwgen/PKGBUILD
Based on Archlinux [pass](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/pass) and [pwgen](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/pwgen) PKGBUILDs (pass depends on pwgen). 
pwgen tested on 32 and 64-bits. pass is just a script.
> Add pass and pwgen packages

- ncurses/0001-CRITICAL-fix-return-value-of-drv_CanHandle-on-unknow.patch
- ncurses/PKGBUILD
A but that was recently introduced into the 6.x development branch of
ncurses causes free()d data to be reused by mistake, leading to a crash.
You can verify this by setting TERM to, say, `msys` and then running
`bash.exe --login -i`.
This fixes https://github.com/git-for-windows/git/issues/222
> ncurses: fix crash when TERM refers to an unknown terminal

- pv/PKGBUILD
pv - Pipe Viewer - is a terminal-based tool for monitoring
the progress of data through a pipeline. 
http://www.ivarch.com/programs/pv.shtml
I just took pv from official site and compiled it with no problems. 
Two tests are failing though - first is remote-format and second is remote-cksum
That really doesn't bother me, because my usecases are mostly something like **pv large_file > copy_of_large_file** . And if you add --nocheck flag the package is buit with no problems.
Please, consider adding pv to packages in that state, it's really useful, when you need a progress bar.
> pv package

- mosh/PKGBUILD
Finally with xterm mouse support. The bash-completion script is now installed automatically.
> mosh: Update to 1.2.5

- python-mock/PKGBUILD
I was too quick yesterday, the python 3 counterpart of mock should use python3-mock as pkgname.
> python-mock: update naming to match other python 3.x packages in msys2

- xz/PKGBUILD
Tested with https://ci.appveyor.com/project/fracting/msys2-packages/build/1.0.63#L1782
> xz: Fix dependency.

- crosstool-ng/0003-modify-kconfig-make-lintl.patch
- crosstool-ng/0004-kconfig-nconf-fix-compile-with-ncurses-reentrant-API.patch
- crosstool-ng/PKGBUILD
Made a pull request for the open issues 9 and 277
https://github.com/diorcety/crosstool-ng/issues/9
https://github.com/Alexpux/MSYS2-packages/issues/277
The patches are based on:
http://cygwin.com/ml/cygwin/2012-06/msg00221/0004-kconfig-nconf-fix-compile-with-ncurses-reentrant-API.patch
https://sourceware.org/ml/crossgcc/2012-05/msg00012.html
> crosstool-ng patches 0003/0004 - Fix compile (issues: 9, 277)

- docx2txt/PKGBUILD
docx2txt is a perl based conversion tool to convert docx files to plain
text. It simplifies comparing the content of docx files a lot.
Its usage is simple:
docx2txt.pl [infile.docx|-|-h] [outfile.txt|-]
docx2txt.pl < infile.docx
docx2txt.pl < infile.docx > outfile.txt
Signed-off-by: Matthias Aßhauer <mha1993@live.de>
> Add the docx2txt Package

- bash-completion/PKGBUILD
- bash-completion/quote_readline_by_ref_fixes.patch
When connected to an Active Directory (a variant of LDAP), tab completion
becomes very slow because the tilde is expanded all the time, even if
completing paths that do not contain a tilde at all. This developer
observed delays of several seconds at a time.
This is completely unnecessary, so let's do not do that.
The patch was provided by Ove Risberg with a bug report to the original
bash-completion project:
https://bugs.launchpad.net/ubuntu/+source/bash-completion/+bug/1390061
Since it fixes code introduced by another add-on patch, that add-on patch
was modified instead of adding yet another patch.
This fixes https://github.com/git-for-windows/git/issues/377
> bash-completion: avoid unnecessary tilde expansion

- vim/PKGBUILD
- vim/accept-crlf.patch
It was noticed in https://github.com/git-for-windows/git/issues/272 and https://github.com/git-for-windows/git/issues/364 that MSys2's `vim` has problems when the user's `$HOME/.vimrc` contains DOS line endings. This is quite common when MSys2 is configured with the regular Windows home directory as `$HOME`.
It's easy to support, so let's do that.
> Support ~/.vimrc with DOS line endings

- winpty-git/0004-Set-the-appropriate-locale.patch
- winpty-git/PKGBUILD
This is necessary to deal with non-ASCII command-line parameters correctly.
I also submitted this as a [Pull Request to winpty](https://github.com/rprichard/winpty/pull/37) but I figured it would not hurt to have it in MSys2 as soon as possible.
This fixes https://github.com/git-for-windows/git/issues/412
> Fix winpty's locale

- git-flow/PKGBUILD
The https://github.com/nvie/git-flow repository appears to be
abandoned. The common wisdom is that Peter van der Does' AVH edition
is the legitimate successor:
https://github.com/petervanderdoes/gitflow-avh
This fixes issue https://github.com/git-for-windows/git/issues/416
Original-patch-by: Robert Dailey <rcdailey@gmail.com>
> Switch git-flow to use the AVH edition

- winpty-git/0002-Add-support-for-conversion-of-all-argv-path-args.patch
- winpty-git/PKGBUILD
In 35510397c6e92845dbad8cdb215d3bef67dc2529, patch `0002-Add-support-for-conversion-of-all-argv-path-args.patch` was removed because it was thought to be superseded by an upstream commit[1], but that was actually only one part of the patch. This commit restores the patch minus the upstreamed part. Fixes #360.
[1] https://github.com/rprichard/winpty/commit/2ecc596f8b191b8b8cd90dfffba162985d3ed0e3
> winpty-git: Restore path mangling of all command-line arguments

- mutt/PKGBUILD
Created a new Package for mutt
The PKGBUILD is mostly the same as the one from ArchLinux (https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/mutt)
The most important difference is the `--with-mailpath=/var/spool/mail`
The configure Script searches if a valid mail path exists. It looks for the following four directories:
1. `/var/mail`
2. `/var/spool/mail`
3. `/usr/spool/mail`
4. `/usr/mail`
The first existing directory will be used. If none of these directories exist you need to specify one with the `--with-mailpath` option. 
I choose `/var/spool/mail` because it made the most sense to me.
> mutt: New Package (Version 1.5.24)

- git-flow/PKGBUILD
rebuilded and tested git-flow locally with Git for Windows (2.6.3.1) SDK (1.0.1) with some feature and release branches.
> updated git-flow package to use stable master branch (version 1.9.1 now)

- readline/PKGBUILD
- readline/readline-6.3-paste-utf8.patch
The call to GetClipboardData(CF_TEXT) returns the text in the system
encoding, which was then incorrectly treated as UTF-8 encoded. Instead we
need to use GetClipboardData(CF_UNICODETEXT) to get the text in UTF-16,
followed by a conversion to UTF-8.
Also fixed a problem where CloseClipboard was only called if
GetClipboardData returns non-null. According to the documentation, every
successful call to OpenClipboard should be matched with a call to
CloseClipboard.
This fixes https://github.com/git-for-windows/git/issues/567
Signed-off-by: Kim Gybels <kgybels@infogroep.be>
> readline: convert clipboard data to UTF-8 encoding

- w3m/0001-Accomodate-MSys2-s-libgc-API.patch
- w3m/0002-MSys-Make-sure-that-setmode-is-declared.patch
- w3m/PKGBUILD
The w3m tool is particularly useful when rendering HTML pages into plain
text, as Git for Windows needs to do with its release notes.
> Add a build script for w3m, a pager with WWW capabilities

- pacman-mirrors/mirrorlist.mingw32
- pacman-mirrors/mirrorlist.mingw64
- pacman-mirrors/mirrorlist.msys
Current locations are broken in 3 ways:
$ wget --spider --no-check https://www2.futureware.at/~nickoe/msys2-mirror/x86_64/mingw64
WARNING: The certificate of ‘www2.futureware.at’ is not trusted.
WARNING: The certificate of ‘www2.futureware.at’ hasn't got a known issuer.
HTTP request sent, awaiting response... 404 Not Found
Remote file does not exist -- broken link!!!
1. Bad certificates - links need to be HTTP until this is fixed
2. Location has changed - now `x86_64` rather than `mingw64`
3. Final `/` is needed to avoid a redirect:
$ wget --spider http://www2.futureware.at/~nickoe/msys2-mirror/x86_64
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www2.futureware.at/~nickoe/msys2-mirror/x86_64/ [following]
> Fix futureware mirror

- curl/PKGBUILD
- serf/PKGBUILD
This is a try to add GSSAPI/Kerberos authentication for the git-svn interface. In big organization Subversion servers probably using Kerberos for authentication via Apache and mod_auth_kerb or https://github.com/modauthgssapi/mod_auth_gssapi in combination with a directory server. The functionality was tested with MS AD but should also work for other directory servers.
That the authentication is working for 2 libraries the build needs to be enhanced. The first is the curl library the second one is the serf library. 
Please notice that I disabled the checks for serf because they were failing with error:
```shell
scons: *** [check] Source test/serf_get' not found, needed by targetcheck'.
scons: building terminated because of errors.
```
I did not investigate this on my Linux boxes it is …
> Enabeling GSSAPI/Kerberos authentication for git-svn

- openssh/PKGBUILD
That version fixes CVE-2016-0777, a vulnerability that can be exploited
via a compromised SSH server. For details, see
http://www.openssh.com/txt/release-7.1p2
> Upgrade OpenSSH to version 7.1p2

- .drone.yml
- drone/build.sh
Hi, I've setup a Wine based Drone CI server at wine-ci.org, and created build script for MSYS2-packages, could you accept this script and register your account at wine-ci.org, so I can have real data to test the Wine CI server?
> Add drone build script.

- drone/build.sh
The CI script should return failure if the build was not success.
Bad example:
http://wine-ci.org/Alexpux/MSYS2-packages/1
Good example:
http://wine-ci.org/fracting/MSYS2-packages/6
The standard way to solve this problem is adding `set -e` to build.sh, it was my fault didn't set it at the first time.
> drone: Return error when build failed.

- .drone.yml
- drone/build.sh
- pacman/PKGBUILD
In this pull request, I add matrix build to .drone.yml:
```
matrix:
runtest:
- false
- true # allow failures
```
Drone CI will run two build for every commit, one without `make check`, the other with `make check` but ignore the test errors.
Example: http://wine-ci.org/fracting/MSYS2-packages/16
In a long term, I'll try to maintain a white list / black list, incrementally force `make check` for more and more packages, push more packages to pass their test suite (on both Windows and Wine).
(BTW, wine-ci.org is slow, with only one vCPU, I'll upgrade it in a few days)
> Introduce matrix build in Drone CI. Fix makedepends of pacman.

- appveyor.sh
- appveyor.yml
This adds AppVeyor CI for MSYS2 packages. When commits update package recipes, `makepkg` will be automatically executed for building the new package versions. Alexey, once you create your account in AppVeyor, simply pushing new commits should trigger the automated builds.
Since multiple packages can be touched and built per commit and some packages may take more than one hour for building, it is also interesting to ask AppVeyor for increasing the time limit to a few hours or something. I think they will be receptive about this.
> AppVeyor continuous integration

- cyrus-sasl/09-digest-md5-Remove-annoying-debug-message.patch
- cyrus-sasl/PKGBUILD
Every time an svn call is made, the message "DIGEST MD5 common mech free"
appears in the application event log viewer. Other communities (See
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1372451.html)
are supressing the message with a logcheck snippet. Since we do not have
such a luxury in the msys2 environment, lets just remove the debug message
for good.
This fixes https://github.com/git-for-windows/git/issues/616
Signed-off-by: 마누엘 <nalla@hamal.uberspace.de>
> cyrus-sasl: Remove annoying debug message

- ci-build.sh
* New implementation for detection of changed recipes.
* Merge dependency installation and actual build into one single makepkg call.
* Use `--cleanbuild` and `--rmdeps` in makepkg call.
* Source code refactoring.
> Improvements for continuous integration

- delta/PKGBUILD
- diffstat/PKGBUILD
- gc/PKGBUILD
- irssi/PKGBUILD
- isl/PKGBUILD
- man-db/PKGBUILD
- man/PKGBUILD
- perl-Exporter-Lite/PKGBUILD
- perl-File-Which/PKGBUILD
- tig/PKGBUILD
- zsh/PKGBUILD
Only these two remained MD5, both broken: `cygrunsrv`, `libevent`
> switch to sha256 for some more packages

- serf/07-sspi-auth.patch
- serf/PKGBUILD
This patch enables SSPI - the Windows integrated authentication for the serf library. As result serf is using the users Kerberos TGT from the MS LSA for authentication against a kerberised Subversion server.
@dscho created the patch  originally, have a look to the [conversation](https://github.com/git-for-windows/git/issues/550).
> enabling SSPI authentication for serf

- .drone.yml
Now our CI has multiple server as workers, as a result, same configuration running on different worker machines might have different environment especially docker image version. docker image tag "latest" doesn't really mean latest build from upstream, it is just a name. To force fetch latest build, we need to enable "pull: true" in .drone.yml.
This patch should fix failure in https://tea-ci.org/Alexpux/MINGW-packages/371 which was caused by outdated msys2-runtime with an upgrade without restart.
I'll send a similar patch to MINGW-packages repo.
> Drone CI: Always pull latest image.

- mpfr/PKGBUILD
mpfr package had invalid version 3.1.4.-3 when it should have been
3.1.4-3. This was caused because an empty _patchlevel was set appended
to the package version separated with a dot.
This commit changes the package versioning so that the _patchlevel is
appended to the package version only if it isn't empty.
Similar commit 0c86b53 was done to mpfr package in MINGW-packages.
> mpfr: Fix versioning

- filesystem/dot.inputrc
fix for https://github.com/Alexpux/MSYS2-packages/issues/511
> filesystem: handle ctrl+[right/left] for word forward/backward in mintty

- filesystem/mingw32_shell.bat
- filesystem/mingw64_shell.bat
- filesystem/msys2_shell.bat
bypass result of "start" to calling process.
Currently if Msys is started from another .bat file by `call path/mingw64_shell.bat`, those .bat file is terminated at this command. To exit only from .bat file instead of terminating cmd.exe, `exit /b` must be used.
> .bat-files: exit only from .bat file instead of terminating parent command processor

- filesystem/mingw32_shell.bat
- filesystem/mingw64_shell.bat
- filesystem/msys2_shell.bat
Shift command don't change value of %* so numbered parameters are required.
> Fix handling quoted parameters, fix handling '-mintty' parameter

- filesystem/PKGBUILD
- filesystem/start_shell.cmd
ConEmu used only if requested by `-conemu` parameter.
> .bat-files: added support for ConEmu terminal emulation

- bc/PKGBUILD
> I believe the gcc dependency is not needed there

- jsoncpp/PKGBUILD
expecting install under "/usr"
no under the root "/"
#548
> jsoncpp install pkgdir

- ccache/MSYS2-dont-use-symlinks.patch
- ccache/PKGBUILD
Ccache for MSYS2.
Thanks to it recompilation with makepkg is much faster also allows to speed up manual recompilation after adding /usr/lib/ccache/bin/ to PATH (`export PATH="/usr/lib/ccache/bin/:$PATH"`).
Normally there would be symlinks to ccache inside /usr/lib/ccache/bin but they don't work out of box in MSYS2. This workaround creates bash scripts executing ccache with proper command.
If someone knows better solution to do it I'll change it. Also if this workaround is acceptable I'll do similar to MinGW ccache package.
EDIT: By the way could some restart tea-ci?
It freeze with `err:seh:setup_exception_record stack overflow 768 bytes in thread 017b eip 611244f9 esp 0060a9e0 stack 0x410000-0x60a9b0-0x610000` in 2 latest commits.
> ccache: add MSYS package

- easyoptions-git/PKGBUILD
[EasyOptions](https://github.com/renatosilva/easyoptions) makes it easy parsing options in Bash and Ruby scripts. For example:
* https://github.com/renatosilva/scripts/blob/master/bzrgrep.rb
* https://github.com/renatosilva/pidgin-plus/blob/master/build/winbuild.sh
> New package easyoptions

- msys2-installer/qt-ifw/packages/com.msys2.root.base/meta/installscript.js
The shortcuts created by installer are now simplified from this:
```batch
C:\Windows\System32\cmd.exe /A /Q /C C:\MSYS2\msys2_shell.bat
C:\Windows\System32\cmd.exe /A /Q /C C:\MSYS2\mingw32_shell.bat
C:\Windows\System32\cmd.exe /A /Q /C C:\MSYS2\mingw64_shell.bat
```
To this:
```shell
C:\MSYS2\start_shell.cmd -msys
C:\MSYS2\start_shell.cmd -mingw32
C:\MSYS2\start_shell.cmd -mingw64
```
> Simplify shell shortcuts

- task/PKGBUILD
This is a command line productivity tool also called [Taskwarrior](https://taskwarrior.org/). It is a highly flexible open source todo list.
It has no support for Windows, so it's on Cygwin.
I'm not an official maintainer or anything, but a user who wanted to use taskwarrior on MSYS2 rather than Cygwin. Dependencies were tested on my MSYS2-x86_64. I borrowed pieces from the official Arch package and the git AUR package, in addition to adding testing.
There are two oddities: the official tar has broken symlinks which causes makepkg to fail, so I download the git repo and switch to the tag instead. In addition, task originally crashes when run, because libgnutls did not install libhogweed, so that is included as a dependency.
The tests has a few failures (out of roughly a thousand), but I …
> New MSYS package: task

- updpkgver-git/PKGBUILD
This tool searches for new source releases and updates the recipe version automatically. It can be used by package maintainers for keeping recipes up-to-date. Another possible usage is creating update bots that automatically detect and commit buildable upstream releases into the repository. Some examples:
Update maintained packages with analysis report:
```bash
updpkgver --maintainer --report
git diff
```
Update all packages committing successful builds and discarding failed ones:
```bash
updpkgver --commit
updpkgver --reset
```
> New package updpkgver

- filesystem/start_shell.cmd
When passing the optional _-here_ argument to start_shell.cmd, mintty will be started in the current working directory instead of the home directory.
This should be a first step towards being able to conveniently spawn a new MSYS2 shell from within a folder of the Windows Explorer. The MSYS2 installer could offer the user to add a respective entry to the context menu, for example.
> Add -where parameter to start_shell.cmd

- appveyor.yml
- ci-build.sh
- ci-library.sh
* Fix the incomplete system update in AppVeyor after new pacman extended the core package list and the explicit references became outdated. This was causing the core update to be completed only in ci-build script, and the regular update to be left behind. For example, #575 seems to have reproduced the problem.
* Fix failure detection for package installation, avoiding false positives like [MINGW-packages#1376](https://github.com/Alexpux/MINGW-packages/pull/1376).
* Explicitly set a default shell in AppVeyor, avoiding failures like reproduced by #587.
* Package downgrades are now enabled for regular updates and for AppVeyor core updates, so removed versions are properly detected.
* Git is now explicitly installed in AppVeyor since the external one is not anymore visible after minimal path …
> Fixes for continuous integration

- gdb/PKGBUILD
Fixes importError:
```
Traceback (most recent call last):
File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
```
> gdb: fix path for gcc-5.3.0 libstdcxx

- winpty-git/0002-fix-path-conversion.patch
- winpty-git/PKGBUILD
- winpty/0002-fix-path-conversion.patch
- winpty/PKGBUILD
Fix path conversion from unix to Windows format, and a build problem caused by mingw-w64-cross-crt-clang-git. Conversion example:
```
$ winpty cmd //c echo //path is /path
/path is C:/MSYS2/path
```
> Fixes for winpty

- ccache/PKGBUILD
- ccache/ccache.install
The compilers available from system path are now used, and the wrapper scripts have been replaced with symlinks. Fixes #562 and removes the need for mingw-w64-ccache.
* Support both MINGW and MSYS toolchains.
* Fix ccache option for makepkg-mingw.
* Update to 3.2.5.
> Some improvements for ccache

- rsync/PKGBUILD
- rsync/rsync-3.1.0-msys2.patch
Because of this commit https://github.com/mirror/newlib-cygwin/commit/9ddf063921f5202100f8e36bb451ae5ac9f76d37 rysnc should use to POSIX ACL
This commit lets it be auto detected rather than hard code it to use SOLARIS_ACLS
> Fix rsync build

- subversion/PKGBUILD
I am grappling with a problem (the infamous Win32 error 1114) when loading `msys-svn_subr-1.0.dll` and while at it, I realized that a new Subversion version was released. Might just as well upgrade ;-)
> Upgrade Subversion to 1.9.4

- .drone.yml
Now we bring 64 bit support to Tea CI, next step is adding package uploading script so users can have a convenient way to download testing packages.
Same to https://github.com/Alexpux/MINGW-packages/pull/1425
> Continuous Integration: Enable 64 bit build.

- appveyor.yml
AppVeyor has [recently updated](https://github.com/appveyor/ci/issues/765) the MSYS2 installation, so manual installation of git and latest pacman is not necessary anymore.
> Updates for continuous integration

- ci-library.sh
Fix for package change detection where sometimes it fails, for example as reproduced by #620.
> Fix for continuous integration

- gnupg/PKGBUILD
- gnupg/gnupg.install
- pinentry/PKGBUILD
- pinentry/pinentry.install
A couple more have crept in since c3d40c1afe76810bdbb49e35f369279157fd4653.
> bashisms: remove arrays [+fix pinentry build]

- filesystem/PKGBUILD
- filesystem/msys2_shell.cmd
Restore the -mingw and -msys2 parameters as deprecated, since some users may be using them. For example see #623.
> Adjustment for shell starter

- subversion/20-fix-stack-corruption-in-swig-wrappers.patch
- subversion/PKGBUILD
Subversion's script bindings (which are used in git-svn) can cause
segmentation faults simply by corrupting the stack under memory
pressure.
This bug was already fixed in Subversion's trunk, but that fix did not
make it into Subversion 1.9.4. Let's forward-port that patch manually.
See http://article.gmane.org/gmane.comp.version-control.git/298427 for
full details.
Reported by Ioannis Kappas.
> subversion: avoid stack corruption in script bindings

- cmake/PKGBUILD
- cmake/cmake-3.5.2-msys.patch
patch stripped a needed closing paran causing cmake builds that use boost to fail
> Fix to missing closing paran in FindBoost.cmake

- ci-library.sh
Fix the below error demo by https://tea-ci.org/fracting/MSYS2-packages/117:
```
warning: pactoys-git-r2.07ca37f-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
Packages (1) pactoys-git-r2.07ca37f-1
Total Installed Size:  0.09 MiB
Net Upgrade Size:      0.00 MiB
:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
:: File /var/cache/pacman/pkg/pactoys-git-r2.07ca37f-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package (checksum))
Errors occurred, no packages were upgraded.
[MSYS2 CI] FAILURE: Updating system failed.
```
> CI: Use --needed when installing pactoys.

- filesystem/PKGBUILD
- filesystem/bash.bashrc
6e6310d (filesystem: New specific variable MSYS2_PS1., 2016-05-01)
introduced the MSYS2_PS1 prompt script proriority to allow multiple
device configurations.
Unfortunately it overwrote the $PS1, even when specifically set by the
users configuration, such as the Git-for-Windows SDK
see https://github.com/git-for-windows/git/issues/794#issuecomment-227401839
and the monkey patch fix
https://github.com/git-for-windows/build-extra/pull/122.
Introduce a priority order so that the user's $PS1 (if set) has an
intermediate priority between the MSYS2_PS1 and the default PS1.
Signed-off-by: Philip Oakley <philipoakley@iee.org>
> bashrc: re-include $PS1 priority

- filesystem/PKGBUILD
- filesystem/bash.bashrc
Should fix regression introduced by #651
bash use some default value for PS1, but this value is not exported. This allow us to distinguish between user-defined PS1 and bash automatic default PS1.
> bash.bashrc: Update PS1 if PS1 wasn't exported.

- filesystem/PKGBUILD
- filesystem/msys2_shell.cmd
Currently msys2_shell.cmd has several issues:
* You cannot pass parameter to shell, if you have directory with the same name. For example, command `msys2_shell.cmd -here -c 'bash -c ls; sleep 5'` will not work if you have directory named `-c`.
* You cannot use directory names like '-help', '-mingw64' and so on - they will be interpreted as parameters. Moreover, last parameter will be used as directory name. For example command `msys2_shell.cmd -mingw64 -here -msys -defterm scripts` will launch **MSys** shell instead of **MinGW64** shell in directory **`scripts`** instead of directory **`-msys`** (even if `-msys` directory is present).
* If you mistyped name of working directory, it will be silently passed as bash parameter. For example `msys2_shell.cmd -mingw64 -here my_driectory` will …
> msys2_shell.cmd updates and fixes

- msys2-launcher-git/PKGBUILD
Use correct epoch when specifying mintty dependency:
mintty package started using an epoch value since version 1~2.0.3 (92fcd06).
> msys2-launcher-git: correct mintty epoch value

- openssl/PKGBUILD
> Upgrade openssl to 1.0.2j

- openssh/PKGBUILD
- openssh/openssh-7.3p1-msys2-drive-name-in-path.patch
This patch was also proposed to upstream developers:
http://lists.mindrot.org/pipermail/openssh-unix-dev/2016-September/035381.html
> openssh: allow scp to copy files using their Windows paths.

- curl/PKGBUILD
This version closes 11 critical bugs, along with other bugs.
> curl: upgrade to v7.51.0

- libarchive/PKGBUILD
- libarchive/libarchive-3.2.2-path_fix.patch
Latest version
Add patch for a compiler error.  I have taken the liberty of making a
merge request to the libarchive developers.
https://github.com/libarchive/libarchive/pull/818 .  I deally, I would
like to remove all patches from this.
> libarchive - 3.2.2 Update to latest version

- procps-ng/PKGBUILD
- procps-ng/procps-ng-3.3.12-msys2.patch
When installing this package, it will replace the older `procps`.
> procps-ng: add 3.3.12

- binutils/0001-coff-linker-weak-nt-externals.patch
- binutils/0002-gas-aux-nt-weak-externals.patch
- binutils/0003-objcopy-weak-nt-externals2local.patch
- binutils/PKGBUILD
The rollback to 2.25.1 (https://github.com/Alexpux/MSYS2-packages/commit/660ffd3fd117a22f3dff71d80edf56ad4a188c26) caused those patches to be disabled. The commit mentions some instability of 2.26 but I couldn't find more information on what specifically was unstable. 
I rebased the weak NT externals patches on 2.25.1.
> binutils: re-enable weak NT externals patches

- msys2-runtime/PKGBUILD
As @jan-hudec noticed we have to disable null pointer optimization until Cygwin fixes their code.
Closes https://github.com/Alexpux/MSYS2-packages/issues/793
Zsh doesn't crash, tested with:
```
mati865@DESKTOP-0J8VPHJ MSYS ~
$ zsh -c 'FOO=$(echo foo)'
mati865@DESKTOP-0J8VPHJ MSYS ~
$
```
> msys2-runtime: better workaround for GCC 6

- filesystem/PKGBUILD
- filesystem/profile
I discovered that zsh as a login shell does not source `/etc/profile.d/lang.sh` and `/etc/profile.d/tzset.sh`. I think this behavior should mirror the upstream behavior in the Arch [`/etc/profile`](https://git.archlinux.org/svntogit/packages.git/tree/trunk/profile?h=packages/filesystem) and source `/etc/profile.d/*.sh` when running zsh.
I didn't change `/etc/profile` to stop sourcing `*.zsh`, in case someone's configuration was depending on it.
> Also source /etc/profile.d/*.sh for zsh

- fish/PKGBUILD
Additional Changes:
* add dependency on `man-db`
- `fish` uses `apropos.exe` at tab-completion
> fish: update to 2.5.0

- cmake/PKGBUILD
- cmake/cmake-3.6.0-msys.patch
The patch used in PKGBUILD for cmake missed a bracket. This is a regression and had been already fixed in #646.
> Fix missing bracket in cmake FindBoost

- pacman-mirrors/mirrorlist.mingw32
- pacman-mirrors/mirrorlist.mingw64
- pacman-mirrors/mirrorlist.msys
It is useful, now that HTTPS got enabled on all mirrors,
according to: https://sourceforge.net/blog/small-but-significant-changes-to-project-pages/
> enable HTTPS for sf.net pacman mirror

- rsync/PKGBUILD
Using the system's zlib disables -z.
The default is to use the included zlib, which is compatible with older
rsync versions.
Arch also doesn't pass --without-included-zlib[1].
[1] https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/rsync
> rsync: Use included zlib

- libqrencode-git/PKGBUILD
- pass/PKGBUILD
Pass 1.7 dropped the pwgen dependency and added an optional dependency: [libqrencode](http://fukuchi.org/works/qrencode/).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alexpux/msys2-packages/833)
> Update pass to 1.7 and add libqrencode package

- filesystem/PKGBUILD
- filesystem/bash.bashrc
- mintty/0002-add-msys2-launcher.patch
- mintty/0003-fix-current-dir-inheritance-for-alt-f2-on-msys2.patch
- mintty/PKGBUILD
Adds a shell selection dialog that pops up when the terminal is launched without command line arguments, as well as duplicated with `Alt-F2`. For the latter use case, this also fixes `cd ~` by `/etc`.
> Taskbar-pinnable mintty

- pass/PKGBUILD
[Pass 1.7.1 was released](https://lists.zx2c4.com/pipermail/password-store/2017-April/002892.html) a few weeks ago.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alexpux/msys2-packages/895)
> pass: Update to 1.7.1

- gcc/PKGBUILD
remove the bogus escape of the $ character
Fixes issue #886
> gcc: fix c89/c99 scripts

- openssh/PKGBUILD
For some reason, the test_utf8 tests fail here, probably because
snmprintf() does not return what OpenSSH expects... But UTF-8 is not
native to Windows anyway (at least not yet).
> openssh: bump to 7.5p1

- pacman/0006-makepkg-avoid-creating-.tar-files-with-extended-attr.patch
- pacman/PKGBUILD
Extended attributes are not necessary for pacman to work. Extended
attributes may not even be supported by the file system to which we
extract the files.
And worst of all: pacman cannot handle extended attributes, but simply
stops extracting files when it encounters an extended attribute.
This is particularly nasty when creating packages on a system configured
to cache, say, file integrity information about .exe files in extended
attributes, as the created packages will fail to install any .exe files.
The fix is very easy: simply pass the -no-xattrs option to bsdtar.
> pacman: Force makepkg to produce .tar files without extended attributes

- zsh/PKGBUILD
- zsh/user-autocomplete.patch
Under windows user name can contains local characters. Without metafy sometimes we get infinite loop and segfault. 
Upstream commit https://github.com/zsh-users/zsh/commit/a11b241d4a5ec7ee1009905372cf32fb4538fbb3
> Fix segfault on user autocomplete in zsh

- ncurses/PKGBUILD
Required for enabling compilation of sipp.
> ncurses: Add missing "links" for compatibility

- msys2-runtime/0002-Rename-DLL-from-cygwin-to-msys.patch
- msys2-runtime/PKGBUILD
- msys2-w32api-headers/PKGBUILD
- msys2-w32api-runtime/PKGBUILD
msys2-runtime/PKGBUILD - Update newlib to 2.8.1
msys2-w32api-headers/PKGBUILD - Update to latest
msys2-w32api-runtime/PKGBUILD - Update to latest
> msys2-runtime/0002-Rename-DLL-from-cygwin-to-msys.patch - Update patch

- dialog/PKGBUILD
- emacs/PKGBUILD
- libedit/PKGBUILD
- nano/PKGBUILD
- ncurses/PKGBUILD
dialog - 20170509 - Update to latest version
emacs -  2.52 - fix conflicts with ctags.  Allow ctags in package under new name
libedit - 2017050329 - Update to latest version
nano - 2.8.5 - Update to latest version
ncurses - 20170708 - Update to latest version
> ncurses and some updated version:

- crosstool-ng-git/0001-stat-check.patch
- crosstool-ng-git/PKGBUILD
- crosstool-ng/0005-GNU-stats-test.patch
- crosstool-ng/PKGBUILD
1. Fix crosstool-ng package using the newest release
2. Fix crosstool-ng-git package built using master branch
Signed-off-by: Ilya Rakhlin <i.rakhlin@gmail.com>
> fix crosstool-ng & crosstool-ng-git packages

- mintty/PKGBUILD
Hello.
It would be nice to have [this fix](https://github.com/mintty/mintty/commit/41489236ded1) released.
I tried the new version with same patches and it seems to work.
> mintty: upgrade to latest version 2.7.9

- libidn2/PKGBUILD
After upgrading msys2 today, gnupg was broken, because of a transitive dependency on libcurl -> libidn2, which depends on libunistring, but I didn't have that installed.
> libidn2: Fix dependency on libunistring

- nettle/PKGBUILD
Without `libhogweed` mutt refuses to start with missing library error. 
Also, in Arch `libhogweed.so` is part of `nettle` package itself, not sure why it was decided here to split it into separate package.
> libnettle: fix missing dependency on libhogweed

- gnupg/0001-Introduce-GPG_ASKPASS-support.patch
- gnupg/PKGBUILD
It is all fine and dandy when users GPG-sign files from the terminal.
But when they do not, things get more complicated.
The usual thing is to install a pinentry helper targeting your graphical
desktop and then launching the GPG agent somehow and connet it all
together.
Except that MSYS2 does not come with a gpg-agent.
So let's just imitate openssh, which interprets the environment variable
SSH_ASKPASS (if set) as the path to a helper that can be called upon to
ask the user to provide a passphrase.
Unsurprisingly, the new environment variable is called GPG_ASKPASS (and
we do not repeat Git's mistake of co-opting SSH_ASKPASS, if set).
This allows, say, Git for Windows' Git GUI to commit with GPG signatures
even if the passphrase is not empty.
Signed-off-by: Johannes Schindelin …
> gnupg: introduce GPG_ASKPASS support

- libunistring/PKGBUILD
unistring gets pulled in through curl but was missing a static build.
> libunistring: package static lib; fixes pacman build

- pacman/0007-exe-interp-ignore-file-conflict.patch
- pacman/PKGBUILD
In case a file "foo.exe" gets renamed to "foo" the msys2 .exe
interpolation makes pacman think an untracker file is replaced.
In case foo and foo.exe are the same file and foo.exe existed
in the old package version we can be sure it's handled by the
old package and ignore the conflict.
> pacman/libalpm: ignore file conflicts for foo.exe -> foo renames

- winln/PKGBUILD
1. Add package winln using code from a similar package in cygwin. It follows the same commands as ln, only uses native windows API to create actual symlinks. This may be useful to alot of requests I have seen before to create symlinks in msys2..
> Add new package; winln

- libpsl/PKGBUILD
- sqlite/PKGBUILD
It was reported on IRC that installing wget on appveyor wont
update icu which results in icu not being found due to an ABI bump/dll rename.
Bumping the version requirements of icu users should fix this.
> Bump icu dependency requirements to the newest version.

- coreutils/PKGBUILD
The `stdbuf.exe` program links to a `libstdbuf.so` file, so if that does
not exist, there is a problem.
In d9773f0a (coreutils: Update to 8.24, 2015-08-28), a sed call was
introduced to ensure that `libstdbuf.so` is built and installed under
that name, without `.exe` suffix.
As reported in https://github.com/Alexpux/MSYS2-packages/issues/541,
however, that fix no longer works, the `libstdbuf.so.exe` file is in
coreutils 8.26-1.
Let's just rename the `libstdbuf.so.exe` file after it has been
installed into the `pkgdir` tree.
Note: we still have to muck around with `Makefile.in` so that the build
does not break with
make[2]: *** No rule to make target 'src/libstdbuf.so', needed
by 'all-am'.  Stop.
> coreutils: fix libstdbuf.so.exe problem once and for all

- mintty/PKGBUILD
Recent version of mintty has localized messages, but they were not installed.
Install them.
> mintty: Install language files

- vim/PKGBUILD
I've done a very basic smoke test opening `vim` and ensuring that there's no issues loading up my rather large [`vimrc`](https://github.com/erichdongubler-dotfiles/vim/blob/0b53811fe036dedce79be64f74ce466ba31f620d/.config/vim/vimrc). If you'd prefer the community did some more testing, I'm more than happy to help make that happen. :)
The main feature of this update is the addition of the `CmdlineLeave` and `CmdlineEnter` `autocmd` triggers.
> Update `vim` to v8.0.1213

- xorriso/PKGBUILD
The xorriso package is useful for those following the OS development guides at http://wiki.osdev.org on Windows.  It is used to create bootable ISOs.
This is my first pull request for MSYS2.  I'm not sure if I used the 'validpgpkeys' property properly.
> Added xorriso package

- ctags/PKGBUILD
- gengetopt/PKGBUILD
- idutils/PKGBUILD
- perl-Compress-Bzip2/PKGBUILD
- task/PKGBUILD
- txt2tags/PKGBUILD
I'm relatively new to contributing, please let me know if there's a better way to go about this.
Exhaustively comparing the (presumably correct) file sizes from [the repo listings](http://repo.msys2.org/msys/) to the descriptions in both msys.db files shows ten total packages with bogus file sizes listed in msys.db. This is the root cause of #942 and friends. A simple rebuild fixed this for ucl; this PR is intended to fix the remainder.
Packages with incorrect sizes in db | [i686](http://repo.msys2.org/msys/x86_64/msys.db) | [x86_64](http://repo.msys2.org/msys/x86_64/msys.db)
-- | -- | --
ctags, gengetopt, perl-Compress-Bzip2, txt2tags | X | X
idutils, task | | X
This also agrees with @lockywolf's list in #1025.
> Rebuild all packages that have an incorrect file size in the sync databases

- msys2-runtime/PKGBUILD
The package group `MSYS2-devel` (containing only msys2-runtime-devel) was created in bcdbf402. The next day, the group `msys2-devel` was created in 1994b55. I don't know if the difference in case was on purpose, or what the consequences of changing it might be. @Alexpux, please advise?
> 'MSYS2-devel' group: possible typo?

- ruby/PKGBUILD
Note that I am now working on ruby 2.5.0.
> Ruby 2.4.0, - rebuild to remove dependency on gcc's libssp library.

- filesystem/05-home-dir.post
- filesystem/PKGBUILD
- filesystem/msys2_shell.cmd
Instead of always changing directory to `$HOME` during shell startup, only do it when started from msys2_shell.cmd as to not break the behavior of `tmux -c` (issue #1107).
> Fix issue #1107

- gnupg/PKGBUILD
- gnupg/gnupg.install
It seems this is obsolete and only makes things more difficult for Git-for-Windows and people with their own private pacman repositories. What do you think, @Alexpux?
> gnupg: Don't nuke pacman's keyring in post-install

- readline/PKGBUILD
- readline/readline-7.0.3-3.clipboard.patch
In readline 7.0 some __CYGWIN__ ifdefs wrapping the paste-from-clipboard command were changed to _WIN32, which isn't defined. I'm not sure why, but this commit adds them back. It fixes #947 which was caused when that command disappeared.
> Fix missing paste-from-clipboard command, fixes #947

- filesystem/msys2_shell.cmd
Allow setting the login shell via command line parameter.  e.g, ```msys2_shell -shell fish -mintty```. 
The default remains bash.
For those that use this script there seems to be no obvious way to change the default login shell besides editing the file.  See https://superuser.com/questions/961699/change-default-shell-on-msys2
The file however gets overwritten when the package is upgraded and modifications lost.
> filesystem: Add -shell parameter to msys2_shell.cmd

- filesystem/profile
Noticed this when using `dash` as my shell.
https://wiki.ubuntu.com/DashAsBinSh#source
> remove minor bashism from /etc/profile

- msys2-runtime/0024-Cygwin-fix-build-with-GCC-7.patch
- msys2-runtime/PKGBUILD
This cherry-picks commit 67609efeb0bcb198463a952a6a214813794a9c2b from cygwin upstream, see https://www.mail-archive.com/cygwin-patches@cygwin.com/msg06820.html
> msys2-runtime: Cherry-pick gcc 7 suport from cygwin

- bash-completion/PKGBUILD
This updates bash-completion to 2.8.
> bash-completion: update to 2.8

- filesystem/05-home-dir.post
Enables users to take action (e.g. in `~/.bash_profile`) if msys was invoked with `CHERE_INVOKING` set.
`CHERE_INVOKING` is unset in the [original code](https://github.com/Alexpux/MSYS2-packages/blob/04890265df2539ff0399bb05d97ffc67d94027ac/filesystem/05-home-dir.post#L256). To make it visible to users it is [copied into a new variable](https://github.com/henrik-jensen/MSYS2-packages/blob/714549756f6eff42b5b950ce40fcfc1a5515a225/filesystem/05-home-dir.post#L256), `CHERE_INVOKING_VISIBLE_FOR_USER`, before unsetting in the PR. If the user choose to use this new variable it is their responsibility to unset this variable. ( Please propose a better naming if you have one )
Example usage ( Start in same directory as at last logout ):
Add to `~/.bash_profile`:
```bash
if [ ! -z …
```
> Make CHERE_INVOKING visible for users.

- diffutils/PKGBUILD
make check resulted:
```
===================================================================
Testsuite summary for GNU diffutils 3.6
===================================================================
```
The failing one is the `no-dereference`, but I believe that's expected, as it is using symlinks.
> diffutils: Update to 3.6

- grep/PKGBUILD
```
Testsuite summary for GNU grep 3.1
```
> grep: Update to 3.1

- openbsd-netcat/PKGBUILD
- openbsd-netcat/openbsd-netcat.patch
`pkgrel `is deliberately 2 due to the debian patchset.
> openbsd-netcat: Update to 1.190

- ci-build.sh
- ci-library.sh
- curl/PKGBUILD
A little script that shows dll dependencies in the CI script. This way we can manually inspect if there are any unlisted msys2 dependencies.
I modified the `curl` `PKGBUILD` only for testing this script :) We don't have to merge that part.
> Automatically check for (unintended) dll dependencies

- iperf3/PKGBUILD
Add new package iperf3 version 3.3:
TCP, UDP, and SCTP network bandwidth measurement tool
iperf3 is incompatible with iperf and offers additional benchmark tests like SCTP testing, it also lacks iperf multithread functionality, so it would be beneficial to have them both.
> Add new package iperf3 version 3.3

- getopt/PKGBUILD
getopt and util-linux are in conflict and they are both in base group so getopt should be excluded
> Remove getopt from base group

- cloog/PKGBUILD
- cloog/cloog-019.1-dont-build-doc.patch
```
Testsuite summary for cloog 0.19.0
```
> cloog: Update to 0.19.0

- perl-Mozilla-CA/PKGBUILD
- perl-Test-Fatal/PKGBUILD
- perl-Test-Needs/PKGBUILD
- perl-Test-Pod/PKGBUILD
- perl-Test-Requiresinternet/PKGBUILD
- perl-URI/PKGBUILD
- perl-XML-SAX/PKGBUILD
- perl-XML-SAX/perl-xml-sax.patch
- perl-XML-Simple/PKGBUILD
- perl-YAML-Tiny/PKGBUILD
- perl-libwww/PKGBUILD
perl-XML-SAX: Update to 1.00
perl-YAML-Tiny: Update to 1.73
perl-Mozilla-CA: Update to 20180117
New package: perl-Test-Fatal (version: 0.014)
New package: perl-Test-Requiresinternet (version: 0.05)
perl-libwww: Update to 6.33
perl-XML-Simple: Update to 2.25
perl-Test-Pod: Update to 1.52
New package: perl-Test-Needs (version: 0.002005)
perl-URI: Update to 1.74
> Perl: Multiple updates

- ci-library.sh
This makes sure that the test does not fail if there are no dll or exe files at all. Also fixes highlighting :)
> Do not fail for no executables

- filesystem/PKGBUILD
- filesystem/bash.bashrc
If msys2 bash is set as the DefaultShell for the Win10 OpenSSH server,
there is no way to pass -l to make it a login shell, so /etc/profile is
not sourced, PATH is not set, and the bashrc produces errors.
Detect this case in /etc/bash.bashrc, by checking for the SSH_CONNECTION
environment variable and PATH not having msys2 elements, and source
/etc/profile.
> better support for Win10 OpenSSH server

- ci-library.sh
CI build fails if package has no `.exe`or `.dll` files. Previous fix still fails because function still returns non-zero status from `[[ -n $exes ]]` test. This fixes this and prints "None" instead. Also handles arbitrary filenames.
> ci-library.sh: No exeutables failure fix

- texinfo/0006-Fix-unescaped-left-braces-in-regexps-deprecated-sinc.patch
- texinfo/PKGBUILD
Patch obtained from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898994
> Silence texinfo deprecation warnings with recent Perl

- isl/PKGBUILD
Interestingly the file name stayed "msys-isl-19.dll"
```
Testsuite summary for isl 0.20
```
> isl: Update to 0.20

- pacman/0010-filelist-strcasecmp.patch
- pacman/PKGBUILD
In case a package gets upgraded and a filename has changed case this allows
the upgrade to go through without any conflicts.
Similarly in case two different packages contain the same file with
a different case this makes it correctly detect a conflict.
This only handles ASCII parts of paths, so Unicode filenames still can
lead to invalid conflict detection.
Fixes #1426
> pacman: make file list comparisons between packages case insensitive

- ccache/PKGBUILD
- ccache/ccache-3.4.2-msys.patch
```
PASSED: 511 assertions, 102 tests, 10 suites
Running test suite base........................................................
Running test suite nocpp2........................................................
Running test suite cpp1.
Skipped test suite multi_arch [multiple -arch options not supported on MSYS_NT-10.0]
Skipped test suite serialize_diagnostics [--serialize-diagnostics not supported by compiler]
Skipped test suite sanitize_blacklist [-fsanitize-blacklist not supported by compiler]
Running test suite debug_prefix_map..
Skipped test suite masquerading [symlinks not supported on MSYS_NT-10.0]
Running test suite hardlink.
Running test suite direct........................................
Running test suite basedir.....
Running test suite compression.
Running test suite …
```
> ccache: Update to 3.5

- flex/PKGBUILD
The test names sed tries to eliminate have changed
over the years (prefix 'test-' dropped, hyphen replaced
by underscore). Moreover, the eliminated tests do pass
since the most recent flex/bison versions.
My first PR here. So pretty simple.
> flex: remove redundant change in 'check'

- filesystem/main-config.site
- filesystem/mingw32-config.site
- filesystem/mingw64-config.site
The variable 'as_echo' is not set in a virgin shell, but by 'autoconf'
and friends. Setting the default value to 'echo' facilitates running
'configure' in a virgin shell.
* filesystem/main-config.site: see above.
* filesystem/mingw32-config.site: see above.
* filesystem/mingw64-config.site: see above.
Fixes #1518
> main-config.site: set default value of var 'as_echo' to 'echo'

- pacman/0011-bash-completion-fix-regex.patch
- pacman/PKGBUILD
The bash_completion script uses \w and \s character classes in its regex, but these do not seem to be implemented in msys2-runtime (for the =~ operator, bash uses the POSIX regcomp/regexec functions which are implemented there). This makes it impossible to auto-complete package names, and probably other things.
This patch replaces them which [[:alnum:]_] and [[:space:]] classes that are implemented and match the same characters.
Not sure if this should be reported upstream since glibc does implement these classes, so the bug does not happen in Arch Linux.
> pacman: fix bash_completion script

- git-flow/PKGBUILD
A new version has been released 2 days ago.
> git-flow: upgrade to v1.12.0

- openssl/0005-Make-OPENSSL_malloc_init-a-no-op.patch
- openssl/PKGBUILD
One affected package is libserf (msys-serf-1-0.dll). This can be seen
when using certain operations of git svn.
> openssl: Patch to avoid potential infinite loops

- serf/PKGBUILD
This is the follow up patch to https://github.com/Alexpux/MSYS2-packages/pull/1576 which will fix various svn related hangs (infinite loops).
> serf: Rebuild with openssl to fix infinite loop issue

- gcc/0016-disable-weak-refs-in-libstdc++.patch
- gcc/PKGBUILD
This patch was in the 7 series of gccs for mingw, and it helps on msys
too.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
> add libstdc++ weakrefs patch for msys gcc

- man-db/PKGBUILD
Fixes #1633 
Pls note: 4 checks are failing just as with the previous version
```
Testsuite summary for man-db 2.8.5
```
> man-db: fixing systemd timer files location

- quilt/PKGBUILD
quilt copies awk into `/usr/share/quilt/compat` at build time, but this hasn't been built against readline 8.
> quilt: rebuild against readline 8

- guile/PKGBUILD
guile requires a rebuild since readline was updated from v7 to v8
which caused libreadline has a different file name
> Rebuild of guile due to readline v7 -> v8 upgrade

- gdb/PKGBUILD
- gdb/gdb-7.11.1-msysize.patch
`gdb_osabi` in `defs.h` and array of `osabi` strings in `osabi.c` must be synchronized otherwise gdb fails with internal error on start as it detects that the array and enumeration have diverged.
With this change `gdb` starts. There are multiple test failures, but without these changes tests couldn't pass for sure.
> Add missing part of msysize patch for gdb

- git-extras/PKGBUILD
Indicate that this succedes git-extras-git.  - Use release version
> git-extras - Update to 4.7.0 - Updated git-extras-git

- curl/PKGBUILD
- curl/curl-7.65.0-revert-progress-curl_disable_progress_meter.patch
This fixes #1658.
In addition, libunistring is added to depends to fix a configure check.
> curl: fix slow operation error

- git-crypt/PKGBUILD
A git plugin for transparent file encryption; works well in msys environment.
> Add git-crypt package, version 0.6.0

- README.md
Latest Drone CI supports Windows build natively, it's still not clear that if it is useful for MSYS2, I suggest to keep `.drone.yml`, `ci-build.sh` and `ci-library.sh` unchanged and revisit later.
> Remove retired Tea CI status.

- vim/PKGBUILD
This addresses CVE-2019-12735, and also brings us plenty of other goodies.
> vim: upgrade to latest version

- azure-pipelines.yml
I was wondering why the artifacts were not published properly in https://dev.azure.com/msys2/mingw/_build/results?buildId=2600... turns out that the script verifies that the current account is `Alexpux` (when it really is `msys2`).
I can't say that I understand how that CI script works at all, though: it fetches `master` from https://github.com/msys2/MSYS2-packages and compares the commits between the fetched revision and the current revision. I have no idea why they are different, though, but it seems to work. @Alexpux do _you_ know why it works?
In any case, this should fix the problem where the build artifacts are not published in the CI build.
> Let the Azure Pipeline know that we moved from Alexpux to msys2

- libarchive/PKGBUILD
- pacman/PKGBUILD
The issue is described in https://github.com/msys2/MSYS2-packages/issues/1674.
Libarchive uses Windows 7 API `BCryptDeriveKeyPBKDF2` to encrypt zip files. By disabling this, pacman works again on Windows Vista and Windows 2008.
> Fix pacman to work on Vista, fixes #1674, fixes #1181

- msys2-runtime/0026-mkdir-always-check-for-existence.patch
- msys2-runtime/PKGBUILD
Temporary patch until cygwin 3.8.x is integrated.
> msys2-runtime: 0026-mkdir-always-check-for-existence.patch

- cmake/PKGBUILD
1. Remove some files that were created by a patch so you don't have to clean the source dir.
2. Make a package for vim and emacs support
3. clarified dependencies by adding several pacakges to makedepends that cmake build mentions.
> Various fixes

- pacman/0101-contrib-pactree-gpgdir.patch
- pacman/PKGBUILD
This is a quick fix for #1720, it hard-codes `pactree` to have a gpg key directory. Meanwhile I'm working on a more involved patch for upstream.
> pacman: Update pacman-contrib to 1.1.0, fix `pactree -s`

- libtool/0013-Allow-statically-linking-compiler-support-libraries-.patch
- libtool/PKGBUILD
The previous patch for the same issue (in
066ff9b4ae0bb8deb6fc158737a117f9541eeff8) works fine for VLC, which
manually overrides "lt_cv_deplibs_check_method=pass_all" in their
configure.ac to get rid of this check in libtool in general.
To fix linking other projects without such existing workarounds
in their configure scripts, we need to patch libtool to allow
statically linking the compiler-rt builtins.
This patch is under discussion upstream at
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27866#65 (but doesn't
seem to be making any progress at the moment).
> Add another libtool patch for picking up compiler-rt builtins from clang

- man2html/PKGBUILD
A Unix manpage-to-HTML converter
> man2html - 3.0.1 - new package

- ninja/PKGBUILD
1. nemacs and vim support in optional packages
2. architecure sfiex
3. bash and vzsh  completions
4. removed referenc e to mingw-w64 in package description for msys package.
> ninja - 1.9.0 - following additions:

- azure-pipelines.yml
- brotli/PKGBUILD
Nothing depends on it and there is python-brotli for Python 3.
@OTLabs any objections?
> brotli: drop python2-brotli

- pacman/PKGBUILD
- pacman/pacman.conf
This fixes database and package downloads, when using recent versions of curl.
Fixes #1774.
> Fix curl command for pacman

- rlwrap/PKGBUILD
- rlwrap/rlwrap.install
This is a very useful little utility that gives you readline editing for
any program with a prompt, and it works perfectly for native windows
programs as well (e.g. rlwrap powershell works fine.)
Can be a nice alternative to winpty for some things.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
> new package: rlwrap-0.43

- dosfstools/PKGBUILD
This change delivers *dosfstools* commands to MSYS2, including `mkfs.fat`, `fsck.fat`, `fatlabel` and compatible aliases (such as `mkfs.vfat`, via `--enable-compat-symlinks`).
````
$ mkfs.fat --help
mkfs.fat 4.1 (2017-01-24)
Usage: mkfs.fat [-a][-A][-c][-C][-v][-I][-l bad-block-file][-b backup-boot-sector]
[-m boot-msg-file][-n volume-name][-i volume-id]
[-s sectors-per-cluster][-S logical-sector-size][-f number-of-FATs]
[-h hidden-sectors][-F fat-size][-r root-dir-entries][-R reserved-sectors]
[-M FAT-media-byte][-D drive_number]
[--invariant]
[--help]
/dev/name [blocks]
$ pacman -Ql dosfstools
dosfstools /usr/
dosfstools /usr/bin/
dosfstools /usr/bin/dosfsck.exe
dosfstools /usr/bin/dosfslabel.exe
dosfstools /usr/bin/fatlabel.exe
dosfstools /usr/bin/fsck.fat.exe
dosfstools …
```
> dosfstools: new package

- .gitattributes
- filesystem/msys2_shell.cmd
Consider this inline invocation in a Windows Command Prompt:
```
C:\msys2\msys2_shell.cmd -defterm -no-start -mingw64 -here -c $@ -- echo hello there, --world=windows
```
This currently produces:
>hello there, --world windows
Note the absence of the `=` character. This is due to the word-splitting done by `cmd.exe` to form the positional parameters (`%1` - `%9`). The same word-splitting is not done on the `%*` special variable, so use that to derive the remaining command line arguments.
With this fix, the above command produces:
>hello there, --world=windows
My use case for this fix is to [pass `--gtest_color=yes` to a Google Test program in Travis CI](https://travis-ci.org/tanzislam/cryptopals/jobs/619370388#L3830).
> msys2_shell.cmd: Avoid argument splitting by cmd.exe

- u-boot-tools/PKGBUILD
This adds a new package for MSYS2: u-boot-tools.
It includes various host tools from U-Boot, the universal bootloader.
The following tools are included:
- dumpimage.exe
- fdtgrep.exe
- fit_info.exe
- fit_check_sign.exe
- mkimage.exe
> Add u-boot-tools package v2020.01

- pacman/0000-pacman-msysize.patch
- pacman/PKGBUILD
- pacman/makepkg.conf
- pacman/makepkg_clang32.conf
- pacman/makepkg_clang64.conf
- pacman/makepkg_mingw32.conf
- pacman/makepkg_mingw64.conf
- pacman/pacman.conf
* Add a dependency on zstd so that makepkg can use it
* Remove the upx option from the config because it was removed
in pacman: https://git.archlinux.org/pacman.git/commit/?id=1a29744d0d
* Various other syncs and adjustments for zstd
This should make it possible for us to switch from xz to zstd, if we want.
Arch switched already: https://www.archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/
> pacman/makepkg: sync config files with upstream and support zstd

- u-boot-tools/PKGBUILD
Add $ before {pkgver} that was missing in previous commit.
> u-boot-tools: Add the missing $ before {pkgver}

- filesystem/msys2_shell.cmd
Commit 11ba641bed28 intended to preserve [`cmd.exe` delimiter characters](https://ss64.com/nt/syntax-esc.html#delimiters) in the command line passed on to `bash`, but broke the handling of `-where` directories with spaces in them. Fix this by:
- Incrementing `shiftCounter` with any quoted arguments treated as separate words (after unquoting), because the `FOR /F ... IN`-loop at the end cannot treat them (in the full command) as single parameters.
- Using the full list of `cmd.exe` delimiters in the `FOR /F ... IN`-loop when skipping the initial tokens.
Tested this with:
```
C:\msys2\msys2_shell.cmd -defterm -no-start -mingw64 -where <DIR> -shell bash -c $@ -- echo hello there, --world=windows
```
where `<DIR>` is the following:
- `C:\Users`
- `C:\Progra~1`
- `"C:\Program Files"`
- …
> Fix msys2_shell.cmd argument-handling with spaces

- filesystem/msys2_shell.cmd
- filesystem/profile
When set shell arguments, LOGINSHELL has double quotes.
In the default, L6: set "LOGINSHELL=bash". 
I followed the format it.
The task I encountered are shown below.
> Remove double quotes of the LOGINSHELL

- filesystem/profile
Issue:
1. Run, C:\msys64\msys2_shell.cmd -mingw64 -shell zsh
2. echo $SHELL
3. Nothing
Image is here:
> Add value to $SHELL for zsh

- python2-setuptools/PKGBUILD
Also remove all dependencies, setuptools bundles all dependencies
by itself anyway.
python3-setuptools -> python-setuptools
> setuptools: split package into Python 2 and Python 3 versions

- libarchive/PKGBUILD
libarchive is currently not built with lzo2
> Remove lzo2 from libarchive dependencies

- texinfo/PKGBUILD
Merging this PR resolves the following issues:
- building failure texinfo package
texinfo v6.6 is on https://packages.msys2.org/outofdate page. 
So, i bumped up pkgrel and updated PKGBUILD file.
In this modification, PKGBUILD has a PKG key.
Therefore, when you build in the local, please execute the following command.
```
gpg --recv-keys EAF669B31E31E1DECBD11513DDBC579DAB37FBA9
```
> Fix building failure texinfo 

- luit/PKGBUILD
- luit/luit-20190106-fix-ldflags.patch
luit is a tool which can convert outputs of applications from other encoding to UTF-8. It's useful when using some non-Unicode programs without changing the encoding of mintty such as Windows built-in commands.
> luit: Add version 20190106

- zsh/PKGBUILD
- zsh/zshenv
Merging this PR resolves the following issues:
- #1285
- #1624
By setting PROMPT in /etc/zsh/zshenv, added no unintended PROMPT viewing
when running interactive zsh from bash.
Set PROMPT in /etc/zsh/zshenv to prevent unintentional format on PROMPT display 
when running an interactive zsh from bash. See also https://github.com/msys2/MSYS2-packages/pull/1897#issuecomment-602273511
This PR doesn't conflict the `grml-zsh-config` package. 
Because the package doesn't provide /etc/zsh/zshenv.
- #1897
- #1899
> Set PROMPT in /etc/zsh/zshenv

- dtc/PKGBUILD
With a fresh installation of MSYS2, running dtc I got:
$ dtc
C:/msys64/usr/bin/dtc.exe: error while loading shared libraries:
msys-yaml-0-2.dll: cannot open shared object file: No such file or directory
Add libyaml to the dependency to fix it.
> dtc: Add libyaml to the dependency

- itstool/PKGBUILD
- libxml2/PKGBUILD
- libxslt/PKGBUILD
- rarian/PKGBUILD
- yelp-tools/PKGBUILD
- yelp-xsl/PKGBUILD
* Move libxml2 and itstool to Python 3
* Drop the python 2 bindings from libxslt, looks like nothing really needs them
> Python 3 porting:  libxml2, itstool, libxslt

- procps-ng/PKGBUILD
Merging this PR resolves the following issues:
- procps-ng v3.3.15 is outofdate (See https://packages.msys2.org/outofdate)
Ref #1914
> procps-ng: Update to 3.3.16

- msys2-runtime/0018-fixup-Do-not-create-cygwin-symlinks.-Instead-use-dee.patch
- msys2-runtime/0019-strace-quiet-be-really-quiet.patch
- msys2-runtime/0020-Work-around-backward-incompatible-bfd_-changes.patch
- msys2-runtime/0021-setup_pseudoconsole-handle-missing-incorrect-helper-.patch
- msys2-runtime/0022-Default-to-disable_pcon.patch
- msys2-runtime/0023-Introduce-the-enable_pcon-value-for-MSYS.patch
- msys2-runtime/PKGBUILD
To make it easier to experiment with it, we now also support `MSYS=enable_pcon` (in addition to the equivalent but unintuitive `MSYS=nodisable_pcon`).
This is a companion PR to https://github.com/msys2/Cygwin/pull/6
> msys2-runtime: demote the "pseudo console" support to opt-in

- pacman/0000-pacman-msysize.patch
- pacman/PKGBUILD
After a core upgrade instead of waiting endlessly and hoping that
the user closes all remaining msys processes ask the user if we should
kill them and then just do it.
This iterates over /proc/*/winpid and passes the list to taskkill
which kills all processes, except pacman itself which exits manually.
In case of --noconfirm things get killed automatically.
> WIP: pacman: kill all msys processes after a core upgrade

- base/PKGBUILD
- base/README.md
This is meant as a replacement for the base group and contains the
same packages. If a user has the base package installed (the installer
will do this in the future) then we can add new packages to the base
and users with existing installations will get those packages installed
automatically.
This follows what Arch did last year:
https://www.archlinux.org/news/base-group-replaced-by-mandatory-base-package-manual-intervention-required/
See #1976
> Add a base package

- zstd/PKGBUILD
This is related to https://github.com/msys2/MSYS2-packages/pull/1969 .
> zstd: Use tar.xz to install the zstd package from old MSYS2

- pacman/0000-pacman-msysize.patch
- pacman/0011-update-ja-po-for-msys2.patch
- pacman/PKGBUILD
Some new messages were added by #1971. Update the Japanese translation
for them.
Additionally, one of the new messages was not translatable. Make it
translatable.
Related: #1786
> pacman: Update ja translation

- pacman/0000-pacman-msysize.patch
- pacman/PKGBUILD
This addresses #1991 as I understand it. [The documentation](https://linux.die.net/man/3/execvp) is not very clear on this, but `execvp()`'s argv appears to start at 0, not 1, so "/F" was not being passed at all. Now it kills all the consoles without asking again. :)
> pacman: Fix core update killall behavior

- file/PKGBUILD
It got copied to the root dir instead of the Python site-packages
> file: fix install path of magic.py

- filesystem/PKGBUILD
- filesystem/msystem
Behavior about the value of HOSTTYPE and MACHTYPE is not compatible between various POSIX compliant shells. For example zsh doesn't set HOSTTYPE at all and set MACHTYPE to that of HOSTTYPE in bash. I checked source tree of bash and found that HOSTTYPE is set to the result of `uname -m` and that MACHTYPE is set to the result of `uname -m` plus "-pc-msys".So change code  accordingly.
This fixes issue #2008.
> filesystem: Make msystem compatible with POSIX compliant shells.

- openssl/PKGBUILD
This contains the htmls docs/manpages and the level 3 man pages (API docs).
openssl is part of base and all these docs make up 7800 files, which is a third
of all files in base.
Since they are rarely needed and contain so many files I think it makes sense to split them out.
> openssl: Add a separate openssl-docs package

- filesystem/PKGBUILD
msys2-base was removed from dash and filesystem, but filesystem gets updated
first and then fails beause it would break dash which hasn't been updated yet.
So add the provides back.
This fixes:
error: failed to prepare transaction (could not satisfy dependencies)
:: installing filesystem (2020.02-3) breaks dependency 'msys2-base' required by dash
> filesystem: fix upgrade

- binutils/PKGBUILD
Done in MinGW, but not in MSYS
> binutils: Install libiberty headers

- python/930-fix-missing-tcp-include.patch
- python/PKGBUILD
Upstream bug: https://bugs.python.org/issue41374
Fixes #2050
> python: Fix socket.TCP_NODELAY missing

- dash/PKGBUILD
The included install script depends on /etc/shells
Fixes #2049
> dash: depend on filesystem

- db/PKGBUILD
Patch from Fedora project.
Fixed compile error:
error: definition of 'int __atomic_compare_exchange(db_atomic_t*, atomic_value_t, atomic_value_t)' ambiguates built-in declaration 'bool __atomic_compare_exchange(unsigned int, volatile void*, void*, void*, int, int)'
> db: fix gcc __atomic_compare_exchange ambiguation.

- python/PKGBUILD
The 'crypt' module was no longer being built, which was a regression.
> python: add libcrypt-devel to makedepends

- perl-Alien-Build/PKGBUILD
- perl-Compress-Bzip2/PKGBUILD
- perl-Crypt-SSLeay/PKGBUILD
- perl-DBI/PKGBUILD
- perl-HTML-Parser/PKGBUILD
- perl-List-MoreUtils-XS/PKGBUILD
- perl-Locale-Gettext/PKGBUILD
- perl-Math-Int64/PKGBUILD
- perl-Net-SSLeay/PKGBUILD
- perl-Socket6/PKGBUILD
- perl-Sys-CPU/PKGBUILD
- perl-XML-LibXML/PKGBUILD
- perl-YAML-Syck/PKGBUILD
This seems to more properly be a dependency of things that compile against perl, so maybe if a perl-devel package existed it would be a dependency of that.
Replacement for PR #2078
> Fix perl modules makedepends

- gdb/PKGBUILD
Otherwise configure fails trying to include Python.h
> gdb: add libcrypt-devel to makedepends

- reflex/PKGBUILD
* reflex/PKGBUILD:
- update version to 20200715
- change to github releases whose unzipped packages have a different
folder name.
- add variables _src_dir and _build_dir for better maintenance.
> reflex: Update to 20200715

- python/PKGBUILD
See https://github.com/msys2/MSYS2-packages/pull/2082#issuecomment-667709021
Tees stdout from make to a file (in a way that doesn't suppress an error
exit from make from failing the build), and runs a sed script over that
file which looks for a list of failed modules, outputs it to ensure it
isn't lost in the build output, and exits with an error code to cause
the build to fail.
I don't know if github allows others to view this, but I did a test run with the libcrypt-devel makedepends removed from python's PKGBUILD to demonstrate how/that this works:
https://github.com/jeremyd2019/MSYS2-packages/runs/947110802?check_suite_focus=true#step:4:1458
> python: fail build if any modules fail to build.

- git-extras/PKGBUILD
6.0.0 is the latest release. It was released on June 21, 2020
> Update to version 6.0.0 of git-extras

- openssl/PKGBUILD
As suggested in https://github.com/msys2/MINGW-packages/issues/6658
The directory name is different, so there is no conflict moving it.
> openssl: move LICENSE file to libopenssl

- ci-build.sh
With auto-key-retrieve enabled, gpg called by makepkg will fetch keys
from validpgpkeys in the PKGBUILD and verify the result.
Uses the ubuntu keyserver because that one isn't as flaky.
This requires that all our packages get an up-to-date validpgpkeys
array. But we no longer have to trust the users to have checked the
signature before creating a PR.
> CI: verify signatures of source files

- filesystem/PKGBUILD
- filesystem/profile
Fixes #2089.
In the event that `%SHELL%` is set in the Windows environment, the shell which msys2_shell.cmd starts (bash by default) and the value of `$SHELL` may differ. Thus when we detect bash in `filesystem/profile`, set `$SHELL` to bash, just to be sure.
> filesystem: Override %SHELL% for bash

- msys2-runtime/0027-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/0028-Expose-full-command-lines-to-other-Win32-processes-b.patch
- msys2-runtime/PKGBUILD
This is the companion to https://github.com/msys2/Cygwin/pull/10 to _actually_ get these patches into MSYS2.
> msys2-runtime: fix `MSYS=wincmdln` and turn it on by default

- ci-build.sh
- ci-dont-install-list.txt
Namely, msys2-runtime and bash.  Currently, msys2-runtime always fails CI.
> CI: don't attempt to install known-troublesome packages.

- python/960-fix-parallel-make.patch
- python/PKGBUILD
It mostly worked out of the box, except for some ln failures in make install due to not
being able to create a broken symlink to a file to be created later.
Fixed by making the make rule that ln's depend on the rule that creates
the files.
> python: enable makeflags option

- python/PKGBUILD
This doesn't contain anything and just depends on python itself and
libcrypt-devel which it uses in Python.h.
This allows packages building against Python to makedepend on this without
having to specify libcrypt-devel etc.
> Add a python-devel package

- gamin/PKGBUILD
Nothing depends on it and it's using Python 2 which want to get rid of.
> gamin: Drop gamin-python

- automake1.10/PKGBUILD
- automake1.11/PKGBUILD
- automake1.12/PKGBUILD
- automake1.13/PKGBUILD
- automake1.14/PKGBUILD
- automake1.15/PKGBUILD
- automake1.16/PKGBUILD
- automake1.6/PKGBUILD
- automake1.7/PKGBUILD
- automake1.8/PKGBUILD
- automake1.9/PKGBUILD
This also removes the pgp checks for everything except 1.16 because
they don't contain the full key ID and can't be auto fetched by gnupg.
Since we have the checksums and they wont be updated in the future anyway
this shouldn't be a problem.
The tests didn't work anyway, so removing Python 2 doesn't change much.
> automake: Don't depend on Python 2

- pacman/PKGBUILD
- pacman/makepkg_mingw32.conf
- pacman/makepkg_mingw64.conf
This enables ASLR, DEP by default.
The goal here is to give these a try for our own package builds and
if there are problems disable some flags again in the respective PKGBUILDs.
Once most of our packages work fine we can think about enabling it
in binutils directly for all users.
Related ASLR change for binutils: https://github.com/msys2/MINGW-packages/pull/6880
Related discussion: https://github.com/msys2/MINGW-packages/issues/6674
> makepkg-mingw: Enable hardening linker flags by default

- po4a/PKGBUILD
Changes:
* Choose a concise package description.
* Add 'perl-YAML-Tiny' as dependency and 'perl-Pod-Parser' as make dependency.
* Source tarball file name has changed. So, remove 'v' from source directory.
> po4a: update to 0.61

- pacman/PKGBUILD
- pacman/makepkg_mingw32.conf
As mentioned in https://github.com/msys2/MINGW-packages/issues/6674#issuecomment-683138852 a different exception mechanism is used by gcc on 32-bit Windows, and this is already the default in lld.
> pacman: add --no-seh to ming32 LDFLAGS.

- sqlite/PKGBUILD
also no reason it should be in base-devel
> sqlite: don't replace lemon with itself

- python/PKGBUILD
We currently have an issue where python was replaced in the pacman repo, leading
to install errors with existing caches containing the old version (CI caches etc).
Bump pkgrel to fix things.
To prevent this in the future see https://github.com/msys2/msys2-autobuild/issues/16
> python: rebuild

- rebase/007-peflags-high-entropy-va.patch
- rebase/PKGBUILD
This has been my go-to tool to display or modify dll characteristics
flags, but it didn't know about the high-entropy-va flag.  Now it does.
> rebase: teach peflags about high-entropy-va flag.

- gnupg/PKGBUILD
- gnupg/gnupg.install
Per https://lists.gnupg.org/pipermail/gnupg-announce/2020q3/000448.html, gnupg-2.2.23 fixes "a *critical security bug* in
versions 2.2.21 and 2.2.22."
mingw-w64-gnupg is still 2.2.20, so unaffected.
Also removed info install/uninstall handling from install script.
> gnupg: update to 2.2.23 for CVE-2020-25125.

- po4a/PKGBUILD
`perl-Pod-Parser` is actually a runtime dependency.
Without it po4a fails with cryptic messages like the following (the module loading error is only printed in verbose mode):
```
$ po4a-updatepo -f pod -m inkscape.pod.in -m inkview.pod.in -p man.pot --verbose
Unknown format type: pod.
po4a::chooser: Module loading error: Can't locate Pod/Parser.pm in @INC (you may need to install the Pod::Parser
module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl
/usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl
/usr/share/perl5/core_perl) at /usr/share/perl5/site_perl/Locale/Po4a/Pod.pm line 14.
BEGIN failed--compilation aborted at /usr/share/perl5/site_perl/Locale/Po4a/Pod.pm line 14.
Compilation failed in require at (eval 37) line 1.
BEGIN …
```
> po4a: add missing runtime dependency (perl-Pod-Parser)

- mc/0003-vfs-win32-absolute-paths.patch
- mc/PKGBUILD
Running `mcedit C:/foo/bar` would result in a message like _Cannot open /usr/bin/C:/foo/bar_.  This patch fixes this use case.
> mc: Recognize Win32 absolute paths

- patchutils/PKGBUILD
NB: This commit adds an implicit run-time dependency to pcre2 for enhanced
pattern searches.
* patchutils/PKGBUILD:
- update to 0.4.2
- add dependency to pcre2/pcre2-devel (new feature since 0.4.0)
- run build in separate directory
- add function check (NB: patchutils 0.4.2: all checks succeed.)
- add license to package
> patchutils: Update to 0.4.2

- pacman/PKGBUILD
- pacman/makepkg_mingw64.conf
This will allow us to change the default to low in binutils, so that our
built packages get proper ASLR support, while users get the same behaviour as
with an older binutils with the old defaults.
See https://github.com/msys2/MINGW-packages/issues/7023#issuecomment-698246859
> makepkg: Add --default-image-base-high to LDFLAGS

- pacman-mirrors/PKGBUILD
- pacman-mirrors/mirrorlist.msys
Signed-off-by: Alex Chi <iskyzh@gmail.com>
https://github.com/msys2/MSYS2-packages/pull/2164 Introduced SJTUG mirror, but the msys2 URL is wrong. In this PR, I fixed the URL.
> pacman-mirrors: fix SJTUG msys mirror URL

- pacman-mirrors/PKGBUILD
- pacman-mirrors/mirrorlist.mingw32
- pacman-mirrors/mirrorlist.mingw64
- pacman-mirrors/mirrorlist.msys
We moved the primary to a smaller hosting and there's probably enough
mirrors now.
> pacman-mirrors: Remove repo.msys2.org

- filesystem/PKGBUILD
- filesystem/msys2_shell.cmd
Helps identifying window thumbnails when switching between MSYS and MINGW64 consoles
> filesystem: use matching icon for console

- pkg-config/PKGBUILD
- pkgconf/001-no-cygpath-conv.patch
- pkgconf/PKGBUILD
Maybe we can default to pkgconf in the future, like Arch.
> pkgconf/pkg-config: some cleanups/updates, make it possible to install pkgconf as an alternative

- gnutls/PKGBUILD
- less/PKGBUILD
- libpipeline/PKGBUILD
- libpsl/PKGBUILD
- mksh/PKGBUILD
- whois/PKGBUILD
Assorted fixes for packages that failed to build in https://github.com/msys2/msys2-autobuild/runs/1300765313?check_suite_focus=true
`less` is a pgp nightmare. It was missing validpgpkeys, and the .sig file was named without the .tar.gz extension, and even with both of those fixed it still failed to validate, I assume it failed to retrieve the key.  I commented out the sig file so it could build.
> fixes for packages that failed to build in msys2-autobuild

- emacs/PKGBUILD
- gnutls/PKGBUILD
- lftp/PKGBUILD
`pkg-config --exists --print-errors gnutls` fails if those .pc files are missing.
Rebuild lftp and emacs after this update, as they were failing due to this.  Also added libunistring-devel as a makedepends on emacs to fix its build.
> gnutls-devel: add depends on other -devel packages

- python/940-rebase-python-dll.patch
- python/950-rebase-dlls.patch
- python/PKGBUILD
It turns out that the calculated auto-image-bases for `msys-python3.8.dll` and `array.cpython-38-i386-msys.dll` overlapped on i686.  I patched in rebase calls after building the python dll and after building the module dlls, which allows the build to succeed on my local machine.  For some unknown reason, it still fails for me in GHA no matter what I tried ☹️ .
I've been keeping this in a branch and rebasing for a couple of python updates, but figured I'd offer it up as a pull request.
> python: rebase dlls during build (for i686)

- rcs/PKGBUILD
Configure looks for it, but the comment says it's only needed if diff3
isn't 'sane'.  Since our diff3 is GNU diff3, it is 'sane', so ed isn't
required at runtime, but configure still checks for it so make it a
makedepends.
> rcs: makedepends on ed

- pkg-config/PKGBUILD
- pkgconf/PKGBUILD
pkgconf is maintained, doesn't include glib and supports more pkg-config
features and builds faster.
Arch and Fedora have switched long ago, so we should too.
> Switch from pkg-config to pkgconf

- mingw-w64-cross-crt-git/PKGBUILD
- mingw-w64-cross-headers-git/PKGBUILD
- mingw-w64-cross-tools-git/PKGBUILD
- mingw-w64-cross-winpthreads-git/PKGBUILD
- mingw-w64-cross-winstorecompat-git/PKGBUILD
Otherwise "git am" used in prepare() wil change HEAD and as a result pkgver().
Also when "git am" is used the hash in the version isn't in the upstream repo
which makes it hard to figure out where it was built from.
Just hardcode to the commit that was checkedd out initially.
> mingw-w64-cross-*: hardcode the commit hash in the version

- libevent/0001-Fix-DNS-lookups-in-MSYS2.patch
- libevent/PKGBUILD
When I tried to verify that the `tmate` package at https://github.com/msys2/msys2-autobuild/releases/tag/staging-msys works correctly, it sadly failed to start, with a terse "lost server" message.
The reason why I did not see this breakage locally was that I still ran with libevent v2.1.11, which for some reason does not seem to have any problem looking up the name server IPs, even if the code in [`evdns.c`](https://github.com/libevent/libevent/blob/HEAD/evdns.c) does not seem to have changed all that dramatically.
Be that as it may, this here PR fixes `libevent` so that the name server IPs are obtained "the Win32 way". And with this, I can finally start `tmate` in an Azure Pipeline!
> libevent: fix DNS lookups in MSYS2

- curl/PKGBUILD
It changes the behaviour of curl, so better only use it when the debug flag is enabled.
Fixes #2223
> curl: don't build with --enable-debug by default

- nano-syntax-highlighting/PKGBUILD
provides/conflicts seem to be left over from -git package.
failure: nano-syntax-highlighting: circular reference nano-syntax-highlighting in provided packages
failure: nano-syntax-highlighting: circular reference nano-syntax-highlighting in conflicted packages
> nano-syntax-highlighting: don't conflict with self

- pacman-mirrors/PKGBUILD
- pacman-mirrors/mirrorlist.md
- pacman-mirrors/mirrorlist.mingw32
- pacman-mirrors/mirrorlist.mingw64
- pacman-mirrors/mirrorlist.msys
Changed sourceforge mirror URL so it has less redirections:
-   Old Sourceforge mirror: sourceforge.net
-   New Sourceforge mirror: downloads.sourceforge.net
Tested and it works fine for me.
> Changed Sourceforge mirror to be faster

- pacman-mirrors/PKGBUILD
- pacman-mirrors/mirrorlist.md
- pacman-mirrors/mirrorlist.mingw32
- pacman-mirrors/mirrorlist.mingw64
- pacman-mirrors/mirrorlist.msys
Now that we have expanded the number of mirrors, I am shutting down my mirror on DigitalOcean because I don't think it is needed any longer.
> Remove Gaphor DigitalOcean mirror

- clang/0002-Fix-GetHostTriple-for-mingw-w64-in-msys.patch
- clang/0004-llvm-config-look-for-unversioned-shared-lib-on-win32.patch
- clang/0006-add-coff-exported-flag.patch
- clang/0007-getLoadAddressWithOffset-assertion.patch
- clang/0009-empty-target-prefix-only-msvc.patch
- clang/0010-mbig-obj-for-all.patch
- clang/0011-Msysize.patch
- clang/0012-Add-minimal-msys-target.patch
- clang/0101-Allow-build-static-clang-library-for-mingw.patch
- clang/0102-fix-libclang-name-for-mingw.patch
- clang/0105-build-libclang-cpp-fix.patch
- clang/0106-cmake-Fix-build-of-attribute-plugin-example-on-Windo.patch
- clang/0107-Msysize.patch
- clang/0108-Add-minimal-msys-target.patch
- clang/0301-LLD-COFF-Error-out-if-creating-a-DLL-with-too-many-e.patch
- clang/0302-LLD-Allow-configuring-default-ld.lld-backend.patch
- clang/0303-LLD-Ignore-ELF-tests-when-ld.lld-defaults-to-MinGW.patch
- clang/0304-ignore-new-bfd-options.patch
- clang/0305-Msysize.patch
- clang/PKGBUILD
- mingw-w64-cross-clang-crt-git/PKGBUILD
- mingw-w64-cross-clang-headers-git/PKGBUILD
- mingw-w64-cross-clang/PKGBUILD
- mingw-w64-cross-compiler-rt/PKGBUILD
Surely some of the patches are unnecessary for MSYS2 package but I included them from MINGW package so the are more "in-line".
Clang's msys target doesn't support using GCC's libstdc++ but it's not necessary for bootstrapping.
Headers and CRT use `_variant=gcc` so they have to built locally and uploaded (their pkgname differs if `_variant=clang` is chosen).
> Add packages for bootstrapping Clang subsystem

- autoconf2.13/0001-autoconf-2.13-version-specific-share-directory.patch
- autoconf2.13/PKGBUILD
Not sure if this package is still needed.  
@lazka   This PR is a preparation step for keeping various autoconf version at the same time. We could later have packages `autoconf-2.69` and `autoconf` (=`autoconf-2.70.x`). Agree - or some other idea?  I am open for anything, but I think it would be helpful to keep `autoconf-2.69` in the play for some longer period of time to avoid massive complaints when packages are not prepared for `autoconf 2.70.x`.  If ok I can look to prepare the same for `autoconf 2.69`.
---
This commit aims at avoiding any interference with another autoconf release
package by keeping the library directory separate from other autoconf
release packages - WITHOUT breaking package functionality.
This approach might be consistently applied to other AUTOCONF versions
other …
> autoconf2.13: move share dir from 'autoconf' to 'autoconf-2.13'

- curl/0001-more-static-fixes.patch
- curl/PKGBUILD
- pacman/PKGBUILD
somehow the libcurl.pc was missing libraries in Libs.private, but rebuilding it locally helped.. let's try again in CI.
> curl: rebuild with libzstd; fix+rebuild pacman

- base/PKGBUILD
It's nice to have at least one CLI editor in the base install, to
edit config files, write commit messages etc.
Fixes #2244
> base: depend on nano

- mingw-w64-cross-compiler-rt/PKGBUILD
like CFLAGS et al, -target should be set for clang when used as an assembler.
This does not appear to be necessary for mingw-w64-cross-clang based on looking at `compile_commands.json`
> mingw-w64-cross-compiler-rt: set ASMFLAGS

- clang/PKGBUILD
Needed for cross-compiling clang.  `llvm-tblgen` was already installed, but `clang-tblgen` was not.
Also fixed pkgbase, and a reference to lldb where it meant lld.
With this, #2294, and some hacks not yet ready for light of day, was able to use [msys2/CLANG-packages' mingw-w64-clang PKGBUILD](https://github.com/msys2/CLANG-packages/tree/bootstrap/mingw-w64-clang) to cross-compile clang for aarch64-w64-mingw32.
I haven't tested it yet, my raspberry pi is still trying to build the same 'native' and probably won't finish any time soon 😉
> clang: package clang-tblgen.exe

- rpcsvc-proto/PKGBUILD
This probably fixes the build issue of new libvirt, https://github.com/msys2/MINGW-packages/issues/6384 /cc @Alexpux
> rpcsvc-proto: Add package for libvirt build

- zsh/PKGBUILD
- zsh/fix-zpty-module.patch
make zsh/zpty work with msys2, and can pass most mafredri/zsh-async#26 test.
```c
master = movefd(master);
if (master == -1) {
zerrnam(nam, "cannot duplicate fd %d: %e", master, errno);
scriptname = oscriptname;
ineval = oineval;
return 1;
}
```
Since cygwin uses two threads to process the pseudoterminal master device, zpty calls the `movefd` method to move the file description of the master device, and cygwin disposed the original `fhandler_pty_master` object, which causes the process thread to run incorrectly. here simply disable the zpty move the master device file descriptor untill cygwin upstream fix this issue.
-  zpty error strace
```
30 27794711 [main] zsh 1918 fhandler_pty_master::cleanup: /dev/ptmx closing master, usecount 0
43 27794754 [main] zsh 1918 …
```
> zsh: make zpty module work

- glib2/PKGBUILD
Since 'pkg-config glib-2.0 --libs' adds also '-lintl' the related
library should be also available
> glib2: for glib2-devel add dependency to gettext-devel

- perl-Algorithm-Diff/PKGBUILD
- perl-Alien-Build/PKGBUILD
- perl-Alien-Libxml2/PKGBUILD
- perl-ExtUtils-MakeMaker/PKGBUILD
- perl-HTTP-Cookies/PKGBUILD
- perl-HTTP-Message/PKGBUILD
- perl-IO-Socket-IP/PKGBUILD
- perl-IO-Socket-SSL/PKGBUILD
- perl-Importer/PKGBUILD
- perl-JSON/PKGBUILD
- perl-List-MoreUtils-XS/PKGBUILD
- perl-List-MoreUtils/PKGBUILD
- perl-Net-HTTP/PKGBUILD
- perl-Net-SSLeay/Net-SSLeay-1.55.patch
- perl-Net-SSLeay/PKGBUILD
- perl-Params-Util/PKGBUILD
- perl-Path-Tiny/PKGBUILD
- perl-Role-Tiny/PKGBUILD
- perl-Test-Fatal/PKGBUILD
- perl-Test-Simple/PKGBUILD
- perl-Test2-Suite/PKGBUILD
- perl-URI/PKGBUILD
- perl-XML-LibXML/PKGBUILD
- perl-YAML-Syck/PKGBUILD
- perl-libwww/PKGBUILD
perl-Algorithm-Diff: Update to 1.201
perl-ExtUtils-MakeMaker: Update to 7.58
perl-JSON: Update to 4.03
perl-IO-Socket-IP: Update to 0.41
perl-IO-Socket-SSL: Update to 2.069
perl-Net-SSLeay: Update to 1.90
perl-Path-Tiny: Update to 0.116
perl-Role-Tiny: Update to 2.002004
perl-Test-Fatal: Update to 0.016
perl-Importer: Update to 0.026
perl-XML-LibXML: Update to 2.0206
perl-List-MoreUtils: Update to 0.430
perl-Test-Simple: Update to 1.302183
perl-YAML-Syck: Update to 1.34
perl-Alien-Build: Update to 2.38
perl-Alien-Libxml2: Update to 0.17
perl-Params-Util: Update to 1.102
perl-Test2-Suite: Update to 0.000139
perl-HTTP-Message: Update to 6.27
perl-perl-HTTP-Cookies: Update to 6.10
perl-libwww: Update to 6.52
perl-Net-HTTP: Update to 6.20
perl-URI: Update to 5.07
> Perl updates

- filesystem/01-devices.post
- filesystem/PKGBUILD
Although the default and most used way to install MSYS2 is to have it
user-writable, some users prefer to have the root writable only to
admins.  In that case, the 01-devices.post script would always print out
two failures on "login" when trying to chmod /dev/{shm,mqueue}.  Since
the only supported configuration for MSYS2 is to mount `/` with noacl
where chmod() is a no-op, the failure is purely cosmetic, as is the
chmod invocation itself.  For these reasons, let's not chmod at all.
I'm aware the non-user-writable root configuration itself is not
officially supported either, but I've been using it like that for years
now and this is the only issue I know of, so I think it's reasonable to
resolve this.
> filesystem: Avoid trying to chmod /dev/{shm,mqueue}

- binutils/0100-binutils-2.36-msys2.patch
- binutils/PKGBUILD
Remove testsuite patches to reduce maintenance effort. 
I guess they are not needed since we didn't run the testsuite.
> binutils: update to 2.36.1

- fish/PKGBUILD
- fish/msys2.fish
- fish/msystem.fish
I noticed fish doesn't get all of its supposed PATH when used as login shell, and I discovered /etc/msystem is not sourced correctly.
Unfortunately I couldn't find a way to source it nicely, I created msystem port for fish. I tested this on my machine.
> fish: Fix msystem variables to be exported

- pacman-mirrors/PKGBUILD
- pacman-mirrors/mirrorlist.mingw32
- pacman-mirrors/mirrorlist.mingw64
- pacman-mirrors/mirrorlist.msys
We have migrated repo.msys2.org to a dedicated server, thanks to
~Appfleet.io~Appfleet.com.
> pacman-mirrors: Enable the main repo again

- binutils/2000-Temporarily-revert-default-dll-characteristics.patch
- binutils/PKGBUILD
To what they were in 2.35. We are not sure if they are compatible with
cygwin.
See https://github.com/msys2/MSYS2-packages/pull/2345 and
https://cygwin.com/pipermail/cygwin/2021-February/247922.html for context.
> binutils: change back the DLL characteristic defaults

- nano/PKGBUILD
Remove '--without-slang' unused configure option.
> nano: Update to 5.6.1

- pacman/PKGBUILD
- pacman/makepkg-mingw
In addition to this we want to add a `mingw_arch=(mingw32 mingw64)` for PKGBUILDs
in the future which tells us which type of builds a PKGBUILD supports.
The goal is to be more consistent and avoid confusion.
Other ideas welcome (we can change anything..)
> makepkg-mingw: Rename MINGW_INSTALLS to MINGW_ARCH

- sqlite/PKGBUILD
* PKGBUILD:
- increase version to 3.35.0 and year to 2021
- remove redundant configure flag '--enable-rtree' (implied by flag
'--enable-all')
- add CFLAG 'SQLITE_ENABLE_MATH_FUNCTIONS' new since 3.35.0 to activate
math functions
> sqlite: Update to 3.35.0

- sqlite/PKGBUILD
The patch release `3.35.1` contains [bug](https://www.sqlite.org/src/info/1c24a659e6d7f3a1)  fix and documentation improvements.
> sqlite: Update to 3.35.1

- btyacc/PKGBUILD
* PKGBUILD:
- change url to github repo since https://invisible-mirror.net appears
to refuse download by CI.
- change top src dir
> btyacc: Update to 20210109

- msys2-runtime/0029-Do-not-show-Error-dialogs-by-default.patch
- msys2-runtime/PKGBUILD
With this change we won't show that annoying message box e.g. when a DLL is missing, unless `MSYS` contains `winjitdebug`.
This PR is essentially forwarding https://github.com/msys2/msys2-runtime/pull/35 to MSYS2-packages.
Cc: @lazka @jeremyd2019
> msys2-runtime: make default Windows error reporting an opt-in

- mingw-w64-cross-clang-crt/PKGBUILD
- mingw-w64-cross-clang-headers/PKGBUILD
- mingw-w64-cross-crt-git/PKGBUILD
- mingw-w64-cross-headers-git/PKGBUILD
- mingw-w64-cross-tools-git/PKGBUILD
- mingw-w64-cross-ucrt-crt/PKGBUILD
- mingw-w64-cross-ucrt-headers/PKGBUILD
- mingw-w64-cross-winpthreads-git/PKGBUILD
- mingw-w64-cross-winstorecompat-git/PKGBUILD
- msys2-w32api-headers/PKGBUILD
- msys2-w32api-runtime/PKGBUILD
This should include fixes for msys2/CLANG-packages#6 and
msys2/CLANG-packages#21
> Update mingw-w64 packages to commit 1c7738.

- less/PKGBUILD
It was released for general use [yesterday](http://www.greenwoodsoftware.com/less/news.581.html).
> less: upgrade to v581

- filesystem/07-pacman-key.post
- filesystem/PKGBUILD
- gnupg/PKGBUILD
- gnupg/gnupg.install
- msys2-keyring/PKGBUILD
- msys2-keyring/msys2-keyring.install
They get started in the background and stay around which comes with various problems:
* The files can't be deleted until they are stopped
* Some CI systems wait until all programs are stopped
* On a cygwin update we have to restart everything or forking will be broken
(though pacman takes care of that now by killing everything cygwin-like on a core update)
Ideally though they would just exit in a controlled way after we no longer need them.
The reason this uses GNUPGHOME instead of passing --home to gpgconf is that dirmngr started by
"pacman-key --refresh-keys" somehow couldn't be killed that way.
Maybe because gpg doesn't forward --homedir in that case. Setting GNUPGHOME helped.
> filesystem, gnupg, msys2-keyring: avoid keeping gpg-agent/dirmngr around

- mingw-w64-cross-clang-crt/PKGBUILD
- mingw-w64-cross-clang-headers/PKGBUILD
- mingw-w64-cross-clang/PKGBUILD
- mingw-w64-cross-compiler-rt/PKGBUILD
This PR adds armv7-w64-mingw32 and aarch64-w64-mingw32 targets for mingw-w64-cross-clang{,-headers,-crt} and mingw-w64-cross-compiler-rt.
> mingw-w64-cross-clang arm and aarch64 targets

- pacman-mirrors/PKGBUILD
- pacman-mirrors/mirrorlist.md
- pacman-mirrors/mirrorlist.mingw64
- pacman-mirrors/mirrorlist.ucrt64
The ucrt64 and x86_64 repo is only supported in my repo for now due to space constraints at the moment, however, I'll solve that in a few weeks time. Also at the time of creating this PR, the x86_64 repo is still syncing with rsync, I'll make a comment on this pr when it's done.
> Canadian Mirror added

- pacman-mirrors/PKGBUILD
They just get overwritten but they shouldn't.
https://wiki.archlinux.org/index.php/PKGBUILD#backup
> pacman-mirrors: Backup mirrorlist.*

- git/PKGBUILD
- git/git-2.31.1-Cygwin-check-backslash-safety.patch
Add patch from Cygwin project that fixes arbitrary code execution vulnerability.
References:
https://cygwin.com/pipermail/cygwin-announce/2021-April/010018.html
https://github.com/me-and/Cygwin-Git/security/advisories/GHSA-rmp3-wq55-f557
> git: Add security patch from Cygwin project.

- filesystem/PKGBUILD
- filesystem/profile.000-msys2.sh
This adds a new profile.d/ script where we can add stuff without changing
/etc/profile and triggering a pacman backup.
Fixes #2438
> filesystem: set XDG_DATA_DIRS for mingw bash-completion

- pacman/PKGBUILD
- pacman/pacman.conf
We used the defaults from Arch, but Arch doesn't sign its databases.
We do sign them, so there is no reason to not enforce this.
Fixes #2453
> pacman: require databases to be signed

- pacman/0020-fix-wrong-files-sig-clean.patch
- pacman/PKGBUILD
-Sc would clean *.files.sig file which after our change to require
signatures for DBs resulted in -F complaining about missing signatures.
This was already fixed upstream master, so backport.
See https://github.com/msys2/MSYS2-packages/issues/2453#issuecomment-826881435
> pacman: fix "-F" not working after "-Sc"

- msys2-launcher/PKGBUILD
- tig/PKGBUILD
Self-explanatory, I hope. If there are others in `/etc` needing backup I couldn't find them.
> Update some PKGBUILD config backups

- mm-common/PKGBUILD
This includes autoconf m4 macros necessary to autoreconf gnome
<whatever>mm projects.  Since autoconf is msys2, this is too.
PKGBUILD largely lifted [from arch](https://github.com/archlinux/svntogit-packages/blob/13ac84ebfee343a2a452207d6c029e165676e972/trunk/PKGBUILD).
> mm-common: new package in support of gnome mm.

- gdb/0005-msysize.patch
- gdb/PKGBUILD
the msysize patch had a hunk that was missed that needed to be updated for i686.
> gdb: fix i686 build

- .ci/ci-build.sh
- .ci/ci-library.sh
By calling `rebase -i`.  Trying to help diagnose #2487.
> ci: list dll bases and lengths

- binutils/3000-more-base-entropy.patch
- binutils/PKGBUILD
We get conflicts in Python modules now. Their paths contain the cygwin
version and that happened to trigger a base image collision when being hashed
since the last update.
This change uses a bit more of the path based hash to increase the possible base addresses
and make collisions less likely.
Hopefully without any negative side effects.
> binutils: increase the address range for auto-image-base

- rhash/002-no-dynamicbase.patch
- rhash/PKGBUILD
This can't be good for cygwin magic, so disable.
> rhash: disable --dynamicbase etc.

- fish/PKGBUILD
Update fish shell to version 3.2.2. Tested build, installation and usage for ~ 2 weeks. No issues encountered.
> Update fish to 3.2.2

- filesystem/PKGBUILD
I don't think they are actually needed anymore
> filesystem: remove empty mingw root directories

- rebase/PKGBUILD
- rebase/rebase.hook
It will rebase any *.{dll,so,oct} except usr/bin/msys-2.0.dll.  Note it
requires the rebase db to be present, so essentially it requires
rebaseall to have been run (probably at install).
> [RFC] rebase: add a pacman hook on i686.

- bash/PKGBUILD
Update bash to the most recent patch level. Tested build and installation - no issues encountered.  
PKGBUILD changes modeled from the ones in Arch: https://github.com/archlinux/svntogit-packages/commit/fe58caae338735a1a67a09c3f5fa7d4e03342b58#diff-37538beb61ff63edebbf735dfcf39e5d732f49183d6beb097169d971875ca422
> Update bash to bash-5.1.008

- cygutils/0001-cygdrop-fix-return-type-of-usageCore.patch
- cygutils/PKGBUILD
- cygutils/msysize.patch
- popt/1.18-cygwin.patch
- popt/1.18-testit.patch
- popt/PKGBUILD
Note that several of the programs here depend on popt, so that has been packaged as well.
This package contains (from the package's `PROGLIST`):
* dump.exe: hex dump of file to stdout, using a nice format
* putclip.exe: copies stdin to the Windows clipboard. does NOT use Cygwin's /dev/clipboard
* getclip.exe: copies the Windows clipboard to stdout. does NOT use Cygwin's /dev/clipboard
* conv.exe: program for converting line endings of text files between DOS and UNIX format.
* msgtool.exe: A command line tool for tinkering with SysV style Message Queues
* semtool.exe: A command line tool for tinkering with SysV style Semaphore Sets
* semstat.exe: Another tool for tinkering with Semaphore Sets
* shmtool.exe: A command line tool for tinkering with shared memory
* banner.exe: prints a large …
> cygutils: add package

- cygutils/PKGBUILD
- popt/PKGBUILD
Per @elieux [on discord](https://discord.com/channels/792780131906617355/794220101741838401/847925167665184769).
Did not bump pkgrel on `cygutils` because the files present while building will be the same.
> popt: split -devel package

- .github/workflows/main.yml
For some reason it seems to have stopped being installed, so do it explicitly.
Fixes #2524
> ci: explicitly install pactoys-git

- etc-update/PKGBUILD
- filesystem/PKGBUILD
- filesystem/os-release
Gentoo's tool to manage config file updates.  Based on Arch's PKGBUILD.
etc-update looks at `/etc/os-release` to determine how config file updates are handled.  Add this to `filesystem` package, specifying that MSYS2 is like cygwin and arch (being like arch is how it decides to look at `.pacnew` files).
Word to the wise, you probably want to set the `EDITOR` environment variable.   I was testing this from a fresh install from an old installer, and `sdiff` tried to run `ed`.
> etc-update: new package

- btyacc/0001-btyacc-20210520-tests-fix-handle-dynamically-determined-YYINT.patch
- btyacc/PKGBUILD
- reflex/PKGBUILD
The btyacc testsuite needs a patch added in the btyacc the commit.
> btyacc & reflex: Upgrade to 20210510

- msys2-runtime/PKGBUILD
it was missed in https://github.com/msys2/MSYS2-packages/pull/2547
> msys2-runtime: copy `usr/libexec` folder also

- sqlite/0007-sqlite3.36.0-Makefile.in-fix-libtclsqlite-package-installation-bug.patch
- sqlite/Makefile.ext.in
- sqlite/PKGBUILD
* PKGBUILD
- upgrade version numbers and related hashes
- rename patch
* Makefile.ext.in
- add regexp.c to CSRC_IGNORE, since module is compiled into sqlite client
since version 3.36.0
* 0007-sqlite3.36.0-Makefile.in-fix-libtclsqlite-package-installation-bug.patch
- renamed from 0007-sqlite3.32.3-Makefile.in-fix-libtclsqlite-package-installation-bug.patch
- remove patch about 'info sharedlibextension' which now works with tclsh
* 0007-sqlite3.32.3-Makefile.in-fix-libtclsqlite-package-installation-bug.patch
- renamed
> sqlite: Upgrade to 3.36.0

- msys2-runtime/0043-Don-t-fall-back-to-ExitProcess-if-process-handled-Ct.patch
- msys2-runtime/PKGBUILD
This corresponds to https://github.com/msys2/msys2-runtime/pull/50.
> msys2-runtime: do not fall back to ExitProcess() on Ctrl+C

- pacman-mirrors/PKGBUILD
- pacman-mirrors/mirrorlist.mingw
- pacman-mirrors/mirrorlist.msys
The former, while faster, doesn't support symlinks and we want to
use/depend on that in the future.
> pacman-mirrors: downloads.sourceforge.net -> sourceforge.net

- pacman-mirrors/PKGBUILD
- pacman-mirrors/mirrorlist.mingw
- pacman-mirrors/mirrorlist.msys
The Internet Association of Australia has kindly agreed to mirror msys2 - both via https/rsync:
https://mirror.internet.asn.au/pub/msys2
rsync://mirror.internet.asn.au/msys2
It has been set up to sync every 4 hours.
> Add IAA mirror to pacman-mirrors

- ca-certificates/PKGBUILD
- ca-certificates/update-ca-trust
This change should fix this issue, which is quite a pain to work through as it's not obvious why pacman fails even when updating ca-trust.
https://github.com/msys2/MSYS2-packages/issues/1222
> Fix issue with certificates not being uniformly updated by update-ca-trust

- pacman/PKGBUILD
- pacman/makepkg_mingw.conf
We had discussed this on Discord a while ago.  `-march=pentium4` seemed like a reasonable minimum, requiring instruction sets through sse2.  This has been the default 32-bit instruction set for Visual Studio starting in Visual Studio 2012, and is also the default in clang (though the `-march=i686` option here has been overriding it to target Pentium Pro instead).
My personal recollection of the last CPU I had to deal with that didn't have SSE2 was the Athlon XP, circa 2005.  All 64-bit capable CPUs support SSE2.
> pacman: switch mingw i686 -march to pentium4

- pacman/PKGBUILD
explicitely fetch the patches we want to apply instead of changing the
base commit.
> pacman: backport .sig redirect fix and rework patch mngmt

- neofetch/PKGBUILD
Neofetch is a command-line system information tool written in bash 3.2
https://github.com/dylanaraps/neofetch
> Add neofetch

- python-zstandard/PKGBUILD
A python module for zstd is required to read .tar.zst files.  This is such a module, and is already packaged in MINGW-packages.
> python-zstandard: new package

- pacman/PKGBUILD
- pacman/makepkg-mingw
* Print MINGW_ARCH info when passing --help/-h
* Change behaviour when MINGW_ARCH isn't set
* Default to MSYSTEM if in a mingw environment
* Default to mingw64 otherwise (but warn)
* Print some feedback on what is getting built right away.
makepkg can take some time at the start and this makes
things clear right away.
The goal of the MINGW_ARCH change is to make it more likely to do the right thing by
default and to not special case any environment.
This has the potential of breaking existing users if MINGW_ARCH isn't set
and they want exactly "mingw32/mingw64" to be built like before. This will now build
only mingw64 if called in a msys environment and either mingw32/64 if called
in those environments.
To restore the old behavior set MINGW_ARCH="mingw64 mingw32" first.
> pacman: try to improve makepkg-mingw defaults

- ca-certificates/PKGBUILD
- ca-certificates/blacklist-dst-root-ca-x3.patch
- ca-certificates/certdata2pem.py
Let's encrypt signs current certificates based on their root
certificate "ISRG Root X1". They provide two different versions
of "ISRG Root X1", though. One is self-signed using "ISRG Root X1"
and one is cross-signed using "DST Root CA X3" [1]. Some systems
still distribute certificate chains with the cross-signed version.
"DST Root CA X3" expired on 2021-09-30. This can lead to valid
certificates being considered invalid on devices with the expired
certificate still in their CA certificate bundle.
Ubuntu[2] and RedHat[3][4] recently dropped this certificates from their
`ca-certificates` packages for the same reasons.
The blacklist code in certdata2pem is copied from the debian version
of the file as it comes with ca-certificates_20210119.tar.xz.
[1] …
> ca-certificates: drop expired "DST Root CA X3"

- gnupg/0002-fix-pcsc_io_request_s-layout-for-SCardTransmit-in-64.patch
- gnupg/PKGBUILD
Apply patch from GPG's issue [T4454](https://dev.gnupg.org/T4454) to fix scdaemon not running on WIndows (adds support for smart cards)
Addresses #2329 
Tested locally with Yubikey 5 NFC. Encryption/Decryption works just fine with GPG as well as ssh.
> Add Windows fix for smart cards

- expect/PKGBUILD
The binary was already removed, but the man page is still there.
Since it conflicts with cygwin, remove it as well.
See https://github.com/msys2/MSYS2-packages/pull/2687#issuecomment-965162412
> expect: also drop the mkpasswd man page

- curl/PKGBUILD
- curl/curl-7.60.0-gssapi-static-libs.patch
upstream no longers uses krb5-config so we switch to pkg-config too.
But the krb5 .pc file is missing sqlite3, and heimdal fails to build currently
so add it hackily..
> curl: fix static deps

- msys2-runtime/0036-console-handle-Unicode-surrogate-pairs.patch
- msys2-runtime/PKGBUILD
When running MSYS2 inside the Windows Terminal, it is currently impossible to paste an emoji (e.g. via recent Windows' <kbd>Windows</kbd>+<kbd>.</kbd> shortcut).
The reason is that emojis cannot be represented by single UTF-16 values, they require _surrogate pairs_. This was recently fixed in Cygwin (not in any official version as yet), and we backported this in https://github.com/msys2/msys2-runtime/pull/67.
This fixes https://github.com/msys2/msys2-runtime/pull/66.
> MSYS2 runtime: fix pasting emojis in the Windows Terminal

- python/PKGBUILD
remove libcrypt-devel since that was removed upstream, see
https://bugs.python.org/issue44751
> python: Update to 3.9.9

- filesystem/01-devices.post
- filesystem/PKGBUILD
When launching a custom msys2 environment, and it does "first-run"
operations, it complains that: "cannot change permissions of
'/dev/shm': Permission denied".
This is related to the previous work in this area that happened
in #2337: Since "/" is mounted with noacl and chmod() is a no-op,
this error is cosmetic and can be removed.
However, in #2337, the access modifying behaviour was not removed
from the "mkdir" branch, which this patch aims to address.
> filesystem: Avoid trying to chmod /dev/{shm,mqueue} during mkdir

- glib2/PKGBUILD
- guile/PKGBUILD
- libffi/PKGBUILD
- libffi/libffi-3.3-msysize.patch
- libffi/libffi.install
- p11-kit/PKGBUILD
- python/PKGBUILD
Reverts msys2/MSYS2-packages#2721
This seems to have broken python pretty badly, to the point where the CI python script doesn't even work anymore.
```
0 [main] python3 312 child_info_fork::abort: address space needed by '_random.cpython-39-x86_64-msys.dll' (0x190000) is already occupied
Traceback (most recent call last):
File "/C/_/.ci/ci-get-build-order.py", line 91, in <module>
packages = "\n".join(get_build_order(list_packages()))
File "/C/_/.ci/ci-get-build-order.py", line 35, in list_packages
changes = list_changes("--pretty=format:", "--name-only")
File "/C/_/.ci/ci-get-build-order.py", line 30, in list_changes
out += run("git", "log", *git_args, "HEAD^..").splitlines()
File "/C/_/.ci/ci-get-build-order.py", line 20, in run
return subprocess.check_output(args, …
```
> Revert "libffi: Update to 3.4.2"

- pactoys/PKGBUILD
> pactoys: update

- autotools/PKGBUILD
- autotools/README.md
The goal of this package is to depend on everything that is (usually)
needed for running autogen/autoreconf if needed,
configure and make, but not a compiler.
If packages would makedepend on this then we could make base-devel smaller and remove all the autotools things from there. So if a package builds with meson or cmake, it doesn't install autoconf in CI.
autotools is then just another build system
> Add an autotools meta package

- cocom/PKGBUILD
from what I see this is only needed for building cygwin, and it's already
a makedep there.
> cocom: remove from msys2-devel group

- autoconf/PKGBUILD
- autoconf2.13/PKGBUILD
- autogen/PKGBUILD
- automake-wrapper/PKGBUILD
- automake1.10/PKGBUILD
- automake1.11/PKGBUILD
- automake1.12/PKGBUILD
- automake1.13/PKGBUILD
- automake1.14/PKGBUILD
- automake1.15/PKGBUILD
- automake1.16/PKGBUILD
- automake1.6/PKGBUILD
- automake1.7/PKGBUILD
- automake1.8/PKGBUILD
- automake1.9/PKGBUILD
- libtool/PKGBUILD
- m4/PKGBUILD
All packages depend on it explicitly now.
> Remove autotools from base-devel

- autoconf2.69/0001-fix-texinfo.patch
- autoconf2.69/0002-msys2.patch
- autoconf2.69/0003-autotest-remove-cr-from-prog-stdout-stderr.patch
- autoconf2.69/0004-docs.patch
- autoconf2.69/0005-package.patch
- autoconf2.69/PKGBUILD
Useful for rebuilding configure files when upstream only supports 2.69 such as bintuils and gcc
> Add back a autoconf2.69 package

- python/28881-backport.patch
- python/PKGBUILD
> python: backport patch to not link against crypt

- sed/PKGBUILD
- sed/gnulib-cygwin-weak-bug.patch
gnulib configure wrongly defines HAVE_WEAK_SYMBOLS, backport a patch
to fix the resulting crashes.
Fixes #2748
> sed: rebuild with gnulib fix

- btyacc/PKGBUILD
- reflex/PKGBUILD
They were added in 7452014cc2c6e4348d but it's not clear why.
> Remove btyacc and reflex from base-devel

- base-devel/PKGBUILD
- base-devel/README.md
Replaces the package group 'base-devel'.
Easier to add/remove packages when it is a package.
```
$ pactree base-devel
base-devel
├─binutils
│ ├─libiconv
│ │ ├─gcc-libs
│ │ └─libintl
│ │   ├─gcc-libs
│ │   └─libiconv
│ ├─libintl
│ └─zlib
│   └─gcc-libs
├─bison
│ ├─m4
│ │ ├─bash
│ │ ├─gcc-libs
│ │ └─libiconv
│ └─bash provides sh
├─diffstat
├─diffutils
│ └─bash provides sh
├─dos2unix
│ └─libintl
├─file
│ ├─gcc-libs
│ ├─zlib
│ └─libbz2
│   └─gcc-libs
├─flex
│ ├─m4
│ ├─bash provides sh
│ ├─libiconv
│ └─libintl
├─gawk
│ ├─bash provides sh
│ ├─mpfr
│ │ └─gmp provides gmp>=5.0
│ ├─libintl
│ └─libreadline
│   └─ncurses
│     └─gcc-libs
├─gettext
│ ├─libintl
│ ├─libgettextpo
│ │ └─gcc-libs
│ └─libasprintf
│   └─gcc-libs
├─gperf
│ ├─gcc-libs
│ └─info
│   ├─gzip
│   │ ├─bash
│   │ └─less
│   │ …
```
> Add a base-devel package

- perl/PKGBUILD
Saves 8MB compressed and 980 files when not installed
Fixes #2774
> perl: split out documentation into an extra perl-doc package

- libtool/0009-libtool-2.4.2.418-msysize.patch
- libtool/PKGBUILD
So that if we target a cygwin triplet we still get libraries with a "msys-" prefix.
This allows us to get rid of some msysize patches if we run autoreconf and
pass a cygwin triplet instead of a msys one.
> libtool: override the soname_spec for cygwin as well

- pacman/PKGBUILD
- pacman/makepkg-mingw
See https://github.com/msys2/MINGW-packages/discussions/10506
> pacman: no longer require toolchains to be installed when running makepkg-mingw

- make/PKGBUILD
It makes problems on 32bit, so disable to fix that and just to
be safe.
See https://github.com/msys2/MSYS2-packages/issues/2801
> make: rebuild without posix_spawn support

- base-devel/PKGBUILD
patchutils:
* It mostly contains tools that are useful to developers, but are not used in
a PKGBUILD directly.
intltool:
* It's long abandoned and everyone should be using gettext
and we want to get rid of it in the long run.
* Many packages that need it depend on it anyway
> base-devel: remove patchutils/intltool

- mingw-w64-cross-binutils/0010-bfd-Increase-_bfd_coff_max_nscns-to-65279.patch
- mingw-w64-cross-binutils/0100-binutils-2.37-msys2.patch
- mingw-w64-cross-binutils/0110-binutils-mingw-gnu-print.patch
- mingw-w64-cross-binutils/PKGBUILD
The building of this package locks for me without this upgrade.
I have not used to package; but, plan to build the rest of these cross mingw packages (not doing the clang ones). I figure if they build then this package works.
See #2807 
Tim S.
> mingw-w64-cross-binutils: Update to version 2.37

- msys2-runtime/0036-Cygwin-path-Convert-UNC-path-prefix-back-to-drive-le.patch
- msys2-runtime/0037-Cygwin-path-Fix-path-conversion-of-virtual-drive.patch
- msys2-runtime/0038-fixup-CI-add-a-GHA-for-doing-a-basic-build-test.patch
- msys2-runtime/0039-Cygwin-fhandler_pipe-get_query_hdl_per_process-avoid.patch
- msys2-runtime/0040-POSIX-ify-the-SHELL-variable.patch
- msys2-runtime/0041-Handle-ORIGINAL_PATH-just-like-PATH.patch
- msys2-runtime/0042-fixup-CI-add-a-GHA-for-doing-a-basic-build-test.patch
- msys2-runtime/PKGBUILD
Forward-porting https://github.com/msys2/msys2-runtime/pull/79:
In MSYS2 <-> MINGW transitions, we convert a couple of environment variables between Unix and Windows styles, most notably `PATH`.
In the Git for Windows project, we realized that the environment variables `SHELL` and `ORIGINAL_PATH` need the same treatment. These patches have proved their worth for years, and it is time for them to be integrated back into the actual MSYS2 runtime.
This should fix https://github.com/msys2/msys2-runtime/issues/43.
> msys2-runtime: special case the SHELL and ORIGINAL_PATH env vars

- msys2-runtime/0044-path_conv-a-directory-with-.lnk-suffix-is-not-a-.lnk.patch
- msys2-runtime/PKGBUILD
This corresponds to https://github.com/msys2/msys2-runtime/pull/82 and fixes https://github.com/msys2/msys2-runtime/issues/81.
> msys2-runtime: a directory with .lnk suffix is not a .lnk file

- docbook-xml/PKGBUILD
- docbook-xml/docbook-xml.install
It appears an overzealous conversion of http to https inadvertently
changed this, breaking the catalog registration.
Fixes #2834
> docbook-xml: install catalogs with http URI

- filesystem/PKGBUILD
- filesystem/profile.000-msys2.sh
This will be shown on a login shell, so the first two lines when
users open a MSYS2 terminal.
This is the linked website: https://www.msys2.org/docs/windows_support/
~~Maybe I should try set an en var, so it doesn't get shown again on nested login shells.~~ done
> filesystem: warn users that Windows 7/8 support is going away

- docbook-mathml/PKGBUILD
- docbook-mathml/docbook-mathml.install
This is in the same spirit as https://github.com/msys2/MSYS2-packages/pull/2826 (where I really should have `git grep`ed for similar instances, but forgot).
Note: after this, `docbook/PKGBUILD` still contains calls to `xmlcatalog` without any `/usr/bin/` prefix. This is intentional because the `PATH` should be set correctly when _building_ MSYS packages, anyway (in contrast to the scenario where `.install` is called, i.e. when the packages are _installed_).
So this is the rule: use `usr/bin/xmlcatalog` in the `.install` scripts, and `xmlcatalog` in `PKGBUILD`.
> Fix the install script of `docbook-mathml`, too

- autoconf2.69/0006-autoconf2.5-2.69-perl-5.22-autoscan.patch
- autoconf2.69/PKGBUILD
This patch was copied from cygwin.
This patch fixes check so it finishes without error.
Tim S.
> autoconf2.69: Add 0006-autoconf2.5-2.69-perl-5.22-autoscan.patch

- grml-zsh-config/PKGBUILD
- txt2tags/PKGBUILD
The `/usr/bin/txt2tags` stub uses `pkg_resources` from python-setuptools, which was present on the older build system.
So on CI, without python-setuptools by default, `txt2tags` fails, generating empty man files.
And building grml-zsh-config succeeds even when `txt2tags` fails (I'm working on an upstream PR to address their Makefile, though there's no need here to wait for that).
Arch Community has done [the same thing](https://github.com/archlinux/svntogit-community/commit/29a507d5eb40b48cacba77349a0d17657ff46eed) with txt2tags, maybe for the same reason? I'm mostly python-illiterate, if there's a better way to fix this I'm all ears.
This PR includes a grml-zsh-config update "for free".
> Fix txt2tags dependency and grml-zsh-config empty man pages

- openssh/PKGBUILD
I'd like to use [openssh-sk-winhello](https://github.com/tavrez/openssh-sk-winhello) with OpenSSH in my MSYS2 environment, but I've found that security keys are disabled in the build.  I can't find any documentation on why this is disabled, and I am able to successfully build OpenSSH and use FIDO2 security keys by removing this flag.
I'm not sure if something else needs to be added to get this in to a current build without changing ssh version, so please help advise me what else is needed to make this PR successful.
Thank you!
> Enable security keys in OpenSSH

- bash/PKGBUILD
This seems to be the latest patch level.
> bash: upgrade to v5.1 patchlevel 16

- mingw-w64-cross-winpthreads-git/PKGBUILD
- msys2-runtime/PKGBUILD
So we don't depend on a committer being set
> Use git apply instead fo git am

- filesystem/PKGBUILD
- filesystem/profile.000-msys2.sh
'function' causes an error when I execute a shell with 'dash'; removing it seems to restore expected behavior (unable to test the actual function as I don't have win7 or win8)
> filesystem: Improve compatibility of '_warn_deprecated_winver'

- git/PKGBUILD
It's also the default in Ubuntu/Debian, and vim users should be capable
of switching if they want. nano is generally easier to use for beginners.
> git: default to nano instead of vim

- git/PKGBUILD
- git/git-2.35.1-git-gui.patch
based on https://github.com/msys2/MSYS2-packages/pull/1912, some old upstreaming process: https://github.com/gitgitgadget/git/pull/612
In theory the script needs some way to detect a MSYS2 mingw env and special case some
things on top of that in combination with is_Cygwin.
Since we want to keep this diff small, keep it hacky.
> Try to make "git gui" work again

- texinfo/0006-msys2-OS-detection-in-texi2dvi.patch
- texinfo/PKGBUILD
Cherrypick upstream patch.
Fixes #2901.
> texinfo: Don't override MSYSTEM in check for path separator.

- fish/PKGBUILD
This PR updates the PKGBUILD to build the latest release of `fish-shell` - `3.4.1`.
- Built and tested on a personal machine, works as expected. No issues encountered so far.
- PKGBUILD is based on Arch Linux `fish` https://github.com/archlinux/svntogit-community/blob/packages/fish/trunk/PKGBUILD
> Update fish to 3.4.1

- file/PKGBUILD
We have three copies of this in the package, but
neither Arch, nor Debian ship them in their package.
Let's just drop them.
This was copied from cygwin, which copied from Fedora:
https://cygwin.com/git-cygwin-packages/?p=git/cygwin-packages/file.git;a=blob;f=file.cygport;h=803ce6b422d4ef316ec25f6587725720bb078f79;hb=HEAD
but it's not clear why it is needed.
> file: drop the text based magic DBs

- u-boot-tools/PKGBUILD
U-Boot v2022.04 host tools (mkeficapsule) introduced new build
dependencies to libgnutls-devel and libuuid-devel. No runtime
dependencies are needed as the mkeficapsule executable is for
testing purpose and we didn't ship it since day 1.
> u-boot-tools: Update to v2022.04

- readline/PKGBUILD
ncurses has started to default to dllimport by default, which means
NCURSES_STATIC has to be set by anyone trying to statically build against it
to get the right symbol names.
To keep things simple for us just build twice, once dynamically and
once statically with NCURSES_STATIC set.
Alternative to #2956
Also removes the "RPATH" part, which was copied from Arch, but from what I see
doesn't change anything for us.
> readline: set NCURSES_STATIC for the static build

- pacman/PKGBUILD
- pacman/pacman.conf
And add commented out versions of clangarm64 and staging while at it,
so they are easy to enable if wanted.
> pacman: enable clang32 by default

- git-extras/PKGBUILD
Release notes for git-extras 6.4.0
https://github.com/tj/git-extras/releases/tag/6.4.0
> Update git-extras to 6.4.0

- libxml2/PKGBUILD
from what I see this is only used for encoding/decoding and the
README says "Mainly useful as an
alternative to iconv on Windows. Unnecessary on most other systems."
Since this is the only user of icu in base this also helps the installer size.
> libxml2: drop icu dependency

- base/PKGBUILD
Windows nowadays has a tar.exe in System32 which is first in PATH
with a clean MSYS2 install.
This will both confuse users as well as scripts because it is
a non-cygwin bsdtar.
To avoid surprises add tar to base.
> base: add tar

- inetutils/PKGBUILD
It's only using a header, nothing more.
See https://cygwin.com/pipermail/cygwin-apps/2013-August/033227.html
> inetutils: only makedepend on tftp-hpa

- pacman-contrib/0100-contrib.patch
- pacman-contrib/PKGBUILD
patch one new call to bsdtar to use an absolute path.
> pacman-contrib: Update to 1.5.3

- breezy/PKGBUILD
force cython rebuild
don't update to 3.2.2 for now since that requires a new dependency
> breezy: update to 3.2.1

- coreutils/004-msystem-osname-cygwin.patch
- coreutils/PKGBUILD
If MSYSTEM=CYGWIN we output "Cygwin" as the operating system.
This is relevant in build scripts which call "uname -o" and
check for cygwin there.
> coreutils: "uname -o" -> Cygwin if MSYSTEM=CYGWIN

- isl/PKGBUILD
all users have been rebuilt, so we can drop the old DLL
> isl: drop 0.22 dll

- python-setuptools/PKGBUILD
- txt2tags/PKGBUILD
The one before the distutils switch. In theory the latest should
include all cygwin patches and should work too, but let's do this
one change at a time.
> python-setuptools: Update to 59.8.0

- python-setuptools/PKGBUILD
This version will take over the stdlib distutils
> python-setuptools: Update to 63.2.0

- less/PKGBUILD
See https://www.greenwoodsoftware.com/less/news.608.html
There is one news item that _sounds_ like it could cause trouble when not using the Win32 Console (such as running in a MinTTY window): "Fix bug in input of non-ASCII characters on Windows."
Following the "View git blame" trail leads to https://github.com/gwsw/less/commit/2bf67924e3be558bc6b9df61ae7ef510918f28b8 which sounds innocuous enough: we probably do not use `WIN32getch()` because we're compiling in Cygwin mode.
> less: upgrade to v608

- guile/0001-Fix-dynamic-library-guile-readline-name-on-Cygwin.patch
- guile/0002-Fix-warning-if-libguile-is-used-with-compile-option-.patch
- guile/0101-Add-convert-a-standard-shared-library-name-for-MSYS.patch
- guile/0201-Activate-test-pthread-create-secondary-for-Cygwin.patch
- guile/0202-Include-ITIMER_REAL-test-in-signals.test-for-Cygwin.patch
- guile/0301-In-foreign.test-add-linked-dll-for-host-type-msys-explicitly.patch
- guile/0302-In-i18n.test-add-unresolved-for-host-type-msys.patch
- guile/0303-In-tests-add-dynamic-link-to-msys-2.0-for-host-type-msys.patch
- guile/0304-Skip-tests-using-setrlimit-for-MSYS-as-done-for-Cygwin.patch
- guile/0305-Remove-failed-test-00-repl-server.test.patch
- guile/PKGBUILD
- activate check()
- only set configure options which are not set by default
- fix depends for libguile-devel
- add support for gdb guile auto-load
> guile: update to 3.0.8

- gdb/PKGBUILD
Now gdb guile extension also with auto-loading is working. This simplifies debugging guile code.
Fix for ModuleNotFoundError: No module named 'libstdcxx' with updated gcc_ver=11.3.0
> gdb: add support for guile and minor fix for ModuleNotFoundError

- guile/PKGBUILD
Fix path and generalize filename for dlltool
> guile: fix auto-load filename for gdb

- libgpg-error/PKGBUILD
This is for backward compatibility.
> libgpg-error: Install gpg-error-config script explicitly

- gnupg/PKGBUILD
fails due to a missing ldap check, I'm waiting for my upstream account being confirmed so I can file a bug.
edit: was already filed https://dev.gnupg.org/T6239
> gnupg: Update to 2.2.40

- pacman/PKGBUILD
- pacman/makepkg_mingw.conf
This allows SSE4.2 and CMPXCHG16, the same with RHEL 9.
Reference: https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level
Signed-off-by: LIU Hao <lh_mouse@126.com>
> pacman: Set default arch to `x86-64-v2`

- pacman/PKGBUILD
- pacman/makepkg_mingw.conf
There are some old AMD CPUs which run Win10 (somehow) but don't have SSSE3 (not to be confused with SSE3), so explicitely disable it. Both gcc and clang seem to understand this combination.
> makepkg: disable SSSE3 by default

- pacman/PKGBUILD
- pacman/makepkg_mingw.conf
This follows what Arch Linux does by default, see
https://github.com/archlinux/svntogit-packages/blob/091c8714716b40241f4259c8e6fdf99508944a2f/trunk/makepkg.conf#L42
This is now possible after https://github.com/msys2/MINGW-packages/issues/13401
> makepkg: set _FORTIFY_SOURCE=2 by default

- binutils/0100-binutils-2.37-msys2.patch
- binutils/PKGBUILD
I missed one target check when rebasing the patches. This only affects 32bit, so I didn't notice.
> binutils: fix dynamicbase being set for 32bit binaries

- pacman/PKGBUILD
- pacman/makepkg_mingw.conf
In case a package has a configure check for say -mssse3 and then enables it if the compiler supports it it would be passed to the compiler before our CFLAGS, which currently has -mno-ssse3 (which seems to also disable sse4 and above while at it). The code then assumes it's available but the compiler fails.
While one could argue that we try to prevent ssse3+ being used in packages, there
are always exceptions like building sse4 code which dynamically gets executed.
So it's better we only enable machine options in CFLAGS and never disable them
Replace "-march=core2 -mno-ssse3" with the equivalent "-march=nocona -msahf". Note that the GCC docs wrongly state that "nocona" doesn't include "CX16", while it does.
See https://github.com/msys2/MINGW-packages/pull/13651
> makepkg: don't use "-mno-*" in CFLAGS

- pacman/PKGBUILD
- pacman/makepkg_mingw.conf
Linux distros have this enabled for years, let's give it a try.
See #3237
> makepkg: add -fstack-protector-strong to default CFLAGS

- tzcode/PKGBUILD
don't fail if gettext is detected by explicitely disabling it
> tzcode: Update to 2022f

- nnn/PKGBUILD
Adding this to MSYS2-packages since one of the deps is only packaged here (ncurses-devel), plus vifm is also here, which is comparable. Both are terminal-based productivity tools to make it easier to develop in the terminal.
> Add nnn terminal file manager

- mosh/PKGBUILD
Diffing the extracted .tar.gz files, it seems they regenerated the autotools files with newer versions, and replaced the file on the github release.
https://github.com/msys2/MSYS2-packages/pull/3263#issuecomment-1297921581
> mosh: update sha256sum

- pacman/PKGBUILD
- pacman/makepkg_mingw.conf
There are many cases where the extra memory is helpful and with the type of software we package this hopefully shouldn't lead to any problems.
Fixes #3283
> makepkg: default to -Wl,--large-address-aware

- libunistring/PKGBUILD
rebuilds are through and in the repo, so we can drop the 1.0 dll now
> libunistring: remove old DLL again

- gdb/PKGBUILD
Cherry-pick patch from upstream to fix compilation with readline 8.2.
Also install license files.
> gdb: Fix building with readline 8.2

- nano/PKGBUILD
* gnulib was updated, so we can remove the weak symbol workaround
* the signing key changed, see https://lists.gnu.org/archive/html/info-gnu/2022-11/msg00005.html
> nano: Update to 7.0

- msys2-runtime/PKGBUILD
See https://github.com/msys2/msys2-runtime/pull/117
> msys2-runtime: apply workaround for missing trailing slashes with path_conv

- glib2/PKGBUILD
* 'fam' was dropped upstream
* glib switched from pcre to pcre2
* socklen_t is signed in cygwin which triggers -Werror=pointer-sign
> glib2: Update to 2.74.3

- libtool/PKGBUILD
> libtool: fix license file location

- libxml2/PKGBUILD
* libxml2/PKGBUILD:
- remove the libraries 'ncurses' and 'ncurses-devel' from depends and makedepends, resp., since they are indirect dependencies to libxml2.
- make autoreconf be verbose
- remove trailing spaces
> libxml2: remove indirect dependencies

- tmate/PKGBUILD
doesn't seem to be used anymore
> tmate: don't makedep on ruby

- wget/PKGBUILD
This follows what Arch/Fedora/Debian do:
https://github.com/archlinux/svntogit-packages/commit/b9ffaf59269e655fb4b4
This also avoids any potential openssl v3 compat issues
> wget: switch from openssl to gnutls

- openssl/0002-Support-MSYS2.patch
- openssl/PKGBUILD
Build for cygwin and patch the DLL names instead.
Also remove the OSNAME check in the perl scripts as I'm not sure if perl will continue to report "msys" and we might switch it to "cygwin" too, see https://github.com/msys2/MSYS2-packages/issues/3401
While at it also re-enable makeflags, building with multiple cores seems to work fine here, and is much faster.
All tests pass with this.
> openssl: build for cygwin

- python-yaml/PKGBUILD
- python-yaml/python-yaml.install
port to build/installer
drop install file - the warning isn't msys2 specific, that's how the package works.
> python-yaml: Update to 6.0

- msys2-runtime/1001-Revert-Cygwin-Enable-dynamicbase-on-the-Cygwin-DLL-b.patch
- msys2-runtime/PKGBUILD
We are seeing fork errors in Docker, which might be related to 3.4.x setting dynamicbase. Let's see if reverting that helps.
> msys2-runtime: disable dynamicbase again

- msys2-runtime/PKGBUILD
Upstream no longer manually strips the cygwin dll and creates a debug file since https://cygwin.com/git/?p=newlib-cygwin.git;a=commit;h=99bb3e937a0fdbc1e3acbdc7cefb31e54a89a6ac
This means the debug info now moved from msys2-runtime-devel to msys2-runtime staying in the DLL.
We don't really want to install/ship debug infos by default, so we could either re-implement the debug info extraction manually again, or let makepkg build a separate "-debug" package, or just strip everything.
Since the later is the least work and the least special compared to other packages, just enable stripping.
> msys2-runtime: strip it

- openssl/0005-skip-dllmain-detach.patch
- openssl/PKGBUILD
openssl/cygwin crashes when pthread APIs are called in DllMain:
0  0x0000000000000000 in ?? ()
1  0x00000001801619bd in pthread_rwlock_wrlock (rwlock=0x800275ff0)
at /c/S/msys2-runtime-3.3/src/msys2-runtime/winsup/cygwin/thread.cc:3228
2  0x000000018019905b in _sigfe () at sigfe.s:35
3  0x00000004358490c9 in CRYPTO_THREAD_write_lock () from /usr/bin/msys-crypto-3.dll 4  0x000000043583c414 in init_thread_remove_handlers () from /usr/bin/msys-crypto-3.dll 5  0x000000043583c843 in OPENSSL_thread_stop () from /usr/bin/msys-crypto-3.dll 6  0x000000043583a953 in DllMain () from /usr/bin/msys-crypto-3.dll
It can be reliably reproduced by calling "meson test", which spawns threads for tests.
Something similar was discussed on the cygwin mailing list years ago, and it seems nothing has …
> openssl: disable cleanup in DLL_THREAD_DETACH

- opensp/PKGBUILD
For some reason, libtool was screwing up when I tried to build this for 32-bit msys2, even though it apparently built fine on 64-bit msys2. autoreconf to get updated (and presumably bugfixed) libtool files.
> opensp: autoreconf

- base-devel/PKGBUILD
- coreutils/PKGBUILD
- cvs/PKGBUILD
- gettext/PKGBUILD
- zsh/PKGBUILD
Not many packages need it, so try to move it to explicit
makedepends instead.
> base-devel: remove groff

- pax/PKGBUILD
switch to http since the upstream TLS setup is no longer supported by openssl
> pax: rebuild

- bisoncpp/PKGBUILD
* PKGBUILD:
- use release tar instead of git tag
- remove outdated dependency version requirements (not documented in package any more)
- FIX BUG to handle symlinks when unzipping
- remove html documentation already covered by man doc in package
- additional edits
> bisoncpp: Update to 6.04.44

- filesystem/PKGBUILD
- filesystem/dot.profile
This was added in e259adce916745c3934
(1) this isn't executed if bash_profile exists, which is the default and (2) I don't think we should include msys2 development related functions here
> filesystem: drop agm2 function

- .ci/ci-build.sh
- .ci/ci-dont-install-list.txt
- msys2-runtime/PKGBUILD
so we get "3.4.3.x86_64" instead of "3.4.3-dirty.x86_64"
> msys2-runtime: explicitely set a runtime version

- readline/PKGBUILD
- readline/inputrc
This is just a copy of the current inputrc from the "filesystem" package which currently gets installed as ~/.inputrc on the first start.
The goal is to remove ~/.inputrc, so that on the first msys2 start the config is already there and a shell restart is no longer needed.
readline is statically linked into bash, so there is no readline dependency, so we assume that libreadline is installed with "base" in some way.
> readline: add etc/inputrc

- python-packaging/PKGBUILD
and don't depend on python-build, to avoid a cycle
> python-packaging: Update to 23.0

- ansible-core/PKGBUILD
- ansible/PKGBUILD
With this, package `ansible-core` was added, which contains only the core logic. `ansible` package now contains the community collection library that depends on `ansible-core`.
When Ansible updated to the 3.0.0 version as they mention, the known ansible-base package moved to ansible-core (see reference: [Ansible 3.0.0 Q&A](https://www.ansible.com/blog/ansible-3.0.0-qa)).
> The former became known as ansible-base (soon to be [ansible-core](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_11.rst)). The latter became additions on top of the core, available either ad-hoc or as part of the Ansible community package, which includes a set of curated and maintained Collections.
Solves:
* https://github.com/msys2/MSYS2-packages/issues/3187
> update ansible to 2.14.1, add ansible community collections

- less/PKGBUILD
There are many commits in the main branch of `less` since the last version that was released "for general use" (v608).
Hoping that some of those commits fix issues reported in the Git for Windows bug tracker, let's update to the latest tagged version, v621.
An alternative would be to backport individual patches, but due to some sweeping changes (e.g. to convert from Kernighan & Ritchie style to C89 style function definitions), I've failed to backport them separately.
Switch to a GitHub archive since this release isn't available on the website yet.
> less: Update to v621

- pacman/PKGBUILD
With win7/8 support dropped now we can bump our CPU requirements for msys packages.
This makes them match what we already use for mingw packages.
> pacman: sync -march flags from mingw to msys

- file/PKGBUILD
enable all compression variants we support, so this doesn't regress again.
> file: re-enable zstd support

- socat/PKGBUILD
it was missing the devel package and depending on the libraries should be enough.
> socat: fix missing openssl support

- zstd/PKGBUILD
* work around symlink in tarball
* don't statically link the .exes, there is no need to
> zstd: Update to 1.5.4

- brotli/0001-link-exe-shared.patch
- brotli/PKGBUILD
they are in the same package anyway, so saves some space
> brotli: link brotli.exe against the shared libs

- brotli/PKGBUILD
- python-brotli/PKGBUILD
so there are fewer dep cycles. (hopefully)
Fixes #3562
> brotli: split out python-brotli into its own PKGBUILD

- file/PKGBUILD
- gdb/PKGBUILD
- glib2/PKGBUILD
- znc/PKGBUILD
Now that we switch to Python 3.11 we can do so without creating upgrade conflicts.
> Add .pyc files to some packages

- make/PKGBUILD
Update the posix_spawn comment, as the issue has been fixed in cygwin. I tested the performance issue again, and posix_spawn is still slower, so adjust the comment and keep posix_spawn disabled.
> make: Update to 4.4.1

- openssl/PKGBUILD
To follow what other distros do, like Arch or Debian
Fixes #3731
> openssl: disable zlib support

- gradle/PKGBUILD
gradle-8.1-1 was broken and failed to start with these messages:
Error opening zip file or JAR manifest missing : C:\msys64\usr\share\java\gradle/lib/agents/gradle-instrumentation-agent-8.1.jar
Error occurred during initialization of VM
agent library failed to init: instrument
Sorry!
> gradle: Fix "Error opening zip file or JAR manifest missing"

- mingw-w64-cross-crt-git/PKGBUILD
- mingw-w64-cross-headers-git/PKGBUILD
- mingw-w64-cross-tools-git/PKGBUILD
- mingw-w64-cross-winpthreads-git/PKGBUILD
- mingw-w64-cross-winstorecompat-git/PKGBUILD
we want to get rid of the "git" suffix, so remove "replaces" first to avoid temporary replace cycles.
We export CC in makepkg now and that makes autotools try to use it
instead of the host compiler, so unset it.
> mingw-w64-cross: remove "replaces"

- sqlite/PKGBUILD
NB: The github action run on my fork hangs in step `dll check` for whatever reason. Let's see what happens here.
> sqlite 3.42.0: remove unnecessary dependencies from split packages

- libxml2/PKGBUILD
> libxml2: try building without libcrypt

- python/PKGBUILD
_crypt.cpython-311-x86_64-msys.dll depends on it
> python: add missing libcrypt dep

- libxcrypt/4.4.2-cygwin-no-undefined.patch
- libxcrypt/PKGBUILD
See #3505
needs dev split and rebuild tests; static libs; is this needed for pacman indirectly?
> Add libxcrypt

- curl/PKGBUILD
it doesn't seem to be used (at least not directly)
> curl: remove libcrypt dependency

- perl-XML-Parser/PKGBUILD
doesn't seem to be used directly
> perl-XML-Parser: remove libcrypt dependency

- inetutils/PKGBUILD
doesn't seem to be used directly
> inetutils: remove libcrypt dependency

- emacs/PKGBUILD
> emacs: remove libcrypt dependency

- perl-ExtUtils-MakeMaker/PKGBUILD
> perl-ExtUtils-MakeMaker: remove libcrypt

- libcrypt/PKGBUILD
- libxcrypt/PKGBUILD
* Replace/provides so users will be moved over
* Remove libcrypt-devel, so no one can link against it
* Keep the old DLL around for now to avoid breaking external users.
Fixes #3505
> Replace libcrypt-devel with libxcrypt-devel

- libuv/PKGBUILD
see https://github.com/msys2/msys2-runtime/pull/164
> libuv: remove workaround for c89 with cygwin

- .ci/ci-build.sh
* .ci/ci-build.sh: run ldd separately for each binary
> [CI] DLL Dependency Check - prohibit data chases for LDD

- msys2-runtime/0041-Cygwin-Fix-and-streamline-AT_EMPTY_PATH-handling.patch
- msys2-runtime/0042-Cygwin-use-new-_AT_NULL_PATHNAME_ALLOWED-flag.patch
- msys2-runtime/0043-Define-_AT_NULL_PATHNAME_ALLOWED.patch
- msys2-runtime/0044-Cygwin-gen_full_path_at-drop-never-reached-code.patch
- msys2-runtime/PKGBUILD
This corresponds to https://github.com/msys2/msys2-runtime/pull/166
/cc @alex-tee
> msys2-runtime: backport fix for `tar xf` with symlinks

- protobuf/0001-constant-initializer.patch
- protobuf/PKGBUILD
Protobuf doesn't build for staging with the following error:
```
google/protobuf/struct.pb.cc: At global scope:
google/protobuf/struct.pb.cc:47:110: error: 'constinit' variable 'google::protobuf::_Struct_default_instance_' does not have a constant initializer
47 | PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StructDefaultTypeInternal _Struct_default_instance_;
|                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
google/protobuf/struct.pb.cc:47:110:   in 'constexpr' expansion of 'google::protobuf::StructDefaultTypeInternal()'
google/protobuf/struct.pb.cc:41:9: error: 'constexpr google::protobuf::Struct::Struct(google::protobuf::internal::ConstantInitialized)' called in …
```
> protobuf: fix build error

- vim/0001-BACKPORT-dynamically-linking-perl-is-broken.patch
- vim/PKGBUILD
The major Perl version is encoded in the file name of the Perl DLL, which makes it much more desirable to link _dynamically_ to the DLL, i.e. on demand. Otherwise `vim.exe` would not even start unless Perl is installed, and the exact expected version at that.
However, due to a bug, even `--enable-perlinterop=dynamic` would let `vim.exe` link to the Perl DLL, defeating the purpose of the `dynamic` part.
This was fixed in the VIM project, via https://github.com/vim/vim/commit/55460da26c27, and here is a backport to get this fix into MSYS2.
This PR addresses https://github.com/git-for-windows/MSYS2-packages/pull/115#issuecomment-1722506060.
> vim: only link to the perl DLL _dynamically_

- jsoncpp/PKGBUILD
- jsoncpp/jsoncpp.install
remove non-default build options, git history doesn't show
why they were added, they shouldn't be needed.
Remove install file which just prints a warning
> jsoncpp: rebuild

- tar/PKGBUILD
32-bit cygwin (and thus msys2) only supports 32-bit time_t, so this configure check was failing there.  Yet another reason not to use 32-bit anymore.  This might also be relevant to @dscho in git-for-windows
Fixes #4078
> tar: disable check for year 2038 support on 32-bit.

- apr-util/PKGBUILD
> apr-util: add missing dependency on libxcrypt

- nghttp2/PKGBUILD
patch is included in this release
> nghttp2: Update to 1.58.0

- gawk/PKGBUILD
* PKGBUILD:
- remove configure flag --without-libsigsegv obsolete since 5.3.0
> gawk: Update to 5.3.0

- perl-Term-Table/PKGBUILD
Importer is no longer used since 0.017
> perl-Term-Table: Update to 0.018

- mingw-w64-cross-binutils/PKGBUILD
- mingw-w64-cross-crt/PKGBUILD
- mingw-w64-cross-gcc/PKGBUILD
- mingw-w64-cross-headers/PKGBUILD
- mingw-w64-cross-tools/PKGBUILD
- mingw-w64-cross-ucrt-crt/PKGBUILD
- mingw-w64-cross-ucrt-headers/PKGBUILD
remove some leftovers from various packages. As far as I see this was never finished. Also it's unlikely we'll target armv7 in the future.
> Remove incomplete GCC support for armv7-w64-mingw32

- mingw-w64-cross-gcc/PKGBUILD
This was causing x86_64 libgcc.a to fail to link on an i686 msys host, apparently due to strip messing up the non-native libraries.  See https://github.com/msys2/MSYS2-packages/pull/4168#issuecomment-1813274876
> mingw-w64-cross-gcc: disable stripping again

- libxml2/PKGBUILD
"Starting with this release, it should be enough to add the --with-legacy configuration option to provide maximum ABI compatibility."
So why not I guess
> libxml2: Update to 2.12.0

- msys2-runtime/0039-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/0040-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/PKGBUILD
This commit corresponds to https://github.com/msys2/msys2-runtime/pull/179 and should fix https://github.com/msys2/MSYS2-packages/issues/2282 and maybe even https://github.com/microsoft/vcpkg/pull/34274.
> msys2-runtime: avoid "Bad address" errors in the MSYS2 path conversion

- binutils/PKGBUILD
it defaults to the internal one by default
Fixes #4218
> binutils: make sure to use the system zlib

- pacman-mirrors/PKGBUILD
- pacman-mirrors/mirrorlist.mingw
- pacman-mirrors/mirrorlist.msys
mirror2.sandyriver.net: gone
repo.casualgamer.ca: gone
fastmirror.pp.ua: move to tier one
mirrors.tencent.com: better URL, see https://github.com/msys2/msys2.github.io/issues/297
> pacman-mirrors: Update to 20231208

- msys2-runtime/0039-path-conversion-Introduce-ability-to-switch-off-conv.patch
- msys2-runtime/0040-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/0041-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/0042-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/0043-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/0044-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/0045-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/0046-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/0047-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
- msys2-runtime/0048-Handle-8-bit-characters-under-LOCALE-C.patch
- msys2-runtime/PKGBUILD
This combines the patches introduced via
https://github.com/msys2/msys2-runtime/pull/181 and https://github.com/msys2/msys2-runtime/pull/182.
> msys2-runtime: backport Git for Windows' pathconv improvements

- man-db/PKGBUILD
This seems to have gotten the same configure check as tar in #4078.
> man-db: disable check for year 2038 support on 32-bit.

- ccache/PKGBUILD
Running check, CCACHE segfaults in the first test, then hangs in the second.  This needs to be fixed.
> ccache(4.8.3): add function CHECK (check segfaults and hangs)

- ccache/0001-fix-blake3-segfault.patch
- ccache/PKGBUILD
Note: this package is still broken
* Remove cmake option that no longer exists
* Fix blake3 using the wrong asm for the platform and crashing
See #4311
> ccache: Update to 4.9 + fix crash (still broken)

- libxml2/PKGBUILD
Also disable the legacy APIs, like we did for the mingw build recently There shouldn't be any users left.
> libxml2: Update to 2.12.4

- libinih/PKGBUILD
as pointed out at
https://github.com/msys2/MSYS2-packages/commit/f0b92831254aca8334858cb863a1306feaf7e91c#commitcomment-137495120
> libinih: backport patch to fix wrong version

- binutils/0100-binutils-2.37-msys2.patch
- binutils/PKGBUILD
* Remove backport which is included in the new release
* 0100-binutils-2.37-msys2.patch: simple refresh
> binutils: Update to 2.42

- xz/PKGBUILD
It was inheriting them from pkgbase, but it's only depending
on the runtime and nothing more.
> xz: remove unneeded dependencies

- msys2-w32api-headers/0001-Work-around-Warray-bounds-warning-for-__readfsdword-.patch
- msys2-w32api-headers/PKGBUILD
In msys2/msys2-runtime@ae5462a53b (CI: fix the build with gcc 13, 2023-11-10), we worked around build errors that look like this:
```
In member function ‘virtual ssize_t fhandler_console::write(const void*, size_t)’:
cc1plus: note: source object is likely at address zero
In function ‘long long unsigned int __readgsqword(unsigned int)’,
inlined from ‘_TEB* NtCurrentTeb()’ at /usr/include/w32api/winnt.h:10013:86,
inlined from ‘tmp_pathbuf::~tmp_pathbuf()’ at winsup/cygwin/local_includes/tls_pbuf.h:21:5,
inlined from ‘virtual ssize_t fhandler_console::write(const void*, size_t)’ at winsup/cygwin/fhandler/console.cc:4047:1:
/usr/include/w32api/psdk_inc/intrin-impl.h:838:1: warning: array subscript 0 is outside array bounds of ‘long long unsig
ned int [0]’ [-Warray-bounds=]
838 | …
```
> msys2-w32api-headers: work around `__buildreadseg` errors

- msys2-runtime-3.3/0057-Move-_cygheap_start-into-.cygheap-section.patch
- msys2-runtime-3.3/0058-Cygwin-dumper-also-link-with-libzstd-as-libbfd-may-r.patch
- msys2-runtime-3.3/0059-Cygwin-configure-Add-option-to-disable-building-dump.patch
- msys2-runtime-3.3/0060-Work-around-fragile-include-in-binutils.patch
- msys2-runtime-3.3/PKGBUILD
On i686, an additional warning showed up that failed the build.  This adds this warning to the CFLAGS/CXXFLAGS exclusions.
```
/t/r/msys2-runtime-3.3/src/msys2-runtime/winsup/cygwin/fhandler_proc.cc: In function 'off_t format_proc_swaps(void*, char*&)': /t/r/msys2-runtime-3.3/src/msys2-runtime/winsup/cygwin/fhandler_proc.cc:1964:43: error: '%s' directive writing 4 bytes into a region of size between 1 and 2147483606 [-Werror=format-overflow=]
1964 |           bufptr += sprintf (bufptr, "%s%s%s\t\t%llu%s\t%llu%s\t%d\n",
|                                           ^~
......
1967 |                                         "file",
|                                         ~~~~~~
/t/r/msys2-runtime-3.3/src/msys2-runtime/winsup/cygwin/fhandler_proc.cc:1964:38: note: directive argument in the …
```
> msys2-runtime-3.3: add -Wno-error for additional warning on i686 build

- msys2-runtime/0050-pathconv-don-t-skip-arguments-with-double-quote.patch
- msys2-runtime/0051-Work-around-fragile-include-in-binutils.patch
- msys2-runtime/0052-Cygwin-try-to-avoid-recalling-offline-files.patch
- msys2-runtime/0053-Cygwin-get-set-security-descriptors-using-FILE_OPEN_.patch
- msys2-runtime/PKGBUILD
With this change, files are no longer "hydrated" (read: downloaded on the fly) when calling `ls` _just_ to determine whether the files in question have a `#!` line that makes them executable.
This commit brings the changes from
https://github.com/msys2/msys2-runtime/pull/209 to MSYS2-packages.
> msys2-runtime: support OneDrive better

- xz/PKGBUILD
Run autogen to get the documentation built instead of just autoreconf Also needs extra build depends for things already included in the tarball.
And remove the signing key from the bad actor.
> xz: Switch from upstream tarball to git tarball

- msys2-runtime/0054-Cygwin-FILE_OPEN_NO_RECALL-is-incompatible-with-FILE.patch
- msys2-runtime/PKGBUILD
This integrates https://github.com/msys2/msys2-runtime/pull/210 into MSYS2-packages.
> msys2-runtime: backport follow-up fix for offline files

- pacman/PKGBUILD
- pacman/makepkg.conf
- pacman/makepkg_mingw.conf
It probably doesn't do anything and breaks Flang 18 when it is being called as a linker.
See https://github.com/msys2/MINGW-packages/pull/20591.
> pacman: remove `-pipe` from default `LDFLAGS` for all environments

- msys2-runtime/PKGBUILD
- msys2-runtime/msys2-runtime.install
Cygwin 3.5 no longer supports Windows 7 and 8.0 and letting users update would render all cygwin tools broken.
There is no good way to abort an installation from within a package, so we run an install script on pre install/upgrade and just kill pacman from there, after printing a message for how to fix things. Since killing pacman would leave the DB locked, remove the lock file before, so the suggested way forward works.
While we don't officially support Win 7/8.0 for quite a while now, this should help those remaining users keep using the parts that still work for a bit longer.
> msys2-runtime: abort installation on Windows 7 and 8.0

- msys2-runtime-3.4/PKGBUILD
- msys2-runtime/PKGBUILD
Replicate the objcopy commands that used to work in msys2-runtime build process.
also, don't strip msys2-runtime-devel.  makepkg's strip mechanism thinks split debug files are binaries that need to be stripped, and debug files with the debug info stripped are pretty useless.  msys2/msys2-pacman#52
Fixes #4595
> msys2-runtime{,3.4}: restore msys-2.0.dbg

- gpgme/0002-gpgme-engine-cache-version.patch
- gpgme/PKGBUILD
See https://github.com/msys2/msys2-pacman/issues/26
See https://dev.gnupg.org/T6369
This saves a gpg spawn for every gpgme_get_key() call, for example around 100ms when starting pacman.
> gpgme: cache the engine version

- wget/PKGBUILD
wget 1's configure script only checks for and uses gpgme if metalink is enabled.  After b9f35e17d62e94d5ef3df3d9ece3b3aaff5f68ad, metalink is explicitly disabled, so gpgme was no longer used.
> wget: don't depend on gpgme

- python-pyalpm/PKGBUILD
The pyalpm dll is dynamically linked to msys-gpgme-11.dll, and now that wget will not depend on libgpgme it shouldn't be pulled into the base packages anymore.
> python-pyalpm: depend on libgpgme

- .ci/ci-build.sh
The find expression was broken for a couple of reasons: it does not run in a subshell (so cannot use && like that), and it needs split arguments not one quoted argument.  Avoid having to call echo by using -printf argument.
Fixes #4611
> CI: fix dll dependency check

- filesystem/PKGBUILD
- filesystem/msys2_shell.cmd
follow-up to 489a8aacde7ff649c77874838bf4e6a79d436e15, I suggest this to be included with another filesystem update (and therefore did not the PKGCONFIG)
> filesystem/msys2_shell: help update (clang32/clangarm64)

- openssl/PKGBUILD
Should probably be in the other targets as well
I don't have the build tools installed so I am not certain of the change but it should be close
> Fixes #4640 openssl legacy provider missing

- findutils/PKGBUILD
As found in #4078, 32-bit cygwin only has 32-bit time_t.
> findutils: disable year 2038 check on 32-bit

- pinentry/1.1.0-w32.patch
- pinentry/PKGBUILD
* 1.1.0-w32.patch: removed hunks included in the release
* disable fltk, since that confused by a bit when the w32 patch wasn't applied locally. It would try to fall back to fltk otherwise.
> pinentry: Update to 1.3.0

- psmisc/0000-fix-build.patch
- psmisc/PKGBUILD
* disable statx since we don't have it and fix the build despite that
* remove the ncurses hack, seems to work fine without
> psmisc: Update to 23.7

- icu/PKGBUILD
This probably only matters for i686, which is stuck on 3.3.6.
I don't know if the upstream pull request (unicode-org/icu#3038) will go anywhere or not, feels like the kind of org that makes you jump through a lot of hoops to contribute anything.
> icu: fix build with cygwin < 3.5.0

- python-markdown/PKGBUILD
> python-markdown: Add 3.6

- gcc/PKGBUILD
- gdb/PKGBUILD
- libtool/PKGBUILD
And add a note to gcc that this needs to happen on every version change
> Rebuild gdb and libtool for new gcc version

- breezy/0003-remove-unused-broken-import.patch
- breezy/PKGBUILD
imp no longer exists with Python 3.12. Luckily this was an unused import
> breezy: remove import for no longer existing module

- glib2/002-fix-build.patch
- glib2/PKGBUILD
* drop the docs package: it moved from gtk-doc to gi-docgen which requires introspection, but we don't have the tooling for that yet
* small patch to fix the build
* it moved from distutils to packaging for version parsing
* rst2man from python-docutils is now used for man pages
* move gobject-query to devel to match Debian
* move gresource from devel, to match Debian
* install man pages
* xslt seems to no longer be used
* install some missing binaries (gio, gio-launch-desktop)
* install missing gettext files
* add conflicts since files have moved
> glib2: Update to 2.80.3

- python/EXTERNALLY-MANAGED
- python/PKGBUILD
See https://peps.python.org/pep-0668/
Similar to what Arch does.
```console
$ pip install pip
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
python-xyz', where xyz is the package you are trying to
install.
If you wish to install a non-MSYS2-packaged Python package,
create a virtual environment using 'python -m venv path/to/venv'.
Then use path/to/venv/bin/python and path/to/venv/bin/pip.
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
> python: PEP 668 - mark as externally managed

- python/990-cygwin-default-to-spawn-for-multiprocessing-and-disa.patch
- python/PKGBUILD
"forkserver" doesn't work, and "fork" is deprecated, so give "spawn" a try See https://github.com/msys2/MSYS2-packages/pull/4743#issuecomment-2213043559
> python: switch default mp start method to "spawn" and disable "forkserver"

- msys2-runtime-3.4/0052-Cygwin-try-to-avoid-recalling-offline-files.patch
- msys2-runtime-3.4/0053-Cygwin-get-set-security-descriptors-using-FILE_OPEN_.patch
- msys2-runtime-3.4/0054-Cygwin-FILE_OPEN_NO_RECALL-is-incompatible-with-FILE.patch
- msys2-runtime-3.4/0055-Cygwin-console-Fix-exit-code-for-non-cygwin-process.patch
- msys2-runtime-3.4/0056-Cygwin-console-Avoid-slipping-past-disable_master_th.patch
- msys2-runtime-3.4/0057-Cygwin-pty-Fix-handle-leak-in-master-process.patch
- msys2-runtime-3.4/0058-Cygwin-pty-Fix-potential-handle-leak-regarding-CallN.patch
- msys2-runtime-3.4/0059-Cygwin-console-Make-VMIN-and-VTIME-work.patch
- msys2-runtime-3.4/0060-Cygwin-pipe-Give-up-to-use-query_hdl-for-non-cygwin-.patch
- msys2-runtime-3.4/0061-Avoid-sharing-cygheaps-across-Cygwin-versions.patch
- msys2-runtime-3.4/0062-uname-report-msys2-runtime-commit-hash-too.patch
- msys2-runtime-3.4/0063-Cygwin-suppress-a-warning-generated-with-w32api-12.0.patch
- msys2-runtime-3.4/PKGBUILD
- msys2-runtime-3.4/update-patches.sh
Seems that we haven't updated this package in a while...
NOTE: There seems to be [a compile error](https://github.com/msys2/msys2-runtime/actions/runs/9835525686/job/27149328693#step:4:1495) that I still need to look into, hence the draft status of this PR.
> msys2-runtime-3.4: synchronize with the `msys2-runtime-3.4.10` branch in the `msys2-runtime` repository

- msys2-runtime/0040-Avoid-sharing-cygheaps-across-Cygwin-versions.patch
- msys2-runtime/0041-uname-report-msys2-runtime-commit-hash-too.patch
- msys2-runtime/PKGBUILD
- msys2-runtime/update-patches.sh
This corresponds to https://github.com/msys2/msys2-runtime/pull/219.
> Prevent different msys2 runtime versions from sharing cygheaps (targeting msys2-runtime v3.5)

- automake1.17/PKGBUILD
- automake1.17/automake-1.17-documentation.patch
- automake1.17/automake-1.17-msys2.patch
- autotools-wrappers/PKGBUILD
This package is based on automake1.16
Difference between automake1.17 and 1.16
- Rename `README.am17` to `README.am1.17`
- Add more `checkdepends`
If you're not satisfied with any changes I've made, feel free to leave feedback.
> automake1.17: new package

- mingw-w64-cross-zlib/PKGBUILD
So we don't have to install for every host
* split the package up for each host
* add a mingw-w64-cross-zlib package that depends on all of them for backwards compat
* conflict against old version to avoid file conflicts during upgrades
> mingw-w64-cross-zlib: convert to split package

- fish/PKGBUILD
There are a number of very old dependencies listed here, which should be able to be removed without any change in the function of the final binary.
> fish PKGBUILD: remove ancient dependencies

- gnutls/PKGBUILD
the weak symbol check has been updated, so remove the workaround
> gnutls: Update to 3.8.7

- mercurial/PKGBUILD
pgp key see: https://lists.mercurial-scm.org/pipermail/mercurial-packaging/2024-August/000737.html
Fixes https://github.com/msys2/MSYS2-packages/issues/4836
> mercurial: Update to 6.8.1

- msys2-w32api-headers/PKGBUILD
- msys2-w32api-runtime/PKGBUILD
Instead depend on only the cross compiler that is needed.
> msys2-w32api: remove dependency on mingw-w64-cross-gcc

- mingw-w64-cross-binutils/PKGBUILD
and move all conflicting files into a "common" package, similar to what Fedora does
> mingw-w64-cross-binutils: split up

- mc/0003-vfs-win32-absolute-paths.patch
- mc/PKGBUILD
Updated mc to version 4..8.32, including updated absolute-paths patch to account for added preprocessor directives.
Also worked around existing issue where mc gets built without version info (verifiable with a `mc --version` or by looking at its F1 help dialog.  There's a versioning script that depends on some magic from the mc git repository, so I added a replacement to force the downloaded package version on it.  If there's a better way to get that info from PKGBUILD to the build process, do let me know.
> mc: update to 4.8.32 and fix version bug

- mingw-w64-cross-headers/PKGBUILD
default to ucrt/win10 like we do for clangarm64
> mingw-w64-cross-headers: add aarch64 variant

- mingw-w64-cross-mingwarm64-headers/PKGBUILD
We need to use the fork, so we can either backport patches, or keep things simple and use a different source for the mingwarm64 variant, which this tries to do.
> mingw-w64-cross-headers: split out mingwarm64

- libssh/PKGBUILD
Patch applied upstream and no longer needed here.
> libssh: update to 0.11.1

- ncurses/PKGBUILD
- openssl/PKGBUILD
new domain and new signing key (see https://openssl-library.org/source/index.html) and sources are now only hosted on github
> openssl: Update to 3.3.2

- winpty/PKGBUILD
and remove an outdated comment, the -git variants are gone
> winpty: makedep only on the needed cross compiler

- ncurses/PKGBUILD
Update to the current dev version, as the last stable release was already two years ago.
This patch set includes a patch to enable the term-driver support for the Win32 console with TERM='#win32con' on the Cygwin runtime, like it does for MinGW, which does not require a terminfo database.
This does not change the regular terminfo-based functionality of ncurses otherwise.
You can verify that this works by running an ncurses program with TERM='#win32con' in a Windows Terminal session or similar. For example this one:
https://github.com/mtoyoda/sl
.
> ncurses: update to 6.5-20240831,enable term-driver

- curl/PKGBUILD
- curl/curl-7.60.0-gssapi-static-libs.patch
Refresh the krb patch due to conflicts.
There was one case where it added libs to GSSAPI_INCS which seems weird, so I dropped it from the refresh.
> curl: Update to 8.10.0

- pacman/0032-Translate-MSYS2-specific-messages-into-Japanese.patch
- pacman/PKGBUILD
MSYS2-specific Japanese translations were removed in 1915a138c0796740f3eec33308d6d34644e78a86.
Restore them.
See: https://github.com/msys2/msys2-pacman/pull/53
> pacman: Restore ja translations

- cmake-bootstrap/PKGBUILD
This adds a bootstrapped cmake, which does not depend on external
libraries and can be used to build makedepends for the real cmake
package which uses external dependencies.
It's mainly useful for bootstrapping.
> Add cmake-bootstrap

- ncurses/PKGBUILD
It breaks colors with nano for some reason, see
https://github.com/msys2/MSYS2-packages/issues/4945
Fixes #4945
> ncurses: disable term-driver again to fix regressions

- libpcap/PKGBUILD
set PCAP_TYPE as suggested by the cmake build error
> libpcap: Update to 1.10.5

- nano-syntax-highlighting/001-nanorc.patch
- nano-syntax-highlighting/PKGBUILD
There is a mistake in the package ```nano-syntax-highlighting```, specifically at line 26 in the file ```/usr/share/nano-syntax-highlighting/nanorc.nanorc``` (brightnormal is not allowed as icolor).
This issue has been reported a few times upstream, and it is also cited on [arch wiki](https://wiki.archlinux.org/title/Nano#Syntax_highlighting), but maintainer seems to be unreachable (his last github activity was mid 2023).
Even though arch wiki says to replace 'brightnormal' with 'normal', it would redefine icolor normal, which
was defined a few lines above on that file. Instead, I decided to keep the original value defined earlier.
Then, I just commented that offending line.
1. Install the package ```nano-syntax-highlighting```:
```bash
pacman -S nano-syntax-highlighting
```
2. Open the …
> fix: nanorc.nanorc on nano-syntax-highlighting

- autoconf2.71/0004-LLVM-Flang.patch
- autoconf2.71/PKGBUILD
- autoconf2.72/0004-LLVM-Flang.patch
- autoconf2.72/PKGBUILD
This allows building more projects with LLVM Flang as the Fortran compiler without needing additional (obscure) configure flags.
Note of caution: I've never used Classic Flang. I don't know if it also defines `__flang__`. And if it does, I don't know if it can be considered as a "drop-in replacement" of gfortran (or other GNU Fortran compilers).
> autoconf: Treat Flang as GNU-compatible Fortran compiler.

- mingw-w64-cross-crt/PKGBUILD
- mingw-w64-cross-mingwarm64-crt/PKGBUILD
same as https://github.com/msys2/MINGW-packages/pull/22263 for the cross toolchain
> cross-crt: disable wildcard by default

- msys2-runtime/0041-Cygwin-find_fast_cwd-don-t-run-assembler-checking-co.patch
- msys2-runtime/PKGBUILD
includes https://github.com/msys2/msys2-runtime/pull/233
> msys2-runtime: update (arm64 canary crash fix backport)

- base-devel/PKGBUILD
It interferes with mingw-w64-pkgconf.
> base-devel: Remove pkgconf dependency.

- msys2-runtime/0045-Cygwin-revert-use-of-CancelSyncronousIo-on-wait_thre.patch
- msys2-runtime/PKGBUILD
This change seems to have caused hangs on x86_64, so let's revert it.
Addresses https://github.com/msys2/MSYS2-packages/issues/4340#issuecomment-2491401847 and corresponds to https://github.com/msys2/msys2-runtime/pull/243.
> msys2-runtime: revert use of CancelSyncronousIo on wait_thread

- filesystem/PKGBUILD
- filesystem/dot.bashrc
HISTCONTROL is a colon-separated list, NOT a comma-separated one
> filesystem: fix HISTCONTROL list separator

- msys2-runtime-3.3/0060-Cygwin-cache-IsWow64Process2-host-arch-in-wincap.patch
- msys2-runtime-3.3/0061-Cygwin-uname-add-host-machine-tag-to-sysname.patch
- msys2-runtime-3.3/PKGBUILD
- msys2-runtime/0046-Cygwin-cache-IsWow64Process2-host-arch-in-wincap.patch
- msys2-runtime/0047-Cygwin-uname-add-host-machine-tag-to-sysname.patch
- msys2-runtime/PKGBUILD
This backports the `uname` patches from Cygwin where Windows/ARM64 is indicated by an `-ARM64` suffix.
It corresponds to https://github.com/msys2/msys2-runtime/pull/245 and https://github.com/msys2/msys2-runtime/pull/244.
> msys2-runtime: uname: add host machine tag to sysname

- autoconf2.72/0006-fortran-mingw-libs.patch
- autoconf2.72/PKGBUILD
Stripping `-lmingwex` from the Fortran standard linker flags can lead to a situation where the first `-lmsvcrt` appears before the first `-lmingwex` for a library that consists of Fortran and C++ sources. That means that the linker picks some functions from the Windows CRT that should instead be picked from `libmingwex.a`.
It took quite some time to figure out that this is causing an odd behavior when calling `std::asin` with a complex double precision value with a real part larger than 1 in such a library.
See also: https://octave.discourse.group/t/6026/75
Also don't strip `-lmoldname` from these flags because there is no reason to do that as far as I can tell.
This essentially reverts the upstream changes from: https://lists.gnu.org/r/autoconf-patches/2021-09/msg00000.html
> autoconf2.72: Don't strip MinGW libraries from Fortran linker flags

- guile/0003-Fix-make-custom-port-in-case-encoding-is-f.patch
- guile/0004-libguile-scm.h-fix-BUILDING_LIBGUILE-for-Werror-unde.patch
- guile/PKGBUILD
guile 3.0.10 requires additional patch 0003 to enable readline support. Furthermore patch 0004 adds a minor fix.
> guile: fix issue #5079

- python-attrs/PKGBUILD
- python-certifi/PKGBUILD
- python-configobj/PKGBUILD
- python-hatchling/PKGBUILD
- python-markupsafe/PKGBUILD
- python-poetry-core/PKGBUILD
- python-pyparsing/PKGBUILD
- python-six/PKGBUILD
- python-urllib3/PKGBUILD
> Various Python package updates

- ccache/PKGBUILD
ccache's cmake files will turn on a "dev mode" if CI is set in the environment, turning on -Werror among other things.  This was causing the build on i686 to fail due to a warning with fmt 11.  We don't really want ccache's dev mode, so unset it explicitly.
> ccache: unset CI env variable before running cmake

- libedit/PKGBUILD
upstream prefixed all man pages, so there are no conflicts anymore
> libedit: Update to 20240808_3.1

- guile/0401-Narrow-parameter-of-logand-immediate-if-no-bits-used.patch
- guile/0402-Fix-fixpoint-needed-bits-computation-in-specialize-n.patch
- guile/0403-Fix-boxing-of-non-fixnum-negative-u64-values.patch
- guile/0404-Run-sigbits-fixpoint-based-on-use-def-graph-not-cfg.patch
- guile/PKGBUILD
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=71891 says the issue was fixed in aff9ac968840e9c86719fb613bd2ed3c39b9905c, but to avoid conflicts (which I don't know how to resolve, not knowing scheme), also pull in 5e6288c9304b60f1875a44808ee3858e3d6efc83
0dab58fc2a6ac6a8354439749d598f8c24f57ddd and
e45b70dcded37eb77e71ec30445b12040b6bb1b7.
I don't know if we want to do this or just wait for 3.0.11.
/cc @h-c-mueller
> guile: backport commits to fix 32-bit

- ruby/PKGBUILD
> ruby: Update to 3.3.7

- msys2-runtime/0046-fixup-Avoid-sharing-cygheaps-across-Cygwin-versions.patch
- msys2-runtime/0047-Revert-Cygwin-signal-Do-not-handle-signal-when-__SIG.patch
- msys2-runtime/0048-Cygwin-cygwait-Make-cygwait-reentrant.patch
- msys2-runtime/0049-Cygwin-signal-Do-not-handle-signal-when-__SIGFLUSHFA.patch
- msys2-runtime/0050-Cygwin-signal-Avoid-frequent-TLS-lock-unlock-for-SIG.patch
- msys2-runtime/PKGBUILD
> msys2-runtime: update with patches for hang issues.

- python/900-msysize.patch
- python/PKGBUILD
pip has recently started to compare wheel tags with system supported wheel tags, and as it turns out build tools just use sysconfig.get_platform() to generate a tag (in setuptools, wheel, packaging, etc) for non-official platforms. For official platforms they do various normalization steps and use other sources.
Since we can't really patch all those packages we need to provide a platform string that wont change between updates.
* Don't include the cygwin version in it anymore, since that can change on updates.
* Hardcode to "cygwin" since builing for cygwin can change the output of os.uname()
The later breaks detection of MSYS2 compared to cygwin, but ideally no one should depend on it, and we want to get rid of the differences there anyway.
Fixes #5143
> python: remove version from platform string and always use "cygwin"

- python/900-msysize.patch
- python/PKGBUILD
In a mingw shell it will call os.uname() which starts with MINGW.. resulting in bogus results. So just check for sys.platform which is always "cygwin".
See #5143
> python: fix sysconfig.get_platform when run in a mingw shell

- binutils/0100-binutils-2.37-msys2.patch
- binutils/2002-Allow-spaces-in-the-name-of-the-external-preprocesso.patch
- binutils/PKGBUILD
* 0100-binutils-2.37-msys2.patch: remove hunk for removed code
* 2002-Allow-spaces-in-the-name-of-the-external-preprocesso.patch: also revert followup cleanup
> binutils: Update to 2.44

- msys2-runtime/0045-fixup-Instead-of-creating-Cygwin-symlinks-use-deep-c.patch
- msys2-runtime/0046-fixup-Instead-of-creating-Cygwin-symlinks-use-deep-c.patch
- msys2-runtime/0047-fixup-Instead-of-creating-Cygwin-symlinks-use-deep-c.patch
- msys2-runtime/0048-fixup-Instead-of-creating-Cygwin-symlinks-use-deep-c.patch
- msys2-runtime/0049-fixup-Instead-of-creating-Cygwin-symlinks-use-deep-c.patch
- msys2-runtime/0050-fixup-Instead-of-creating-Cygwin-symlinks-use-deep-c.patch
- msys2-runtime/0051-fixup-Instead-of-creating-Cygwin-symlinks-use-deep-c.patch
- msys2-runtime/0052-amend-Instead-of-creating-Cygwin-symlinks-use-deep-c.patch
- msys2-runtime/PKGBUILD
> msys2-runtime: add deepcopy symlink improvements

- msys2-runtime-3.3/PKGBUILD
So there is an automated upgrade path and users don't have to manually switch to msys2-runtime-3.3.
> msys2-runtime-3.3: build as msys2-runtime on i686

- mintty/PKGBUILD
- mintty/minttyrc
instead of plain xterm. xterm-256color is the default on most modern systems, so give it a try.
Fixes #4973
> mintty: default to Term=xterm-256color

- gettext/PKGBUILD
- gettext/gettext-0.19.7-archive.patch
- gettext/gettext-0.22.5-gettext-runtime-gnulib-lib-localcharset-c.patch
- gettext/gettext-0.22.5-gettext-runtime-gnulib-lib-localename-h.patch
- gettext/gettext-0.22.5-gettext-runtime-gnulib-lib-localename-unsafe-c.patch
- gettext/gettext-0.22.5-gettext-runtime-intl-gnulib-lib-localcharset-c.patch
- gettext/gettext-0.22.5-gettext-runtime-intl-gnulib-lib-localename-h.patch
- gettext/gettext-0.22.5-gettext-runtime-intl-gnulib-lib-localename-unsafe-c.patch
- gettext/gettext-0.22.5-gettext-tools-gnulib-lib-localcharset-c.patch
- gettext/gettext-0.22.5-gettext-tools-gnulib-lib-localename-h.patch
- gettext/gettext-0.22.5-gettext-tools-gnulib-lib-localename-unsafe-c.patch
This update was born as an attempt to solve build issues for nano 8.3 ( [https://github.com/msys2/MSYS2-packages/pull/5110#issuecomment-2646155381](https://github.com/msys2/MSYS2-packages/pull/5110#issuecomment-2646155381) ).
Changes:
* All the added patches ( gettext-0.22.5-* ) came from Cygwin sources for gettext;
* The patches that were disabled ( gettext-0.22-gettext-* ) no longer applies for 0.22.5;
* The addition on ```gettext-0.19.7-archive.patch``` followed the idea from the last update.
> [!NOTE]
> 
> I have no experience with gettext at all (I was trying to solve build issues on nano 8.3), so someone skilled enough on it should run their tests
> gettext: update to 0.22.5

- util-linux/PKGBUILD
It needs the --disable-year2038 configure argument due to i686 Cygwin's 32-bit time_t.
Also, fallocate only builds for Cygwin 3.5+, and i686 is stuck on 3.3 forever.
> util-linux: fix build on i686

- pcre2/PKGBUILD
See https://github.com/PCRE2Project/pcre2/blob/c421b939e7e1e7caf8a3de89b86f8e3fa83317e4/SECURITY.md for the signing key change
> pcre2: Update to 10.45

- genromfs/PKGBUILD
The current package version is 0.5.7. This version number comes from a tag in the GitHub repository at commit [2bdc5f9](https://github.com/chexum/genromfs/commit/2bdc5f933f5aa1451252d36f10bd376992affe24) - a commit made in 2009. However, this tag was never released as a true package release and the commit has the label:
> Update to version 0.5.7 (not released)
Repology [reports](https://repology.org/project/genromfs/versions) that the vast majority of package distributions are shipping the 0.5.2 release, which is the most recent true release made in 2007.
One bug that was found with the 0.5.7 non-release is that the genromfs tool opens file handles without then closing them which eventually causes a "Too many open files" error. A patch has been submitted to fix the issue …
> genromfs: downgrade to 0.5.2 - the most recent true release

- enscript/PKGBUILD
GNU enscript is a somewhat lesser known package (It is a GNU package meant to replace the adobe enscript from the late 80s) that prints to PostScript ASCII files suitable for printing to a physical printer or to STDOUT. It seems to want to use lpr by default, so some patches might be required. The config file lets you specify if a physical printer or STDOUT should be delivered to. Or maybe patch out lpr usage. Or both? I'll let you make the call.
> enscript: new package

- msys2-runtime/0054-Cygwin-Adjust-CWD-magic-to-accommodate-for-the-lates.patch
- msys2-runtime/PKGBUILD
This is a companion of https://github.com/msys2/msys2-runtime/pull/264.
> msys2-runtime: adjust CWD magic to accommodate for the latest Windows previews

- libblake3/0001-use-windows-asm.patch
- libblake3/PKGBUILD
the first one made it crash when using asm, the later avoids it failing to link at build time
This fixes ccache segfaulting in some cases.
> libblake3: use windows asm under cygwin; disable avx512

- msys2-runtime/PKGBUILD
See https://github.com/msys2/msys2-runtime/pull/271
So we can build GIMP until we have an upstream fix
> msys2-runtime: backport pipe hang fix

- brotli/PKGBUILD
- c-ares/PKGBUILD
- doctest/PKGBUILD
- libpcap/PKGBUILD
- libssh/PKGBUILD
- msgpack-c/PKGBUILD
- re2c/PKGBUILD
- upx/PKGBUILD
- znc/PKGBUILD
To get some cmake 4.0 testing rebuild a few things, and while at it move those packages to ninja.
> cmake: move various packages to ninja; fixes for cmake 4

- openssh/PKGBUILD
I had to pull the last update, f97d8e521886b021d868 because it was no longer working with cygwin 3.5
> openssh: Update to 10.0p1 (v2)

- llvm/PKGBUILD
This allows building dynamic libraries, making the package *much* smaller.
> llvm: build with clang

- gdbm/0001-missing-include.patch
- gdbm/PKGBUILD
new key, as pointed out here:
https://www.gnu.org.ua/software/gdbm/download.html
> gdbm: Update to 1.25

- cygutils/PKGBUILD
- cygutils/cygutils-1.4.17-4.src.patch
- cygutils/lssparse-support-check.patch
Corresponds to Cygwin's 1.4.17-4.
Additional patch to not build lssparse if SEEK_HOLE is not defined in unistd.h, as it is not on runtime versions < 3.6.
Fixes #5311
> cygutils: update to 1.4.17.4

- mingw-w64-cross-gcc/0101-Cygwin-enable-libgccjit-not-just-for-MingW.patch
- mingw-w64-cross-gcc/0200-add-m-no-align-vector-insn-option-for-i386.patch
- mingw-w64-cross-gcc/PKGBUILD
Refreshes due to these upstream commits:
* https://github.com/gcc-mirror/gcc/commit/bd9c550acc42c5b04a61be3c8d981359b2093357
* https://github.com/gcc-mirror/gcc/commit/e22962538f64bb6e5ac87977ec8a5d86f4ef21cb
* https://github.com/gcc-mirror/gcc/commit/1f05dfc131c7996a85dd82b3300f7b5f93d4b1bd
enable libstdcxx-backtrace to match our mingw build
remove unused _targets var
> cross-gcc: Update to 15.1.0

- mingw-w64-cross-mingwarm64-gcc/PKGBUILD
the upstream fork now contains the cygwin patches, so uncomment them for now.
enable libstdcxx-backtrace to match the other gcc cross compilers
> cross-mingwarm64-gcc: Update

- emacs/PKGBUILD
It is implicitly disabled due to configure not finding libgccjit.h, and is not supported (and causes configure to fail) on 32-bit, so just disable it.
> emacs: explicitly disable native compilation

- rebase/PKGBUILD
- rebase/autorebase.bat
Technically, the installation path or the `%PATH%` environment variable could contain a space.
Since this is a simple wrapper script to launch dash with the actual rebase script, it must follow Windows convention and quote the arguments to avoid an issue if the batch directory (`%~dp0`) is a path that contains space.
> `autorebase.bat`: Add quotes to prevent space issues

- gnupg/PKGBUILD
This version [was tagged yesterday](https://github.com/gpg/gnupg/releases/tag/gnupg-2.4.8). There are [no news](https://gnupg.org/) about it as of time of writing, [not even in `gnupg-announce`](https://lists.gnupg.org/pipermail/gnupg-announce/2025q2/thread.html), but [the `NEWS` file](https://github.com/gpg/gnupg/blob/gnupg-2.4.8/NEWS#L1-L30) suggests that it is official.
> gnupg: update to v2.4.8

- pacman/PKGBUILD
- pacman/makepkg-mingw
- pacman/makepkg_mingw.conf
- pacman/makepkg_mingw.conf.d.clang64.conf
- pacman/makepkg_mingw.conf.d.clangarm64.conf
- pacman/makepkg_mingw.conf.d.mingw32.conf
- pacman/makepkg_mingw.conf.d.mingw64.conf
- pacman/makepkg_mingw.conf.d.ucrt64.conf
makepkg-mingw.conf will include /etc/makepkg_mingw.conf.d/${MSYSTEM,,}.conf, and makepkg-mingw will list these confs to populate MINGW_ARCH_ALLOWED
Addresses #5285 along with #5381
> pacman: make msystems pluggable

- less/PKGBUILD
Release notes (https://www.greenwoodsoftware.com/less/news.678.html):
Version 678 was released for beta testing on 2 May 2025, and was released for general use on 17 May 2025.
These are the differences between [version 668](https://www.greenwoodsoftware.com/less/news.668.html) and version 678:
-   Treat -r in LESS environment variable as -R.
-   Add ESC-j and ESC-k commands ([github #560](https://github.com/gwsw/less/issues/560)).
-   Add --no-paste option ([github #523](https://github.com/gwsw/less/issues/523)).
-   Add --no-edit-warn option ([github #513](https://github.com/gwsw/less/issues/513)).
-   Add --form-feed option ([github #496](https://github.com/gwsw/less/issues/496)).
-   Add ESC-b command ([github #615](https://github.com/gwsw/less/issues/615)).
-   Make TAB complete …
> less: upgrade to version 678

- mingw-w64-cross-clang-crt/PKGBUILD
- mingw-w64-cross-clang-headers/PKGBUILD
to match mingw-w64-cross-{crt,headers}
> mingw-w64-cross-clang-{crt,headers}: update to 2ca6f1348c

- pacman/PKGBUILD
- pacman/makepkg_mingw.d.clang64.conf
- pacman/makepkg_mingw.d.clangarm64.conf
currently there is an issue with `crt-static` option being uncontrollable for windows-gnu targets: https://github.com/rust-lang/rust/issues/137389. this behavour is bad because libunwind.dll is linked by default for windows-gnullvm, but no gcc dynamic libs are linked in case of windows-gnu. I tried to use bootstrap.toml option, but it doesn't do what is expected. this leads to confusion because there is a need to pull libunwind package separately for all rust-based packages...
this change should be temp before the issue is fixed. this flag can be changed in case of package which has cc-libs as their dependency anyway. didn't add the flag for GCC envs because nothing changes with it
I'll block some rust updates/additions before this is merged
> makepkg confs: apply +crt-static in RUSTFLAGS for CLANG*

- pacman-mirrors/PKGBUILD
- pacman-mirrors/mirrorlist.mingw
- pacman-mirrors/mirrorlist.msys
* move mirror.umd.edu down, as it is still flaky
* rename ftp.osuosl.org to the new ftp2.osuosl.org
* move ftp2.osuosl.org up as it is our best mirror
* move download.nus.edu.sg to tier 2 (we lost rsync some time ago)
* move repo.extreme-ix.org to tier 2 (too slow for tier 1)
> pacman-mirrors: Update to 20250607

- gcc/0101-Cygwin-enable-libgccjit-not-just-for-MingW.patch
- gcc/PKGBUILD
the removed change was fixed upstream via
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=1283b9f946eea07573be5ba0e0785c9e9279b3be
> gcc: Update to 13.4.0

- less/PKGBUILD
Release notes (from https://www.greenwoodsoftware.com/less/news.679.html):
Version 679 was released for beta testing on 29 May 2025, and was released for general use on 19 Jun 2025.
These are the differences between version 678 and version 679:
* Fix bad parsing of lesskey file an env var is a prefix of another env var (github gwsw/less#626).
* Fix unexpected exit using -K if a key press is received while ng the input file (github gwsw/less#628).
> less: upgrade to 679

- icu/PKGBUILD
- znc/PKGBUILD
* remove upstreamed patch
* new release key: https://github.com/unicode-org/icu/pull/3223
> icu: Update to 77.1

- ansible-core/PKGBUILD
- ansible/PKGBUILD
Upstream changed the name of the downloadable artifact from ansible-core-version.tar.gz to ansible_core-version.tar.gz, so a bit of character juggling is added to compensate for that.
Ansible 9.13.0 is the final release of the Ansible 9.x series, see https://forum.ansible.com/t/release-announcement-ansible-community-package-9-13-0/38866.
> ansible: update to 9.13.0 + ansible-core: update to 2.16.14

- joe/0001-fix-build.patch
- joe/PKGBUILD
My first MSYS2 package contribution.
> joe: Joe's own editor

- ansible/PKGBUILD
ansible implicitly depends on a certain version of ansible-core, so let's formalize this by adding the version to PKGBUILD.
> ansible: add version constraint on ansible-core

- u-boot-tools/PKGBUILD
noticed fdt_add_pubkey missing, added to PKGBUILD
> [u-boot-tools] add fdt_add_pubkey fix (fixes msys2#5673)
