ucl/000-msys2.patch
ucl/001-autoconf-compat.patch
ucl/002-missing-macros.patch
ucl/PKGBUILD
upx/PKGBUILD

I need upx for my recipes, but upx can also be used in makepkg's tidy phase.

new: ucl, upx

---

cscope/PKGBUILD
ctags/PKGBUILD
global/PKGBUILD
idutils/PKGBUILD
python-pygments/PKGBUILD

All seem to be working properly. ctags and global integration is not yet fully functional. I think it's due to issue #170.

Added exuberant ctags, cscope, idutils, python pygments, and gnu global.

---

repman-git/PKGBUILD

* Update to new BSD-licensed version.
* Format the source code.

repman: Update and format

---

global/PKGBUILD
markdown/PKGBUILD

Added package markdown, that converts text to markdown.

Added markdown.

---

markdown/PKGBUILD

Added markdown runtime dependencies on perl.

markdown: fix dependencies.

---

sharutils/PKGBUILD
sharutils/install

This package contains the `uuencode` and `uudecode` utilities.

New package sharutils

---

pacman/0005-Do-a-sanity-check-before-maniplating-final-DB-URL.patch
pacman/PKGBUILD

This makes Pacman work with repositories hosted e.g. by Bintray.

Sanity check database URL

---

perl-TAP-Harness-Archive/PKGBUILD
perl-YAML-Tiny/PKGBUILD

These are useful to create an archive of TAP test results.
Can be please also get binaries for these? :-)

Add the TAP-Harness-Archive and YAML-Tiny Perl packages

---

socat/PKGBUILD

socat: New package.

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.mingw32
pacman-mirrors/mirrorlist.mingw64
pacman-mirrors/mirrorlist.msys

Add futureware mirror

---

tmux-git/PKGBUILD
tmux-git/no-check-dirs-permission.patch

This patch belongs to issue #271.
(https://github.com/Alexpux/MSYS2-packages/issues/271)
It affects to only MSYS2 environment.

Modify "can't create socket" occurred

---

irssi-git/0000-msys2ize.patch
irssi-git/PKGBUILD

Basically I had the one correction of adding an 'r' to the pkg version, and then you requested I squash to just the initial commit.  I would have used the squash but it was two confusing showing others pull requests, so since this was my only contribution, I removed, re-forked, and sumbited again with just the initial commit, with the pkgver corrected of course.

Initial commit irssi-git

---

ssh-pageant-git/PKGBUILD
winpty-git/PKGBUILD

This is roughly based on winpty's PKGBUILD file.

Add a package for ssh-pageant

---

pkgconf/PKGBUILD

Thanks for all your work on msys2, it's really great!

update pkgconf to 0.9.11

---

xz-git/PKGBUILD
xz-git/xz-5.0.5-msys2.patch

Tested in Travis CI: https://travis-ci.org/fracting/xz/jobs/73484000#L3052

Add xz-git package.

---

ed/PKGBUILD

upgpkg: ed 1.12-1

---

python-mock/PKGBUILD

Add as checkdepend of newer setuptools and friends.

addpkg: python-mock 1.0.1-1

---

mercurial/PKGBUILD

upgpkg: mercurial 3.5-1

---

python-nose/PKGBUILD

upgpkg: python-nose 1.3.7-1

---

python-py/PKGBUILD

Add as dependency of pytest, which is a checkdepend of newer version of setuptools and friends.

addpkg: python-py 1.4.30-1

---

p7zip/PKGBUILD

Upstream new release. Also merged some changes in Arch Linux's PKGBUILD.

upgpkg: p7zip 9.38.1-1

---

python-pytest/PKGBUILD

Add as checkdepend of newer setuptools, py, and friends.

addpkg: python-pytest 2.7.2-1

---

xz-git/PKGBUILD

Built and tested on Travis CI: https://travis-ci.org/fracting/xz/jobs/73845661#L3037

xz-git: Add missing provides and conflicts fields.

---

git-flow/PKGBUILD

The "git flow" way to organize branches in a large team has gained some
popularity in the recent years. Let's package it for use with MSys2.
See http://nvie.com/posts/a-successful-git-branching-model/ for more
details about this branching model.

Add the git-flow package

---

pacman/makepkg_mingw32.conf
pacman/makepkg_mingw64.conf

Make it easier to compile with ASLR and DEP.

Provide hardening examples.

---

tmux-git/PKGBUILD
tmux-git/cwd-param-mod.patch

This fixes issue https://github.com/Alexpux/MSYS2-packages/issues/376

tmux-git: Fixed tmux fails to start

---

wcd/PKGBUILD

Hi,
I created a new PKGBUILD file for wcd.
regards,
Erwin

New package: wcd

---

scons/PKGBUILD
scons/scons-2.3.4-cyglink-msys2.patch

scons: fix wrong LIBSUFFIXES for msys.

---

.drone.yml
drone/build.sh

Also move irc notification from #msys2 to #msys2-ci as suggested by renatosilva  :)

Drone disable matrix build

---

ci-build.sh

Ok, this time should be fine.
Testing here: http://wine-ci.org/Alexpux/MSYS2-packages/25

Continuous Integration: Test package installaton after successful build.

---

ci-build.sh

This is a sync for https://github.com/Alexpux/MINGW-packages/pull/1064
Please commit, thanks!

Continuous Integration: Upgrade system before installing dependencies. Update package detection logic.

---

dos2unix/PKGBUILD

dos2unix: Update to 7.3.3

---

ci-build.sh

Colored output and source code refactoring.

Improvements for continuous integration

---

appveyor.yml
ci-build.sh

This is a sync of https://github.com/Alexpux/MINGW-packages/pull/1075, please merge, thanks!

CI: Update core packages before full system upgrade.

---

ttyrec/PKGBUILD

package for [ttyrec](http://0xcc.net/ttyrec/index.html.en)

ttyrec: New package

---

znc-git/PKGBUILD
znc-git/znc-configure-msys2.patch

made package for [znc](http://znc.in)
This will be useful to use this with irssi-git package.

znc-git: New package

---

screenfetch/PKGBUILD
screenfetch/msys2.patch
screenfetch/screenshot.patch

With specific patches for Msys2 and Windows.

new package: screenfetch

---

cscope/PKGBUILD
global/PKGBUILD
python-pygments/PKGBUILD

cscope: Update to 15.8b.
global: Update to 6.5.2.
python-pygments: Update to 2.1.1.

Update cscope, global and python-pygments.

---

.drone.yml

fracting/msys32 will be deprecated.

CI: Switch image to teaci/msys32.

---

ruby/PKGBUILD

Increase release version for ruby

---

filesystem/mingw32_shell.bat
filesystem/mingw64_shell.bat
filesystem/msys2_shell.bat

Remove unused part of .bat files

Remove Win9x support from .bat files

---

msys2-installer/compress-msys2
msys2-installer/make-msys2-installer
msys2-installer/qt-ifw/packages/com.msys2.root.base/meta/installscript.js

Fixed shortcuts in start menu and added new files

---

.gitignore

* Ignore ASCII signatures
* Ignore log files

Update git ignore list

---

mutt/PKGBUILD

Updated to new upstream version

Update Mutt to 1.6.0

---

gradle/PKGBUILD

Gradle updated to version 2.12

---

easyoptions-git/PKGBUILD
repman-git/PKGBUILD

* Update repman to latest version.
* Some recipe adjustments.

Update repman and some adjustments

---

quilt/PKGBUILD

Quilt patch manager from Debian packaging.

New package Quilt

---

openssl/PKGBUILD

openssl: new version

---

python-py/PKGBUILD

Update to latest version and specify python path so we use the right
version.

python-py: 1.4.31 - update to latest version

---

python-pygments/PKGBUILD

python-pygments - 2.1.3 - update to latest version

python-pygments - 2.1.3 - update to latest version

---

scons/PKGBUILD

scons - 2.5.0 - update to new version

scons - 2.5.0 - update to new version

---

colordiff/001-colorize-filenames.patch
colordiff/002-build-fix.patch
colordiff/PKGBUILD
colormake-git/PKGBUILD
colormake-git/colormake.install

* Colordiff colorizes output of diff and related tools.
* ColorMake colorizes output of make, gcc and similar.

Some colorizing tools

---

xmlto/PKGBUILD

xmlto: 0.0.28 - update to latest version

xmlto: 0.0.28 - update to latest version

---

cmake/3.5.2-case-sensitivity.patch
cmake/3.5.2-cpuinfo.patch
cmake/3.5.2-cygwin-paths.patch
cmake/PKGBUILD
cmake/cmake-3.5.2-msys.patch
cmake/disable-curses-for-msys.patch
cmake/disable-response-files-for-msys.patch

Attempt to make a better patch

Cmake 3.5.2

---

libssh2/PKGBUILD
msys2-launcher-git/PKGBUILD

Update to latest version and add validpgpkeys

Libssh2: 1.7.0 Update to latest version

---

ci-build.sh
ci-library.sh

Fix saneman installation and update, see Alexpux/MINGW-packages#1504.

Fixes for continuous integration

---

filesystem/PKGBUILD
filesystem/profile
filesystem/shell

* Avoid continuously appending items to MANPATH and INFOPATH.
* Check for .bashrc existence in shell manager.

Some improvements to filesystem

---

nano/PKGBUILD

Nano 2.6.0 - Update to latest version

---

grml-zsh-config/PKGBUILD
txt2tags/PKGBUILD

easy installation for a powerful zsh config

grml-zsh-config

---

fish/PKGBUILD

* fix dendency
- change the dependency on `doxygen` to `makedepends`
- add optional dependency on `python`
* move system configuration dir: `/usr/etc/fish` => `/etc/fish`

fish: Update to 2.3.1

---

git-flow/PKGBUILD

update git-flow package to use stable version 1.10.1

---

emacs/PKGBUILD
emacs/configure.ac.diff

emacs for msys without x tool kit

emacs for msys without x tool kit

---

file/PKGBUILD
file/fix-missing-parenthesis.patch

Please wait until I check the results of CI.

Fix file-5.28 build fail

---

re2c/PKGBUILD

new package for for building some libraries in mingw such as ninja.

re2c - 0.16 - New Package

---

ncurses/PKGBUILD

Untested fix for https://github.com/Alexpux/MSYS2-packages/issues/444 .

ncurses: fix typo

---

docbook-dsssl/PKGBUILD
docbook-dsssl/docbook-dsssl.install
docbook-dsssl/docbook-style-dsssl.Makefile
docbook-mathml/LICENSE
docbook-mathml/PKGBUILD
docbook-mathml/docbook-mathml.install
docbook-sgml/PKGBUILD
docbook-sgml/docbook-sgml.install
docbook-sgml31/PKGBUILD
docbook-sgml31/docbook-sgml31.install
sgml-common/PKGBUILD
sgml-common/sgml-common-0.6.3-manpage-1.patch
sgml-common/sgml-common.install

docbook-dsssl - 1.79 - New Package
docbook-mathml - 1.1CR1 - New Package
docbook-sgml - 4.5 - New Package
docbook-sgml31 - 3.1 - New Package (legacy version)
sgml-common - 0.63 - New Package

Docbook additonal stuff to complement mingw-w64- versions.

---

xz/PKGBUILD

* Update to 5.2.3
* Add validpgpkeys

xz: Update to 5.2.3

---

curl/PKGBUILD

* Update to 7.52.1
* Update validpgpkeys

curl: Update to 7.52.1

---

grep/PKGBUILD

* Update to 2.27
* add Jim Meyering pgp key

grep: Update to 2.27

---

nano-syntax-highlighting-git/PKGBUILD
nano-syntax-highlighting-git/nanorc.sample

* r115 --> r275
* add new syntax's to sample conf.

nano-syntax-highlighting-git: bump to 275.d2d84b8

---

mercurial/PKGBUILD

4 was not major update, regular bug-fixes and just new bundled hgext in this update from 3.7 series.

Mercurial: Update to 4.0.1

---

flex/PKGBUILD

Upstream releases changed to lz format

flex: Update to 2.6.3

---

m4/PKGBUILD
m4/m4-1.4.18-msys2.patch

I missed update the patch file in #780, this PR fixes it.

m4: Update patch

---

curl/PKGBUILD

cURL: update to v7.53.0

---

file/PKGBUILD
nano/PKGBUILD

file 5.30 - Update to altest version

nano 1.75 - enable UTF8 latest version

---

curl/PKGBUILD

cURL: bump to v7.53.1

---

bzr/0003-bzr-lazy-regex.patch
bzr/PKGBUILD

Fixes https://github.com/Alexpux/MSYS2-packages/issues/826

bzr: fix issue with python 2.7.12

---

mingw-w64-cross-crt-git/PKGBUILD
mingw-w64-cross-headers-git/PKGBUILD
mingw-w64-cross-tools-git/PKGBUILD
mingw-w64-cross-winpthreads-git/PKGBUILD
mingw-w64-cross-winstorecompat-git/PKGBUILD
msys2-w32api-headers/PKGBUILD
msys2-w32api-runtime/PKGBUILD

after: https://sourceforge.net/blog/small-but-significant-changes-to-project-pages/

switch to secure Git/SVN checkouts with sf.net

---

upx/PKGBUILD

UPX has updated to 3.93

---

filesystem/PKGBUILD
filesystem/msys2_shell.cmd

* Removed unused parameter "-consolez"
* Added "-no-start" parameter to get command execution result. Useful with "-defterm" parameter.

Update of msys2_shell.cmd

---

curl/PKGBUILD

curl: update to v7.54.0

---

openbsd-netcat/PKGBUILD
openbsd-netcat/openbsd-netcat.patch

Sorry for my so many tries. ><
I love using openbsd-netcat more than gnu-netcat because it's more powerful.
So I try a day to make it complied on msys2!
Hope it can be merged!

Add openbsd-netcat

---

nasm/PKGBUILD

related: https://github.com/Alexpux/MINGW-packages/pull/2511

nasm: update to 2.13.01

---

msys2-w32api-headers/PKGBUILD
msys2-w32api-runtime/PKGBUILD

w32api-runtime - Update to latest version

w32api-headers - update to latest version

---

dtc/PKGBUILD
dtc/fpic.patch

This patch adds a package description for the device tree compiler
Signed-off-by: Andy Gross <andy.gross@linaro.org>

Add device tree compiler

---

git/PKGBUILD
git/git-1.8.4-msys2.patch
git/git-2.8.2-Cygwin-Allow-DOS-paths.patch

* Fix conflicts.
* Disable JIT in PCRE.
Closes #974.

git: Update to 2.14.1

---

curl/PKGBUILD
jansson/PKGBUILD
jansson/jansson-2.10-msys2.patch
libnghttp2/PKGBUILD
libnghttp2/nghttp2-1.24.0-msys2.patch
libssh2/PKGBUILD

…h nghttp2
jansson - 2.10 - Add package for libnghttp2
libnghttp2 - 1.24.0 - add so curl can support HTTP/2
libssh - 1.80 - Update to altest version

curl - 7.55.1 - Update to latest version and add http2 support through nghttp2

---

msys2-runtime/0024-fix-strnstr-for-msys2-runtime.patch
msys2-runtime/PKGBUILD

revert changes in strnstr
in order to fix p11-kit

Msys2 runtime fix strnstr

---

openssl/PKGBUILD

add nasm as makedepend and build with asm

enable asm in openssl build

---

gradle/PKGBUILD

Updated gradle version from 4.1 to 4.2.

gradle: Update to 4.2

---

tig/PKGBUILD

tig: upgrade to 2.3.0

---

libffi-git/PKGBUILD

And add corresponding "provides"/"conflicts".

libffi-git: Add -git suffix to packages

---

filesystem/msys2_shell.cmd

Do this so the help docs are clearer.

Correct spelling in msys2_shell.cmd

---

autogen/PKGBUILD
autogen/autogen-5.18.12-allow-guile-2.2.patch
autogen/autogen-5.18.12-fix-guile-iface.patch
autogen/autogen-5.18.12-fix-guile-version-check.patch

This fixes autogen building with the current version of guile, 2.2.

autogen: fix build with guile-2.2

---

mintty/PKGBUILD

mintty: Update to 2.8.2

---

pacman/0008-answer-yes-by-default.patch
pacman/PKGBUILD

See #1141 and upstream PR in the main repo: https://github.com/Alexpux/MSYS2-pacman/pull/52
While the change seems trivial, pacman does not build for me right now, so I'm unable to test unfortunately.
The build log is attached.
[pacman-5.0.1-4-x86_64-prepare.log](https://github.com/Alexpux/MSYS2-packages/files/1713818/pacman-5.0.1-4-x86_64-prepare.log)
[pacman-5.0.1-4-x86_64-build.log](https://github.com/Alexpux/MSYS2-packages/files/1713817/pacman-5.0.1-4-x86_64-build.log)

pacman: change default answer of all queries to yes

---

quilt/PKGBUILD

Rebuild quilt to fix missing dll errors

---

gawk/PKGBUILD
gawk/fix-cr.patch

Fixes https://github.com/git-for-windows/git/issues/1524

Awk: Fix stripping of CR

---

man-db/PKGBUILD

Fix mandb setuid error

---

tmux/PKGBUILD
tmux/inherit-msystem-var.patch

tmux: Start shells of the same type as parent

---

libcrypt/PKGBUILD
libpsl/PKGBUILD
mksh/PKGBUILD
mpfr/PKGBUILD
mpfr/mpfr-4.0.0-add-ax_thread_m4.patch
publicsuffix-list/PKGBUILD
tzcode/PKGBUILD
tzcode/tzcode-fix-unknown-type-locale_t.patch
vifm/PKGBUILD

some fixes for tzcode, mksh, libpsl, mpfr, libcrypt
update vifm, publicsuffix-list.

some fixes and update.

---

cpio/PKGBUILD

I added new package: GNU Cpio.

Add GNU cpio

---

unrar/PKGBUILD

unrar: update to 5.6.4

---

README.md

Install msys2-devel to build packages

---

nano/PKGBUILD

nano: update to 2.9.7

---

vim/PKGBUILD

vim: update to 8.1.0022

---

filesystem/msys2_shell.cmd

Adds a loop collecting all command line arguments remaining after msys2_shell.cmd processing

Add support for more than 9 shell command line arguments

---

iperf/PKGBUILD

Add support for iperf network benchmarking tool

New package: iperf (network benchmarking tool)

---

iperf/PKGBUILD

iperf: Update to version 2.0.12

iperf: Update to version 2.0.12

---

iperf3/PKGBUILD

iperf3: update to 3.6

---

libuv/PKGBUILD

libuv: update to 1.22.0

---

isl/PKGBUILD

```
Testsuite summary for isl 0.19
```

isl: Update to 0.19

---

yelp-tools/PKGBUILD
yelp-xsl/PKGBUILD

yelp-tools: Update to 3.28.0
yelp-xsl: Update to 3.28.0

yelp tools: multiple updates

---

parallel/0001-support-MSys2.patch
parallel/PKGBUILD

- Update parallel to latest version
Build script:
- Check pgp signature file
- Use sha2 instead of sha1

parallel: update to 20180722

---

libuv/PKGBUILD

libuv: update to 1.23.0

---

unrar/PKGBUILD

unrar: update to 5.6.6

---

libuv/PKGBUILD

libuv: update to 1.23.1

---

fish/PKGBUILD
fish/config.fish
fish/msys2.fish
fish/perlbin.fish

I am not sure if I've made any mistakes in PKGBUILD, but these fish config files let you use fish as a login shell. Tagging @mashir43 for review. Fixes #1546

fish: update to 3.0.0-2

---

filesystem/05-home-dir.post

Minor fix, I'm guessing this was the original intention.

filesystem: minor fix

---

libuv/PKGBUILD

https://github.com/libuv/libuv/releases 1.27.0

libuv: upgrade to 1.27.0

---

pacman/PKGBUILD

(I get doxygen segfaults during the build locally.. calling make again makes the build finish at least, also with the old pacman)

pacman: Update to 5.1.3

---

zstd/PKGBUILD

New package: zstd v1.3.7
Zstandard - Fast real-time compression algorithm
https://facebook.github.io/zstd/

New package: zstd v1.3.8

---

mintty/PKGBUILD

move getemojis script to /usr/share/mintty/emojis/getemojis for consistancy with CygWin .

mintty - 2.3.0.6- - update to llatest version

---

pacman/PKGBUILD

Forgot to change the checksum of the edited pacman.conf in #1775. Should fix build errors.

Fix checksum in PKGBULD for pacman.conf

---

nawk/PKGBUILD
nawk/manpage-naming.patch

Add nawk package (version 20121220)

---

pacman/0011-update-ja-po-for-msys2.patch
pacman/PKGBUILD

`0000-pacman-msysize.patch` adds some translatable messages.
However those messages have not been translated. This PR translates them into Japanese.

pacman: Translate MSYS2 specific messages into Japanese

---

axel/PKGBUILD

Signed-off-by: Ismael Luceno <ismael@iodev.co.uk>

axel: Update to 2.17.7

---

lemon/PKGBUILD
lemon/lemon.c
lemon/lempar.c

Update to source in sqlite 3.31.1

lemon: Update to 3.31.1

---

btyacc/PKGBUILD
reflex/PKGBUILD

Standard packages which should not be missing from my point of view.

Add packages btyacc and reflex

---

.github/ISSUE_TEMPLATE/bug_report.md

I would like to improve the quality of this repository/software by asking the Issue Drafter to ensure reproducibility. Using template provided by GitHub.
See also:
- [Configuring issue templates for your repository](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)
What do you think about using this bug report template?
Please give me your comments.
Bug report template format is here:
```
A clear and concise description of what the bug is.
Steps to reproduce the behavior:
1. Run '...'
2. Do something '....'
3. Catch the error
A clear and concise description of what you expected to happen.
If applicable, add screenshots to help explain your problem.
- OS: [e.g. Windows 10 Pro version 1909 64bit]
- Pacman [e.g. Pacman v5.2.1 - …
```

[Proposal] Adding bug report template

---

zsh/PKGBUILD
zsh/zshrc

Reverts msys2/MSYS2-packages#1897

Revert "Set PROMPT in /etc/zsh/zshrc"

---

perl-PerlIO-gzip/PKGBUILD

New dependency required by lcov

perl-PerlIO-gzip: Add version 0.20

---

u-boot-tools/PKGBUILD

u-boot-tools: Update to v2020.04

---

vim/PKGBUILD

Merging this PR brings the package up to date.
Ref #1914

vim: Update to 8.2.0510

---

znc-git/PKGBUILD

and add icu dependency.
Should fix #1931.

znc-git: Update to r5233.efe64008

---

gnome-doc-utils/PKGBUILD
gnome-doc-utils/gnome-doc-utils-0.20.10-python3.patch
gnome-doc-utils/more-python3-fixes.patch

gnome-doc-utils: Port to Python 3

---

pacman/0000-pacman-msysize.patch
pacman/0005-Hack-gettext-libalpm-pkg-config-static-link.patch
pacman/0013-use-libintl.patch
pacman/0014-fix-asciidoc-argparse.patch
pacman/0015-excise-ldconfig.patch
pacman/0016-excise-fakeroot.patch
pacman/0017-excise-sudo.patch
pacman/0018-use-msys-tools.patch
pacman/PKGBUILD

Spent a bit of time on the meson build.  Currently I have this issue:
```
Checking for function "ngettext" : NO
```
I'll see if I can get further tomorrow.

pacman: Switch to meson

---

bash/PKGBUILD
ci-build.sh
filesystem/PKGBUILD
mintty/PKGBUILD
msys2-runtime/PKGBUILD
pacman-mirrors/PKGBUILD
pacman/PKGBUILD
pacman/makepkg.conf

PKGEXT in PKGBUILD wins over the value set in makepkg.conf
@Alexpux

Switch to zstd by default except for core packages

---

namcap/001-disable-some-things.patch
namcap/002-force-msys-python.patch
namcap/003-handle-no-source.patch
namcap/PKGBUILD
namcap/namcap.sh

This is similar to saneman in pactoys, but used by Arch and somewhat maintained.

Add namcap

---

tmux/PKGBUILD

tmux: Update to 3.1b

---

bison/PKGBUILD

Please note that I did not run checks, since they take a very very long time.  Again, would be great if CI could run `check` for selective packages.

bison: Update to 3.6.3

---

msys2-runtime/0025-popen-call-usr-bin-sh-instead-of-bin-sh.patch
msys2-runtime/PKGBUILD

See https://github.com/msys2/Cygwin/pull/7
Fixes #1998

msys2-runtime: Fix popen() in chroot

---

.github/workflows/main.yml
README.md

This is the same as msys2/MINGW-packages#6633, applied to this repo.

ci: add name to 'main' GHA workflow, update shields/badges

---

asciidoc/PKGBUILD

asciidoc: update to 9.0.1

---

icu/PKGBUILD

The old one resulted in an HTML page for me rather than the .tgz file.

icu: Update source URL.

---

libmetalink/PKGBUILD

Fix URL for libmetalink source.

---

msys2-runtime/0001-Add-MSYS2-triplet.patch
msys2-runtime/0002-Rename-dll-from-cygwin-to-msys.patch
msys2-runtime/0003-Add-functionality-for-converting-UNIX-paths-in-argum.patch
msys2-runtime/0004-Add-functionality-for-changing-OS-name-via-MSYSTEM-e.patch
msys2-runtime/0005-Move-root-to-usr.-Change-sorting-mount-points.-By-de.patch
msys2-runtime/0006-Do-not-create-cygwin-symlinks.-Instead-use-deep-copy.patch
msys2-runtime/0007-Automatically-rewrite-TERM-msys-to-TERM-cygwin-With-.patch
msys2-runtime/0008-Do-not-convert-environment-for-strace.patch
msys2-runtime/0009-Special-case-for-converting-root-directory-to-have-t.patch
msys2-runtime/0010-dcrt0.cc-Untangle-allow_glob-from-winshell.patch
msys2-runtime/0011-dcrt0.cc-globify-Don-t-quote-literal-strings-differe.patch
msys2-runtime/0012-strace.cc-Don-t-set-MSYS-noglob.patch
msys2-runtime/0013-Add-debugging-for-build_argv.patch
msys2-runtime/0014-Add-debugging-for-strace-make_command_line.patch
msys2-runtime/0015-environ.cc-New-facility-environment-variable-MSYS2_E.patch
msys2-runtime/0016-Fix-native-symbolic-link-spawn-passing-wrong-arg0.patch
msys2-runtime/0017-QueryUnbiasedInterruptTime-must-be-load-from-kernel3.patch
msys2-runtime/0018-fixup-Do-not-create-cygwin-symlinks.-Instead-use-dee.patch
msys2-runtime/0019-strace-quiet-be-really-quiet.patch
msys2-runtime/0020-Default-to-disable_pcon.patch
msys2-runtime/0021-Introduce-the-enable_pcon-value-for-MSYS.patch
msys2-runtime/0022-Don-t-create-WSL-symlinks-for-MSYS2.patch
msys2-runtime/0023-popen-call-usr-bin-sh-instead-of-bin-sh.patch
msys2-runtime/0024-CI-add-a-GHA-for-doing-a-basic-build-test.patch
msys2-runtime/0025-Set-up-a-GitHub-Action-to-keep-in-sync-with-Cygwin.patch
msys2-runtime/0026-recursiveCopy-Always-close-the-used-handle-with-Find.patch
msys2-runtime/PKGBUILD

msys2-runtime: Update patches

---

.github/workflows/main.yml

Accidentally copied this from mingw-packages.

Fix copy/paste typo

---

ci-build.sh

Had an epiphany the way I was doing it was unnecessarily complex.
https://github.com/msys2/MSYS2-packages/pull/2110#discussion_r471198129

CI: get rid of unnecessary subshells

---

perl-Pod-Parser/PKGBUILD

See e.g. https://github.com/darktable-org/darktable/issues/6009

perl-Pod-Parser: new package (removed from core)

---

libqrencode/PKGBUILD

* PKGBUILD:
- update to 4.1.0
- build in separate directory
- add check() function

qrencode: Update to 4.1.0

---

libiconv/PKGBUILD

Commented within patches.
Related issue: #2148

iconv: extra CPs, proper dependencies

---

lcov/001-mingw-lcov1.12-handle-equals-signs.patch
lcov/002-mingw-lcov1.12-fix-undef-behaviour.patch
lcov/PKGBUILD

Useful for creating coverage reports of mingw builds

Add lcov package

---

msys2-keyring/PKGBUILD

I extended my key's validity to 2021-10-02.

msys2-keyring: Update to 20201002

---

git/PKGBUILD

git: Update to 2.28.0

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.md
pacman-mirrors/mirrorlist.mingw32
pacman-mirrors/mirrorlist.mingw64
pacman-mirrors/mirrorlist.msys

This PR adds Clarkson University as a mirror and documents the others using a markdown file:
- Location
- Hosting Organization
- URLs
- Contact
Thanks to Clarkson University for hosting us :tada:

Add Clarkson University Mirror and Document Others

---

u-boot-tools/PKGBUILD

u-boot-tools: Update to v2020.10

---

ci-build.sh
ci-library.sh
meson/PKGBUILD

and a meson update on top to test it

CI: Sync CI scripts with the mingw repo

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.md
pacman-mirrors/mirrorlist.mingw32
pacman-mirrors/mirrorlist.mingw64
pacman-mirrors/mirrorlist.msys

This PR adds a mirror hosted by the NLUUG. Thanks NLUUG for your support! 🎉

Add NLUUG to mirror list

---

git/PKGBUILD
git/git-1.9.0-manifest-msys2.patch

Update git to 2.29.0

---

libssh/0001-Work-around-internal-compiler-error.patch
libssh/PKGBUILD
msgpack-c/PKGBUILD
tmate/0001-tmux-Inherit-MSYSTEM-variable.patch
tmate/0002-configure-handle-MSYS2.patch
tmate/0003-do-not-check-directory-permissions.patch
tmate/0004-Avoid-unsupported-GCC-option.patch
tmate/0005-Try-to-side-step-libevent-for-DNS-resolution.patch
tmate/PKGBUILD

https://tmate.io/ allows "instant terminal sharing". This PR brings the client to MSYS2.

Add support for `tmate`

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.md
pacman-mirrors/mirrorlist.mingw32
pacman-mirrors/mirrorlist.mingw64
pacman-mirrors/mirrorlist.msys

Thanks to the National University of Singapore and Oregon State University Open Source Lab for hosting :tada:

Add NUS and OSUOSL as mirrors

---

tmux/PKGBUILD

Update tmux to 3.1c

---

remake/PKGBUILD

remake: add -fcommon to CFLAGS

---

bash/PKGBUILD
filesystem/PKGBUILD
mintty/PKGBUILD
msys2-keyring/PKGBUILD
msys2-runtime/PKGBUILD
pacman-mirrors/PKGBUILD
pacman/PKGBUILD
zstd/PKGBUILD

It's been long enough and everyone should have a pacman that supports it

Use zstd for all packages now

---

mingw-w64-cross-clang/PKGBUILD
mingw-w64-cross-compiler-rt/PKGBUILD

Simple loop to build both x86_64 and i686 target libraries, as is done in -crt.  I have not actually looked at the resulting binaries.

mingw-w64-cross-compiler-rt and -clang i686

---

u-boot-tools/PKGBUILD

u-boot-tools: Update to v2021.01

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.md
pacman-mirrors/mirrorlist.mingw32
pacman-mirrors/mirrorlist.mingw64
pacman-mirrors/mirrorlist.msys

fastmirror.pp.ua
Speed: 100 Mbit/s
IPv4: 93.126.115.182
IPv6: 2a01:d0:fa02:5555:6829:17ff:fe25:da0c
http, https, rsync
Location: Ukraine, Kyiv

Add Ukrainian mirror

---

git/PKGBUILD

git: Update to 2.30.1

---

git/PKGBUILD

git: Update to 2.30.2

---

git/PKGBUILD

git: Update to 2.31.0

---

binutils/2002-Allow-spaces-in-the-name-of-the-external-preprocesso.patch
binutils/PKGBUILD
mintty/PKGBUILD

binutils: revert a windres commit

---

mintty/PKGBUILD

(will fail until staging is updated)

mintty: Update to 3.4.7

---

git/PKGBUILD

git: Update to 2.31.1

---

ncdu/PKGBUILD

Fixes https://github.com/msys2/MSYS2-packages/issues/1538

ncdu: Update to 1.15.1

---

u-boot-tools/PKGBUILD

u-boot-tools: Update to v2021.04

---

libtool/0014-Support-llvm-objdump-f-output.patch
libtool/PKGBUILD

More info in https://github.com/msys2/CLANG-packages/issues/9

libtool: support `llvm-objdump -f` output

---

libtool/0014-Support-llvm-objdump-f-output.patch
libtool/PKGBUILD

Details in msys2/MSYS2-packages#2431

libtool: fix recent patch

---

tmux/PKGBUILD
tmux/inherit-msystem-var.patch

tmux: Update to 3.2

---

curl/PKGBUILD

curl: upgrade to v7.76.1

---

gyp-git/0001-msys-ize.patch
gyp-git/PKGBUILD

it was mixing tabs/spaces in the patch which is no longer allowed

gyp: fix patch; pin commit

---

msys2-runtime/0031-CI-give-the-cygwin-sync-job-explicit-write-permissio.patch
msys2-runtime/0032-Cygwin-path_conv-Try-to-handle-native-symlinks-more-.patch
msys2-runtime/PKGBUILD

Reported here: https://cygwin.com/pipermail/cygwin/2021-April/248307.html

msys2-runtime: Backport fix for symlink resolving

---

msys2-runtime/0033-Cygwin-console-Fix-race-issue-regarding-cons_master_.patch
msys2-runtime/PKGBUILD

msys2-runtime: backport another fix for hanging pipes

---

pactoys-git/0001-pacboy-new-architectures.patch
pactoys-git/0002-disable-odd-msys2-check.patch
pactoys-git/PKGBUILD

With the advent of a host of new architectures in MSYS2 the PacBoy needs a refresh.

pactoys: support for new architectures in PacBoy

---

pacman/PKGBUILD

https://git.archlinux.org/pacman.git/log/

pacman: pull in some upstream fixes

---

tmux/PKGBUILD

tmux: Update to 3.2a

---

pacman/PKGBUILD
pacman/fix-sig-download-name.patch

See https://bugs.archlinux.org/task/71274 for details

pacman: fix DB signature not being found if the server redirects

---

msys2-runtime/0042-Fix-64-vs-32-bit-type-confusion-in-swprintf.patch
msys2-runtime/PKGBUILD

msys2-runtime: patch to fix ctrl-c handling

---

msys2-runtime/0044-getprocaddr-refactor-cleanup.patch
msys2-runtime/PKGBUILD

msys2-runtime: update patch for getprocaddr

---

msys2-runtime/0045-use-IsWow64Process2-to-detect-arm-cases.patch
msys2-runtime/PKGBUILD

msys2/msys2-runtime#47
Also fixed some tabs that slipped by on my last PR to this PKGBUILD.  🤦

msys2-runtime: update ctrl-c handling for ARM64.

---

pacman/PKGBUILD
pacman/pacman.conf

pacman: switch to the unified mingw mirror list 

---

u-boot-tools/PKGBUILD

u-boot-tools: Update to v2021.07

---

msys2-runtime/0046-Revert-Cygwin-Handle-virtual-drives-as-non-symlinks.patch
msys2-runtime/0047-Cygwin-respect-PC_SYM_FOLLOW-and-PC_SYM_NOFOLLOW_REP.patch
msys2-runtime/0048-Cygwin-make-option-for-native-inner-link-handling.patch
msys2-runtime/PKGBUILD

msys2-runtime: add patch for native inner links

---

git/PKGBUILD

git: Update to 2.33.0

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.mingw
pacman-mirrors/mirrorlist.msys

See https://github.com/msys2/msys2.github.io/issues/155

pacman-mirrors: add nju mirror

---

localepurge/PKGBUILD
localepurge/locale.nopurge
localepurge/localepurge.8.patch
localepurge/localepurge.config.patch
localepurge/localepurge.patch

Imported from Arch[1], with minor adaptations.
[1] https://aur.archlinux.org/packages/localepurge

Add localepurge package

---

curl/0001-Curl_http2_setup-do-not-change-connection-data-on-repeat-invokes.patch
curl/PKGBUILD

this affects pacman and also is backported in Arch

curl: backport a fix

---

git/PKGBUILD

git: Update to 2.33.1

---

u-boot-tools/PKGBUILD

u-boot-tools: Update to v2021.10

---

curl/PKGBUILD
curl/curl-7.60.0-gssapi-static-libs.patch
heimdal/1.5.3-missing-libs-pkg-config.patch
heimdal/7.7.0-fix-autoconf-2.71.patch
heimdal/PKGBUILD
pacman/PKGBUILD

heimdal: fix build; fix missing sqlite3 dep in .pc file

---

git/PKGBUILD

git: Update to 2.34.0

---

meson/9722.patch
meson/PKGBUILD

https://github.com/mesonbuild/meson/pull/9722

meson: fix static intl dep

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.mingw
pacman-mirrors/mirrorlist.msys

add new tier 1 mirror
move too slow mirror to tier 2

pacman-mirrors: Update

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.mingw
pacman-mirrors/mirrorlist.msys

See https://github.com/msys2/msys2.github.io/issues/171

pacman-mirrors: add mirrors.aliyun.com

---

m4/PKGBUILD
m4/gnulib-weak.patch

fix weak symbol check in gnulib

m4: rebuild

---

scons/PKGBUILD

scons: Remove from base-devel

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.mingw
pacman-mirrors/mirrorlist.msys

linked here https://github.com/msys2/MSYS2-packages/issues/2775#issuecomment-1002959867

pacman-mirrors: add mirror.iscas.ac.cn

---

texinfo/PKGBUILD
texinfo/texinfo-install.hook
texinfo/texinfo-remove.hook

It breaks when installing things into a different root :(
Fixes #2793

Revert "texinfo: run hooks in a fresh environment"

---

msys2-runtime/0043-posix_spawn-fix-get-set-uid-gid-calls-for-32-bit-Cyg.patch
msys2-runtime/PKGBUILD

msys2-runtime: backport for 32bit posix_spawn issue

---

u-boot-tools/PKGBUILD

u-boot-tools: Update to v2022.01

---

filesystem/PKGBUILD
filesystem/bash.bashrc

Clean up some code that spawns an external process unnecessarily.
This fixes https://github.com/git-for-windows/git/issues/3652

filesystem(bashrc): avoid spawning an external process

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.mingw
pacman-mirrors/mirrorlist.msys

pacman-mirrors: remove sourceforge

---

xmlto/0001-xmlto-convert-output-path-to-unix-path-on-cygwin-msy.patch
xmlto/PKGBUILD

Patch sent upstream for review:
https://pagure.io/xmlto/pull-request/10

xmlto: workaround -o argument handling with cygpath

---

expat/PKGBUILD

Signed-off-by: Christopher Degawa <ccom@randomderp.com>

expat: update to 2.4.6

---

expat/PKGBUILD

Signed-off-by: Christopher Degawa <ccom@randomderp.com>

expat: update to 2.4.7

---

python-pacdb/PKGBUILD

poetry conveniently created a setup.py in the source tar.gz

python-pacdb: add package

---

expat/PKGBUILD

Signed-off-by: Christopher Degawa <ccom@randomderp.com>

expat: update to 2.4.8

---

bison/PKGBUILD
diffutils/PKGBUILD
ed/PKGBUILD
file/PKGBUILD
gnutls/PKGBUILD
gperf/PKGBUILD
gpgme/PKGBUILD
groff/PKGBUILD
libarchive/PKGBUILD

Setting a var this way doesn't actually change it for expansion in the same line..

Fix cygwin build triplet hack - part 1

---

cygnative/.gitignore
cygnative/PKGBUILD

Source: https://github.com/davidecolombo/cygnative
Required for rsync+plink integration.

cygnative: new package

---

p11-kit/PKGBUILD

from what I see it isn't actually used/needed.

p11-kit: remove glib dependency

---

ncurses/PKGBUILD
ncurses/ncurses-6.3-cflags-private.patch
ncurses/ncurses-6.3-pkgconfig.patch

ncurses: pkg-config improvements

---

ca-certificates/PKGBUILD
ca-certificates/blacklist-dst-root-ca-x3.patch

ca-certificates: Update to 20211016

---

bash-completion/PKGBUILD
brotli/PKGBUILD
dash/PKGBUILD
findutils/PKGBUILD
gettext/PKGBUILD
libarchive/PKGBUILD

Some package rebuilds

---

msys2-runtime/0036-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
msys2-runtime/PKGBUILD

This corresponds to https://github.com/msys2/msys2-runtime/pull/95

msys2-runtime: stop trimming trailing colons

---

libiconv/1.16-wchar.patch
libiconv/PKGBUILD

libiconv: Update to 1.17

---

tmux/PKGBUILD

tmux: Update to 3.3a

---

expat/PKGBUILD
filesystem/PKGBUILD
libgcrypt/PKGBUILD
libgpg-error/PKGBUILD

to get all of base to include SHA256 checksums

Some more rebuilds

---

python-dulwich/PKGBUILD
python-pytest-runner/PKGBUILD
python-pytest/PKGBUILD
python-setuptools-scm/PKGBUILD
python-tomli/PKGBUILD
python-tomli/install_wheel.py

Some Python package updates

---

meson/0001-cygwin-disguise.patch
meson/PKGBUILD

that dropped patch was applied upstream

meson: Update 0.63.0

---

git/PKGBUILD

git: backport fix for staging removals with add -i

---

coreutils/PKGBUILD

and work around the gnulib weak symbol bug

coreutils: rebuild

---

mintty/001-default-size.patch
mintty/PKGBUILD

80x24 is too small for me (and maybe others?) and it's not that obvious
that you can change the size in the settings, so maybe a larger default
helps new users.

mintty: bump the default window size a bit

---

clang/0013-missing-limits.patch
clang/PKGBUILD

clang: rebuild

---

python-certifi/PKGBUILD
python-dulwich/PKGBUILD

Add python-certifi

---

breezy/PKGBUILD
python-fastbencode/PKGBUILD

breezy: Update to 3.2.2

---

python-configobj/PKGBUILD

python-configobj: depend on six; some cleanup

---

gc/PKGBUILD

Also, fix license (it is MIT not GPL) and remove dependency on libatomic_ops.

gc: update to 8.2.2

---

u-boot-tools/PKGBUILD

Signed-off-by: Bin Meng <bin.meng@windriver.com>

u-boot-tools: Update to v2022.07

---

tree/Makefile-Uncomment-for-Cygwin.patch
tree/PKGBUILD

tree: Update to 2.0.4

---

msys2-runtime/update-patches.sh

I [forgot this](https://github.com/msys2/MSYS2-packages/pull/3195#issuecomment-1253003087) one time too many!

msys2-runtime: automatically bump pkgrel when updating patches

---

curl/PKGBUILD

curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

curl: backport http2 fix

---

less/PKGBUILD

less: switch from pcre to pcre2

---

pcre/PKGBUILD

pcre: switch upstream URL

---

elinks-git/PKGBUILD

elinks-git: rebuild

---

perl-TermReadKey/PKGBUILD

add missing perl-devel makedepends

perl-TermReadKey: rebuild

---

readline/PKGBUILD
readline/readline-7.0.3-3.clipboard.patch

readline: Update to 8.2

---

libtool/0003-Pass-various-runtime-library-flags-to-GCC.mingw.patch
libtool/0009-libtool-2.4.2.418-msysize.patch
libtool/0015-Allow-statically-linking-Flang-support-libraries.patch
libtool/PKGBUILD

I built Octave on MINGW64 after upgrading to this version and it still seems to do its job.

libtool: update to version 2.4.7

---

bash/0001-bash-4.4-cygwin.patch
bash/0002-bash-4.3-msysize.patch
bash/0005-bash-4.3-msys2-fix-lineendings.patch
bash/0006-bash-4.3-add-pwd-W-option.patch
bash/0007-fix-static-build.patch
bash/PKGBUILD

bash: Update to 5.2

---

bash/PKGBUILD

bash: update to v5.2 patchlevel 9

---

msys2-runtime/0042-ci-avoid-using-Node.js-12-Actions.patch
msys2-runtime/0043-When-converting-to-a-Unix-path-avoid-double-trailing.patch
msys2-runtime/0044-amend-Special-case-for-converting-root-directory-to-.patch
msys2-runtime/PKGBUILD

See https://github.com/msys2/msys2-runtime/compare/f975120d20d51ca11217e4abbf16cc51ab8c9290...HEAD for details.

msys2-runtime: sync with msys2/msys2-runtime

---

bison/PKGBUILD
diffutils/PKGBUILD
flex/PKGBUILD
gperf/PKGBUILD
groff/PKGBUILD

they still haven't been rebuilt since the group was removed, let's try to get rid of the group

Some base-devel package rebuilds

---

help2man/PKGBUILD
intltool/PKGBUILD
make/PKGBUILD
man-db/PKGBUILD
patch/PKGBUILD
patchutils/PKGBUILD
pkgconf/PKGBUILD
unrar/PKGBUILD
xmlto/PKGBUILD

More old base-devel rebuilds

---

u-boot-tools/PKGBUILD

u-boot-tools: Update to v2022.10

---

gawk/PKGBUILD

gawk: Update to 5.2.1

---

irssi/PKGBUILD

remote !strip, not clear why it's there

irssi: Update to 1.4.3

---

libevent/PKGBUILD
libevent/libevent-2.1.12-openssl-compat.patch

libevent: backport openssl v3 patch

---

mpc/PKGBUILD

mpc.h:287:35: error: unknown type name 'FILE'

mpc: backport fix for undefined FILE

---

python-pip/PKGBUILD

also it should work without setuptools now, as it will install build deps where needed.

pip: Update to 22.3.1

---

msys2-runtime/0037-Revert-Cygwin-Enable-dynamicbase-on-the-Cygwin-DLL-b.patch
msys2-runtime/PKGBUILD

No changes, just moved the patch upstream

msys2-runtime: update

---

python-build/001-use-flit.patch
python-build/PKGBUILD

Backported from upstream.
This should make botostrapping work again after setuptools needs build

python-build: switch to flit

---

perl-Alien-Libxml2/PKGBUILD
perl-HTTP-Cookies/PKGBUILD
perl-IO-HTML/PKGBUILD
perl-IO-Socket-IP/PKGBUILD
perl-Importer/PKGBUILD
perl-LWP-Protocol-https/PKGBUILD
perl-List-MoreUtils/PKGBUILD
perl-Role-Tiny/PKGBUILD
perl-Test-Fatal/PKGBUILD

perl packages not rebuilt in a while

Some perl rebuilds

---

libbsd/001-random-hackery.patch
libbsd/PKGBUILD
libmd/PKGBUILD

Add libmd and libbsd

---

pacman/PKGBUILD
pacman/pacman.conf

pacman: Enable clangarm64 repository

---

file/PKGBUILD

file: Update to 5.44 (v2)

---

icu/PKGBUILD
znc/PKGBUILD

The package grokker pointed to znc needing to be rebuilt.

icu: update to 72.1

---

bash-completion/PKGBUILD
gtk-doc/PKGBUILD
isl/PKGBUILD
itstool/PKGBUILD
libtirpc/PKGBUILD
libtre-git/PKGBUILD
opensp/PKGBUILD
swig/PKGBUILD
txt2html/PKGBUILD

Some rebuilds

---

python-editables/PKGBUILD
python-hatch-vcs/PKGBUILD
python-hatchling/PKGBUILD
python-iniconfig/PKGBUILD
python-pathspec/PKGBUILD

iniconfig 2.0 uses hatchling as a build backend, so add hatchling and all required dependencies

Add python-hatchling and update python-iniconfig

---

sshpass/PKGBUILD

sshpass: Update to 1.10

---

python/900-msysize.patch
python/PKGBUILD

python: some cleanup

---

less/PKGBUILD

helps with https://github.com/gwsw/less/issues/337

less: Update to v629

---

subversion/17-fix-test-link.patch
subversion/PKGBUILD

17-fix-test-link.patch: also skip filesize-test which doesn't link

subversion: Update to 1.14.2

---

autoconf2.13/PKGBUILD
autoconf2.13/autoconf-2.13-Clang-16-fixes-for-various-tests.patch
autoconf2.13/autoconf-2.13-K-R-decls-clang.patch
autoconf2.13/autoconf-2.13-perl-5.26.patch
autoconf2.13/autoconf-2.13-test-fixes.patch

especially the clang ones which we will require for clang v16 compatiblity.

autoconf2.13: import gentoo patches

---

autoconf2.69/PKGBUILD
autoconf2.69/autoconf-2.69-K-R-decls-clang.patch
autoconf2.69/autoconf-2.69-fix-libtool-test.patch
autoconf2.69/autoconf-2.69-make-tests-bash5-compatible.patch
autoconf2.69/autoconf-2.69-perl-5.26-2.patch
autoconf2.69/autoconf-2.69-perl-5.26.patch

autoconf2.69: import gentoo patches

---

autoconf2.71/PKGBUILD
autoconf2.71/autoconf-2.71-AC_C_BIGENDIAN-lto.patch
autoconf2.71/autoconf-2.71-AC_LANG_CALL_C_cxx.patch
autoconf2.71/autoconf-2.71-K-R-decls-clang-deux.patch
autoconf2.71/autoconf-2.71-K-R-decls-clang.patch
autoconf2.71/autoconf-2.71-make-4.4.patch

autoconf2.71: import gentoo patches

---

rhash/1.4.0_rhash-CYGWIN.patch
rhash/PKGBUILD

rhash: Update to 1.4.3

---

nsinstall/PKGBUILD

Required for mingw nspr and nss package

nsinstall: Add package

---

rebase/005-peflags-add-support-for-IMAGE_DLLCHARACTERISTICS_GUA.patch
rebase/PKGBUILD

https://cygwin.com/pipermail/cygwin-apps/2023-April/042816.html

rebase/peflags: add support for reading/writing the CFG flag

---

expect/PKGBUILD
sqlite/PKGBUILD
tcl/PKGBUILD

This is to remove any potential conflict with mingw tcl package

tcl: split development files to separate package

---

rebase/005-peflags-add-support-for-IMAGE_DLLCHARACTERISTICS_GUA.patch
rebase/PKGBUILD

rebase: update cfg patch

---

msys2-runtime-3.3/0050-Cygwin-Fix-compiling-with-w32api-headers-v11.0.0.patch
msys2-runtime-3.3/PKGBUILD

msys2-runtime-3.3: Update & rebuild

---

git/PKGBUILD
git/git-2.8.2-Cygwin-Allow-DOS-paths.patch

git: Update to 2.41.0

---

util-linux/PKGBUILD

util-linux: move to libxcrypt

---

aspell/PKGBUILD

function CHECK:
- fix variable
- remove make flag '-k'
- remove .sig file from sources since public key unknown ERROR: aspell-0.60.8.tar.gz ... FAILED (unknown public key B6D9D0CC38B327D7)

aspell: fix PKGBUILD

---

binutils/PKGBUILD

v1 was #3940 - this time with a backport from master

binutils: Update to 2.41 (v2)

---

git/PKGBUILD
git/git-2.8.2-Cygwin-Allow-DOS-paths.patch

strbuf_add_absolute_path moved to a different file so adjust the patch accordingly. No other changes.

git: Update to 2.42.0

---

git/PKGBUILD
git/git-2.8.2-Cygwin-Allow-DOS-paths.patch

this time without missing includes, so things don't crash

git: Update to 2.42.0 (v2)

---

breezy/PKGBUILD
cython0/PKGBUILD
python-fastbencode/PKGBUILD
python-lxml/PKGBUILD
python-yaml/PKGBUILD

Since python-yaml needs cython 0.x add a cython0 package like Arch
Rebuild everything just to be sure

Update cython to 3.x

---

ruby/PKGBUILD

ruby: Update to 3.2.2

---

nghttp2/PKGBUILD

adjust pkgbase to match dirname

nghttp2: Update to 1.56.0

---

tar/PKGBUILD
tar/tar-1.33-textmount.patch

tar: Update to 1.35

---

gyp/PKGBUILD

gyp: Update to work with Python 3.11

---

pkgconf/384ade5f316367f15da9dbf09853e06fe29bf2bf.patch
pkgconf/PKGBUILD

same as https://github.com/msys2/MINGW-packages/pull/18635

pkgconf: revert commit causing wrong PKG_CONFIG_PATH order

---

texinfo/0002-manifest.all.patch
texinfo/PKGBUILD

texinfo: Update to 7.1

---

mingw-w64-cross-zlib/PKGBUILD

* unset CC to fix cross compiling
* fix the URL
* clean up options while at it

cross-zlib: rebuild

---

sqlite/PKGBUILD

no docs release this time, so split the versions

sqlite: Update to 3.44.1

---

parallel/0001-support-MSys2.patch
parallel/PKGBUILD

parallel: Update to 20231122

---

perl-http-cookiejar/PKGBUILD
perl-libwww/PKGBUILD

perl-libwww: Update to 6.72

---

autoconf2.72/0001-autoconf-2.70-MSYS2-specifics-AC_CYGWIN.patch
autoconf2.72/0002-autoconf-2.70-MSYS2-Autotest-Unify-EOLs-By-Default.patch
autoconf2.72/0003-autoconf-2.70-MSYS2-specifics-config.guess.patch
autoconf2.72/0005-package.patch
autoconf2.72/PKGBUILD
autotools-wrappers/0001-bump-latest-autoconf-version.patch
autotools-wrappers/PKGBUILD

All the removed patches (compared to 2.71) are included in this new release

autoconf: Add autoconf 2.72

---

inetutils/PKGBUILD
inetutils/inetutils-2.5-1.src.patch

inetutils: Update to 2.5

---

libbsd/001-random-hackery.patch
libbsd/PKGBUILD

libbsd: Update to 0.11.8

---

ruby/PKGBUILD
subversion/PKGBUILD

ruby: Update to 3.3.0

---

curl/PKGBUILD
curl/curl-7.58.0-libpsl-static-libs.patch

curl-7.58.0-libpsl-static-libs.patch: simple refresh

curl: Update to 8.6.0

---

libpsl/PKGBUILD

it only needs xsltproc at build time

libpsl: move libxslt to makedepends

---

msys2-runtime/PKGBUILD

See https://github.com/msys2/msys2-runtime/pull/196

msys2-runtime: fix pathconv with quotes

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.mingw
pacman-mirrors/mirrorlist.msys

Remove broken mirror, see https://github.com/msys2/msys2.github.io/issues/180#issuecomment-1936908695

pacman-mirrors: Update to 20240210

---

msys2-runtime-3.3/0051-Cygwin-console-Fix-hangup-of-less-on-quit-after-the-.patch
msys2-runtime-3.3/0052-Adjust-CWD-magic-to-accommodate-for-the-latest-Windo.patch
msys2-runtime-3.3/0053-CI-fix-the-build-with-gcc-13.patch
msys2-runtime-3.3/0054-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
msys2-runtime-3.3/0055-fixup-Add-functionality-for-converting-UNIX-paths-in.patch
msys2-runtime-3.3/0056-nlsfuncs-work-around-an-overzealous-GCC-warning.patch
msys2-runtime-3.3/PKGBUILD

This corresponds to https://github.com/msys2/msys2-runtime/pull/197.
/cc @jeremyd2019

msys2-runtime-3.3: backports from 3.4

---

gdb/PKGBUILD

gdb: add multiarch package

---

ccache/0002-Stop-msys2-from-hanging-forever-Problem-MSYS2-symlin.patch
ccache/PKGBUILD

This solves the problem by not using symlinks but posix open.
This fixes #4311

ccache fix infinite hang

---

msys2-runtime/0055-Cygwin-console-Fix-exit-code-for-non-cygwin-process.patch
msys2-runtime/0056-Cygwin-console-Avoid-slipping-past-disable_master_th.patch
msys2-runtime/0057-Cygwin-pty-Fix-handle-leak-in-master-process.patch
msys2-runtime/0058-Cygwin-pty-Fix-potential-handle-leak-regarding-CallN.patch
msys2-runtime/0059-Cygwin-console-Make-VMIN-and-VTIME-work.patch
msys2-runtime/0060-Cygwin-pipe-Give-up-to-use-query_hdl-for-non-cygwin-.patch
msys2-runtime/PKGBUILD

This corresponds to https://github.com/msys2/msys2-runtime/pull/205.

msys2-runtime: some backports

---

cyrus-sasl/01-fix-plugin-ext.patch
cyrus-sasl/PKGBUILD

cyrus-sasl: Fix loading plugins with proper file extension

---

libunistring/PKGBUILD
libunistring/libunistring-0.9.3-2.src.patch

libunistring: Update to 1.2

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.mingw
pacman-mirrors/mirrorlist.msys

Remove mirror.ufro.cl
according to https://mirror.ufro.cl/ our mirror was removed

pacman-mirrors: Update to 20240504

---

pactoys/PKGBUILD

See https://github.com/msys2/pactoys/pull/6

pactoys: Update to r65.b5fcc0f

---

pacman-contrib/0100-contrib.patch
pacman-contrib/PKGBUILD

pacman-contrib: Update to 1.10.6

---

.github/workflows/generate-srcinfo.yml
.github/workflows/main.yml
python-mako/PKGBUILD

See https://github.com/msys2/MINGW-packages/pull/21022

CI: do a treeless clone in case we need the history

---

iperf/0001-build-fix.patch
iperf/PKGBUILD

* backport build fix
* uncomment "make check", passes here

iperf: Update to 2.2.0

---

ruby/PKGBUILD

ruby: Update to 3.3.2

---

msys2-runtime/0039-Cygwin-disable-high-entropy-VA-for-ldh.patch
msys2-runtime/PKGBUILD

See https://github.com/msys2/msys2-runtime/pull/217

msys2-runtime: Update (ldd hang fix)

---

msys2-w32api-headers/PKGBUILD
msys2-w32api-runtime/PKGBUILD

https://github.com/mingw-w64/mingw-w64/compare/05598db99...819a6ec2e

msys2-w32api: Update to 12.0.0

---

mingw-w64-cross-crt/PKGBUILD
mingw-w64-cross-headers/PKGBUILD
mingw-w64-cross-tools/PKGBUILD
mingw-w64-cross-winpthreads/PKGBUILD
mingw-w64-cross-winstorecompat/PKGBUILD

https://github.com/mingw-w64/mingw-w64/compare/05598db99...819a6ec2e

mingw-w64-cross: Update to v12.0.0

---

pv/PKGBUILD

upstream changed licence starting with 1.8.0

pv: Update to 1.8.10

---

gi-docgen/PKGBUILD
python-docutils/PKGBUILD
python-smartypants/PKGBUILD
python-typogrify/PKGBUILD
python-typogrify/jinja-3.1.patch

python-docutils for man pages, the rest for API docs, though that also needs introspection, and we don't have any of that yet.

Add some Python packages for glib

---

python/PKGBUILD

there is a address space conflict

python: rebuild again

---

meson/PKGBUILD

this should make msys2-tests happy again

meson: backport a regression fix

---

mingw-w64-cross-crt/PKGBUILD

mingw-w64-cross-crt: convert to split package

---

c-ares/PKGBUILD

Add new key to validpgpkeys (see upstream website)

c-ares: Update to 1.33.0

---

libssh/PKGBUILD

https://gitlab.com/libssh/libssh-mirror/-/issues/268
https://gitlab.com/libssh/libssh-mirror/-/issues/269

libssh: Update to 0.11.0

---

glib2/PKGBUILD

Set new glib_debug as suggested upstream

glib2: Update to 2.82.0

---

pacman/PKGBUILD
pacman/makepkg_mingw.conf

frame-pointers are already enabled for rust package, so let's put it for all rust-based packages
push repo checksum while at it

makepkg-mingw.conf: add RUSTFLAGS

---

mingw-w64-cross-crt/PKGBUILD
mingw-w64-cross-headers/PKGBUILD
mingw-w64-cross-tools/PKGBUILD
mingw-w64-cross-winpthreads/PKGBUILD
mingw-w64-cross-winstorecompat/PKGBUILD

https://github.com/mingw-w64/mingw-w64/compare/819a6ec2e...c6bf4bdf6

mingw-w64-cross: Update to c6bf4bdf65

---

msys2-runtime/0040-Cygwin-pipe-Fix-a-regression-that-raw_write-slows-do.patch
msys2-runtime/PKGBUILD

This corresponds to https://github.com/msys2/msys2-runtime/pull/227.

msys2-runtime: slow pipe fix

---

gawk/PKGBUILD

gawk: Update to 5.3.1

---

openssh/PKGBUILD

https://www.openssh.com/releasenotes.html

openssh: Update to 9.9p1

---

msgpack-c/PKGBUILD
tmate/PKGBUILD
tmate/msgpack-v6.patch

msgpack-c: Update to 6.1.0

---

tmux/PKGBUILD

tmux: Update to 3.5

---

ruby/PKGBUILD

ruby: Update to 3.3.5

---

lua/PKGBUILD

lua: add 5.4.7

---

tmux/PKGBUILD

tmux: Update to 3.5a

---

cocom/PKGBUILD

Added [WANT_AUTOCONF="2.69"] and changed check to make test.
Tim S.

cocom: WANT_AUTOCONF="2.69" autoreconf -fi

---

ruby/PKGBUILD

ruby: Update to 3.3.6

---

curl/PKGBUILD

same as https://github.com/msys2/MINGW-packages/pull/22490

curl: backport netrc regression fixes

---

msys2-runtime/0043-fixup-cygthread-suspend-thread-before-terminating.patch
msys2-runtime/PKGBUILD

See https://github.com/msys2/msys2-runtime/pull/236

msys2-runtime: Update (suppress proc_waiter error messages)

---

msys2-runtime-3.3/0058-fixup-cygthread-suspend-thread-before-terminating.patch
msys2-runtime-3.3/0059-Cygwin-revert-use-of-CancelSyncronousIo-on-wait_thre.patch
msys2-runtime-3.3/PKGBUILD

msys2-runtime-3.3: update

---

cmake/PKGBUILD

@lazka please update cmake to 3.31.2

cmake: Update to 3.31.2

---

curl/PKGBUILD

Remove backports included in the new release

curl: Update to 8.11.1

---

libiconv/1.16-aliases.patch
libiconv/1.16-cross-install.patch
libiconv/PKGBUILD

libiconv: Update to 1.18

---

ccache/PKGBUILD

ccache: Rebuild after fmt-11 update

---

msys2-runtime/0045-Cygwin-signal-Do-not-handle-signal-when-__SIGFLUSHFA.patch
msys2-runtime/PKGBUILD

See https://github.com/msys2/msys2-runtime/pull/251

msys2-runtime: backport signal hang fix

---

ninja/PKGBUILD

ninja: Fix bash completion installation directory

---

tree/Makefile-Uncomment-for-Cygwin.patch
tree/PKGBUILD

tree: Update to 2.2.1

---

shutdown/PKGBUILD

cygwin shotdown utils
Fixes #1208

shutdown: Add 2.0.0

---

u-boot-tools/PKGBUILD

u-boot-tools: Add mkenvimage

---

pacman-mirrors/PKGBUILD
pacman-mirrors/mirrorlist.mingw
pacman-mirrors/mirrorlist.msys

See https://github.com/msys2/msys2.github.io/issues/364

pacman-mirrors: Update to 20250220

---

diffutils/PKGBUILD

autoreconf is broken, so skip it

diffutils: Update to 3.11

---

zsh/0004-pcre2.patch
zsh/PKGBUILD

pcre is unmaintained for years

zsh: build with pcre2

---

gnulib-l10n/PKGBUILD

gnulib-l10n: Add 20241231

---

enscript/PKGBUILD
enscript/enscript-EXEEXT.patch

Build as cygwin.
Based on a review of Cygwin's source package.
Note that there is a .sig file, but the signing key has been revoked
(possibly because it is a dsa1024 key?)

enscript: add patch, update url

---

libblake3/PKGBUILD

libblake3: Add 1.6.1

---

mingw-w64-cross-crt/PKGBUILD
mingw-w64-cross-headers/PKGBUILD
mingw-w64-cross-tools/PKGBUILD
mingw-w64-cross-winpthreads/PKGBUILD
mingw-w64-cross-winstorecompat/PKGBUILD

https://github.com/mingw-w64/mingw-w64/compare/9c93e483b...850703ae4

mingw-w64-cross: Update to 850703ae46

---

nnn/PKGBUILD

the makefile complains about it:
https://github.com/msys2/MSYS2-packages/pull/5282#issuecomment-2758932197

nnn: makedep on pkgconf

---

msys2-runtime/PKGBUILD
msys2-runtime/signal-crash-backport.patch

See https://github.com/msys2/msys2-runtime/issues/272

msys2-runtime: more backports

---

fish/0001-cmake-4-backport.patch
fish/PKGBUILD

backport fix for building with cmake 4

fish: fix for building with cmake 4

---

curl/PKGBUILD
curl/curl-7.60.0-gssapi-static-libs.patch

curl: Update to 8.13.0

---

llvm/PKGBUILD

I don't know if this warrants a pkgrel bump.  I think the only real change would be the LLVMConfig.cmake file.

llvm: remove unnecessary MINGW-packages detritus

---

libgit2/0001-missing-alloca.patch
libgit2/PKGBUILD

Add libgit2

---

ruby/PKGBUILD

ruby: Update to 3.4.3

---

texinfo/0005-fix-makeinfo-exeext.msys2.patch
texinfo/PKGBUILD

* patch refresh
* (share/lib)/texinfo got renamed to texi2any

texinfo: Update to 7.2

---

curl/PKGBUILD
curl/openssl-no-cleanup.patch

Align with https://github.com/msys2/MSYS2-packages/pull/3448
See also https://github.com/curl/curl/issues/17262

libcurl: don't call OPENSSL_thread_stop

---

mingw-w64-cross-mingwarm64-crt/PKGBUILD
mingw-w64-cross-mingwarm64-headers/PKGBUILD
mingw-w64-cross-mingwarm64-tools/PKGBUILD
mingw-w64-cross-mingwarm64-winpthreads/PKGBUILD
mingw-w64-cross-mingwarm64-winstorecompat/PKGBUILD

https://github.com/Windows-on-ARM-Experiments/mingw-woarm64/compare/41a713605cd1630e...70d63e7c9a477b

mingw-w64-cross-mingwarm64: Update to 70d63e7c9a

---

mingw-w64-cross-crt/PKGBUILD
mingw-w64-cross-headers/PKGBUILD
mingw-w64-cross-tools/PKGBUILD
mingw-w64-cross-winpthreads/PKGBUILD
mingw-w64-cross-winstorecompat/PKGBUILD

https://github.com/mingw-w64/mingw-w64/compare/850703ae4...2ca6f1348

mingw-w64-cross: Update to 2ca6f1348c

---

libgit2/PKGBUILD

but even this fix seems to not work...
closes #5412

libgit2: fix pkgconf file installation

---

ngtcp2/PKGBUILD

without any crypto helpers for starters

ngtcp2: Add 1.13.0

---

pacman/0004-test-fixes.patch
pacman/0005-Remove-everything-related-to-sudo-fakeroot-file-perm.patch
pacman/0012-Remove-ldconfig.patch
pacman/0032-Translate-MSYS2-specific-messages-into-Japanese.patch
pacman/0033-fixup-Core-update.patch
pacman/PKGBUILD

This corresponds to msys2/msys2-pacman#57

pacman: update patches

---

mingw-w64-cross-crt/PKGBUILD
mingw-w64-cross-headers/PKGBUILD
mingw-w64-cross-tools/PKGBUILD
mingw-w64-cross-winpthreads/PKGBUILD
mingw-w64-cross-winstorecompat/PKGBUILD

https://github.com/mingw-w64/mingw-w64/compare/2ca6f1348...b45abfec4

mingw-w64-cross: Update to b45abfec4e

---

msys2-runtime/0042-Cygwin-pipe-Fix-SSH-hang-with-non-cygwin-pipe-reader.patch
msys2-runtime/0043-Cygwin-pipe-Update-source-comment-align-with-previou.patch
msys2-runtime/0044-Cygwin-pipe-Make-pipe_data_available-return-PDA_UNKN.patch
msys2-runtime/0045-Cygwin-console-Set-ENABLE_PROCESSED_INPUT-when-disab.patch
msys2-runtime/PKGBUILD
msys2-runtime/msys2-runtime.commit

This corresponds to https://github.com/msys2/msys2-runtime/pull/296.

msys2-runtime: backport recent fixes

---

squashfs-tools/0001-fix-cygwin.patch
squashfs-tools/PKGBUILD

Add squashfs-tools

---

ruby/PKGBUILD

ruby: Update to 3.4.5

---

llvm/0016-LLVM-Cygwin-Enable-conditions-that-are-shared-with-M.patch
llvm/0017-llvm-objcopy-COFF-Ignore-associative-sections-in-exe.patch
llvm/0018-lli-Fix-crash-with-no-process-syms-on-MinGW-151386.patch
llvm/0019-llvm-Enable-building-Analysis-plugins-on-Cygwin-1513.patch
llvm/0020-LLVM-adjust-lit.cfg.py-for-Cygwin-151416.patch
llvm/0021-LLVM-Support-Fix-tests-on-Cygwin-151417.patch
llvm/0022-LLVM-lit-add-system-cygwin-feature-152780.patch
llvm/0023-hack-tablegentest.patch
llvm/0102-Clang-Cygwin-Enable-few-conditions-that-are-shared-w.patch
llvm/0122-Tests-Add-system-cygwin-feature-and-use-it.-152611.patch
llvm/PKGBUILD
llvm/README-patches.md

This corresponds with what was published as a test release on Cygwin.

llvm: refresh patches

---

texinfo/PKGBUILD

https://github.com/msys2/MSYS2-packages/commit/120d619b4d629f7382e6a4d865116ce0c4a04a49#commitcomment-164328097

texinfo: add gnulib workaround to fix build

---

ansible-core/PKGBUILD
ansible/PKGBUILD

Local build environment:
* OS: Windows 11 24H2
* MSYS2 Version: 20250830.0.0
Ansible and Ansible Galaxy version:
```text
ansible [core 2.19.2]
config file = None
configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.12/site-packages/ansible
ansible collection location = /home/vagrant/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/bin/ansible
python version = 3.12.11 (main, Jun  9 2025, 11:30:55) [GCC 13.3.0] (/usr/bin/python.exe)
jinja version = 3.1.6
pyyaml version = 6.0.2 (with libyaml v0.2.5)
ansible-galaxy [core 2.19.2]
config file = None
configured module search path = ['/home/vagrant/.ansible/plugins/modules', …
```

ansible-core: Update to 2.19.2, ansible: Update to 12.0.0

---

ruby/PKGBUILD

ruby: Update to 3.4.6

---

ansible-core/0001-ctypes-cdll-loadlibrary-msys2.patch
ansible-core/PKGBUILD
ansible/PKGBUILD

<https://forum.ansible.com/t/release-announcement-ansible-community-package-12-1-0/44629>

ansible/ansible-core: update to 12.1.0/2.19.3
